### ISSUE TITLE
Willkommens E-Mail konzipieren

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#10]
Was wollen wir unseren Held:innen per E-Mail schicken, wenn sie sich angemeldet haben?

Ein paar Gedanken dazu:
* Duzen?
* Link um E-Mail Adresse zu bestätigen?
* Link um Daten zu editieren/löschen?
* Kurze Info zum Prozess?
* Link zur Map?

**Comment by weliveindetail** [comment]
In Progress hier im Google Doc:
https://docs.google.com/document/d/1DkU6N3XARyWXgZTGdJGCAp8VQxJVJuGI5iMLX-SWC9Q/edit#

**Comment by ImmunHeldin-CE** [comment]
Super!
