### ISSUE TITLE
Übersetzung youknow Film auf Englisch

### ISSUE THREAD

**Issue by vikiarn** [ImmunHelden/ImmunHelden.de#103]

**Comment by vikiarn** [comment]
Auswahl der Stimme: https://intern.you-know.de/speaker/?p=IMU-05574&l=de&s=en-US&t=1590407486485

**Comment by vikiarn** [comment]
Auswahl der Stimme: https://intern.you-know.de/speaker/?p=IMU-05574&l=de&s=en-US&t=1590407486485

**Comment by weliveindetail** [comment]
Fertig: https://www.youtube.com/watch?v=61HJz_PGbiI
