### ISSUE TITLE
Blutspendeeinrichtungen für Antikörperbehandlungen

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#11]
Könnte mit einem Schlag eine recht große Zahl von "Angeboten" generieren.

**Comment by DominikGolle** [comment]
https://ukm-blutspende.de/index.php?id=rekonvaleszentenplasma

**Comment by weliveindetail** [comment]
https://www.dortmund.de/de/leben_in_dortmund/nachrichtenportal/alle_nachrichten/nachricht.jsp?nid=626978

**Comment by weliveindetail** [comment]
Ich denke das ist dringend. Daher würde ich die Kontaktanfragen zunächst mal übernehmen. Ich geb das Thema aber möglichst bald gern an jemanden ab.

**Comment by weliveindetail** [comment]
Klinikum in Dortmund klingt sehr interessiert und wartet nur auf Rücksprache mit Chefarzt. Bleibe in Kontakt mit ihnen.

**Comment by DominikGolle** [comment]
Wow, super!!!

--
 Dominik Golle
 dominikgolle@fastmail.com
 Public Key ID: A7C6A5DF (RSA 4096 bit)



Am Fr, 24. Apr 2020, um 12:25, schrieb Stefan Gränitz:

**Comment by weliveindetail** [comment]
Das UKM in Münster ist auch sehr begeistert. Für einen Pin auf unserer Karte warten sie noch auf das Go ihrer Marketing Abteilung. Sie haben einen Prozess, der für unsere Vermittlung relevant ist und hier beginnt:
https://static.uni-muenster.de/covid19/

**Comment by DominikGolle** [comment]
Ok, wie war das mit Betaphase? :D
Päm!

--
 Dominik Golle
 dominikgolle@fastmail.com
 Public Key ID: A7C6A5DF (RSA 4096 bit)



Am Fr, 24. Apr 2020, um 13:29, schrieb Stefan Gränitz:

**Comment by ImmunHeldin-CE** [comment]
Liste aller Rekonvaleszentenplasma-Zentren in D: https://www.blutspenden.de/blutspendedienste/

**Comment by weliveindetail** [comment]
Die Liste kommt vom BZgA, was laut Hannes eine "nachgeordnete Behörde" des BMG (Gesundheitsministerium) ist. Wir sollten bis Anfang der Woche auf das Feedback des UKM und KlinikumDo warten (evtl. haben sie gute Vorschläge für Verbesserungen bei uns) und dann ggf gleich das BMG kontaktieren und fragen, ob wir die ganze Liste übernehmen können.

**Comment by ImmunHeldin-CE** [comment]
Haben wir einen Kontakt zum BGM? Ich glaube nicht, dass BZgA oder BGM entscheiden dürfen, ob wir diese Organisationen ohne deren explizite Einwilligung auf unserer Website listen können, kann am Montag aber mal beim BzGA nachfragen.
Alternativ schreiben wir eine nicht personalisierte Infomail direkt an alle Blutspendedienste bzw. deren Dachorganisationen (Haema, DRK, Caritas usw., die Unikliniken müssen wir wahrscheinlich einzeln anschreiben).

**Comment by weliveindetail** [comment]
Hatte deinen Post hier nicht gesehen, sorry. Dachorganisationen kontaktieren klingt gut. Idealerweise könnten wir die Daten direkt von der BZgA Seite holen um den Aufwand zu vermeiden die abtippen und in Sync halten zu müssen. Ganz nebenbei wäre unsere Map dafür auch ideal geeignet ;)

Hannes hat mir geraten mal Christian Kohl vom BZgA zu kontaktiert und um eine kurzes Gespräch zu bitten. Er ist "Zentraler Ansprechpartner für die Firmenblutspende in Bayern" (https://www.blutspendedienst.com/partner/blutspende-in-unternehmen). Mal sehen ob er sich meldet.

Auf das Feedback der beiden Unikliniken warte ich nach wie vor. Sollte ich morgen noch mal anrufen und "drängeln" oder besser noch warten? (Hatte Freitag so um die Mittagszeit mit ihnen gesprochen.)

**Comment by ImmunHeldin-CE** [comment]
Super, hoffen wir mal, dass ein Gespräch mit dem BZgA zustande kommt! 
Drängeln find ich gut ;)

**Comment by weliveindetail** [comment]
Hannes sagt ich sollte ihm 5 Tage einräumen, bevor ich nachhake. Mal schauen 🤔

**Comment by weliveindetail** [comment]
E-Mail mit Preview an die Charite ist raus. Hier als Vorlage für weitere Kontaktaufnahmen:
[Vermittlung Rekonvaleszenten-Plasmaspender.pdf](https://github.com/ImmunHelden/ImmunHelden.de/files/4552048/Vermittlung.Rekonvaleszenten-Plasmaspender.pdf)

Ich mach jetzt noch zwei Previews für UKM und KlinikumDo und sende es hinterher mit der Bitte um Feedback.

**Comment by weliveindetail** [comment]
Follow-ups mit UKM und KlinikumDo sind auch raus.

Als nächstes will ich die Demo mit den drei Einträgen online bringen. Sobald sie sich melden, schick ich ihnen den Link, wo sie die exakte Pin-Position setzen können und unsere Datenschutzrichtlinien bestätigen + Frage nach Feedback natürlich. Das muss dann eingearbeitet werden.

Hoffentlich haben wir bis dann was vom BZgA. Idealerweise könnten wir am Wochenende schon starten ihre Datenbank anzubinden. Naja mal sehen 🙂

**Comment by weliveindetail** [comment]
Eine Woche muss man einplanen für Behördenkommunikation 🙂 

>Hallo Herr Gränitz,
>
>herzlichen Dank für Ihre Mail und bitte entschuldigen Sie meine späte Rückmeldung!!
>Lassen Sie uns gerne telefonieren. Würde Ihnen Montag um 12 Uhr passen?
>
>Beste Grüße
>Christian

**Comment by weliveindetail** [comment]
Preview gemerged: https://github.com/ImmunHelden/WirVsVirusMap/pull/1

**Comment by weliveindetail** [comment]
Notizen vom Telefonat mit Herr Kohl heute.

* Wie hoch wird die Nachfrage sein? _Unklar_
* Können Kapazitäten das leisten? _Unklar, aber Kapazitäten wären schon da_
* Andere Initiativen? _Nein aber RKI Projekt -> Kontakt Dienstag_
* Spenderprofil? _Bis frühe Zwanziger. Dann große Lücke. Top Spender werden langsam aber sicher zu Patienten._
* Welche Spender via Blutspenden.de? _Unklar_
* Digital-affine "Nichtspender" aktivieren? _Sehr gern!_
* BZgA Blutspenden.de _Kontakt Dienstag
* Fragebogen für großangelegte Antikörperspende vereinheitlichen? _Sehr gern. Herausforderung für Plasmaspende generell! Kontakte: RKI, Paul Ehrlich Institut, Bundesärztekammer, Helmholzinstitut -> Kontakt Dienstag_

**Comment by weliveindetail** [comment]
Wir haben bisher leider nur das bekommen: https://www.rki.de/SharedDocs/Kontaktformulare/O/Offergeld_Ruth/Integrator.html

Hab nochmal nachgehakt ob sich beim BZgA doch nicht zumindest jemand zur technischen Umsetzung von blutspenden.de findet.

**Comment by weliveindetail** [comment]
Alternativ könnten wir auf eigene Faust die Daten der Zentren zur Antikörperspende raus kopiern und bei uns hosten. Dann haben wir Ende der Woche ein Angebot auf unserer Seite.

**Comment by DominikGolle** [comment]
Pate Dr. Henrik Matthies vom Health Innovation Hub hat uns mit https://www.antikoerper-online.de/ vernetzt, die eine Liste von Rekonvaleszenzzentren haben sollten. Er hat auch dort angefragt, ob sie unsere Mentoren werden wollen.

**Comment by weliveindetail** [comment]
Gibt ein erstes Ergebnis meines [extra geschriebenen Scripts für blutspenden.de](http://immunhelden.de/parseBlutspendenDe), das die Daten automatisiert grob aus der Seite parst.

Hier können wir es gemeinsam bearbeiten -- **Achtung: nicht mehrere parallel UND speichern drücken wenn ihr fertig seid (ggf. kopieren bevor ihr den Tab schließt)** 😃 :
http://jsoneditoronline.org/#left=cloud.e5477329fbd043e7875f9bef6b779f07&right=local.bibafe

Von hier aus müssen wir leider händisch rann. Die ersten beiden Einträge hab ich mal exemplarisch gemacht. Die Adressen sind das wichtigste. **Wer würde sich bereit erklären die übrigen Einträge nachzuarbeiten?**

Ich würde derweil einen Import für die Map bauen.

**Comment by ImmunHeldin-CE** [comment]
Seid ihr euch wirklich sicher, dass es datenschutzrechtlich OK ist, die Blutspendezentren ohne ihr Einverständnis auf unserer Map zu verzeichnen?  @DominikGolle könntest du das vielleicht noch die Datenschutzberatung fragen?

**Comment by DominikGolle** [comment]
Das hat eigentlich keine Datenschutzrelevanz, weil keine personenbezogenen Daten betroffen sind. Zudem sind die Daten ja eh öffentlich verfügbar. Man darf ja auch Geschäfte auf Google Maps eintragen, ohne zu fragen.
Rechtlich sehe ich also kein Problem. Trotzdem kann ich mir vorstellen, dass manche Einrichtungen ähnlich reagieren - von dem her wäre es schon besser, mindestens nachträglich sagen zu können, dass wir die Daten von einer der offiziellen Listen erhalten haben.

**Comment by weliveindetail** [comment]
Wenn wir die Liste bis heute Abend nachgearbeitet bekommen, haben wir morgen eine Karte mit Angeboten.

**Comment by weliveindetail** [comment]
Ok aus den ersten beiden Einträgen kann ich jetzt [diese Map generieren](https://weliveindetail.github.io/WirVsVirusMap/plasma.html). Learnings:
* alle HTML Tags raus und nur die echten Informationen drin lassen
* `title` darf nicht zu lang sein, sonst passt er nicht ins Popup
* in `email` bitte manuell `(at)` durch ein echtes `@` ersetzen
* bei `url`s bitte überprüfen, ob sie tatsächlich funktionieren
* `phone` kann Leerzeichen und Striche enthalten, führende `0` wird automatisch durch `+49` ersetzt

Wenn wir ein mal durch sind haben wir einen guten ersten Datensatz!

<img width="894" alt="Screenshot 2020-05-07 at 16 45 11" src="https://user-images.githubusercontent.com/7307454/81308656-525a0180-9082-11ea-9c73-af53c9328a11.png">

**Comment by DominikGolle** [comment]
Jetzt nicht grad top prio, aber:
Könnten wir, wenn kein mobiler Browser festgestellt wird, bei Klick auf die Telefonnummer direkt einen Anruf per Jitsi (oder einen anderen Dienst) starten? Festnetztelefonie kostet ja kaum noch was - da könnten wir auch etwas Guthaben springen lassen, wenn es daran scheitern würde.

**Comment by Highkovic** [comment]
Ich mache das, bitte alle anderen aus der Datei draußen bleiben - danke!

**Comment by weliveindetail** [comment]
Dank @Highkovic Einsatz sind es nun schon über 30 Locations! YEY! 🎉 

<a href="https://weliveindetail.github.io/WirVsVirusMap/plasma.html"><img width="449" alt="Screenshot 2020-05-07 at 18 18 44" src="https://user-images.githubusercontent.com/7307454/81318999-550f2380-908f-11ea-9046-7bb5ac2a9b01.png"></a>

**Comment by weliveindetail** [comment]
Die übrigen hat mein Parser nicht korrekt erkannt. Da arbeite ich dran. Wenn ihr in der Zwischenzeit helfen wollt, dann schnappt euch ein Bundesland, schreibt hier im Chat welches ihr habt und schaut in der Map:
* machen die Infos generell Sinn?
* sind genügend Kontakmöglichkeiten gegeben?
* stimmt die URL der Webseite?

Wenn euch was auffällt könnte ihr hier eine Notiz machen: https://github.com/weliveindetail/WirVsVirusMap/commit/22d489bb0c7059cc0499fb6ba2f32b59080dfbb5#diff-4e1b2387b1f3416cbf43d5a8eca6a96a

**Comment by weliveindetail** [comment]
Parser gefixt und Update committed. Über 130 Locations jetzt online.

<a href="https://weliveindetail.github.io/WirVsVirusMap/plasma.html">
<img width="521" alt="Screenshot 2020-05-08 at 12 51 56" src="https://user-images.githubusercontent.com/7307454/81399162-cf40b600-912a-11ea-847f-c2c59299818a.png">
</a>

**Comment by weliveindetail** [comment]
Wenn jemand Fehler finden, bitte hier markieren: https://github.com/weliveindetail/WirVsVirusMap/commit/7862f956bb768339df8797686fd040d6fdeb411d

**Comment by Highkovic** [comment]
Top, soll ich da nochmals drüber schauen und wieder glattziehen wie gestern?--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 08.05.20, 12:54 schrieb "Stefan Gränitz" <notifications@github.com>:

   
  Parser gefixt und Update committed. Über 130 Locations jetzt online.

**Comment by weliveindetail** [comment]
> Top, soll ich da nochmals drüber schauen und wieder glattziehen wie gestern?

@Highkovic Das Ergebnis das aus dem Parser heraus fällt, ist jetzt deutlich besser als gestern. Wenn du es schaffst, wäre es super direkt in der Karte zu schauen prüfen, ob die Einträge Sinn machen, die Webseiten erreichbar sind, usw.

Vielleicht ein Bundesland nach dem anderen und hier markieren, falls es Fehler gibt: weliveindetail/WirVsVirusMap@7862f95

Also QA im Prinzip 👍 🙂

**Comment by weliveindetail** [comment]
Die IDs der Locations werden jetzt beibehalten, auch wenn ich die Map neu generiere. Wir haben jetzt Permalinks und die werden auch als Link in den Details angezeigt, z.B.:
https://weliveindetail.github.io/WirVsVirusMap/plasma.html#blutspendende-dBBpkOgvtUi

Im Laufe des Tages sind 5 neue Einträge dazu gekommen. Wer auch immer blutspenden.de betreibt, scheint neue Locations hinzuzufügen 🤔
https://github.com/weliveindetail/WirVsVirusMap/commit/cd7eca896c199567bafae8a48058873ec5c3439b
