### ISSUE TITLE
Alle Profilbilder durch das neue Logo ersetzen

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#116]
Da wir nun schon ein Logo mit Schriftart und allem drum und dran haben, sollten wir bis nächste Woche alle Profilbilder aktualisieren.

**Comment by weliveindetail** [comment]
Done: https://github.com/ImmunHelden/

**Comment by weliveindetail** [comment]
Done: https://wirvsvirus.projecttogether.org/profile

**Comment by weliveindetail** [comment]
# 2 Varianten mit transparentem Hintergrund

Default:
![logo_default](https://user-images.githubusercontent.com/7307454/83170479-e0bb2380-a114-11ea-9168-fff3ca5a5a74.png)

Quadratisch:
![logo_square](https://user-images.githubusercontent.com/7307454/83170486-e1ec5080-a114-11ea-99e3-55bae2194678.png)

# 2 Varianten mit weißem Hintergrund

Rund:
![logo_circle_wirvsvirus](https://user-images.githubusercontent.com/7307454/83170477-e0228d00-a114-11ea-9ce1-87785d93b765.png)

Rechteckig:
![logo_rect_wirvsvirus](https://user-images.githubusercontent.com/7307454/83170482-e153ba00-a114-11ea-8ca1-01668532be06.png)

Sollen wir noch mehr/andere Varianten machen?

**Comment by weliveindetail** [comment]
Done: https://www.youtube.com/channel/UC1cCZ_OYkbLXCp9nQh7SMJw

**Comment by Highkovic** [comment]
Entscheidung ist gefallen: wir nehmen das Logo, zumindest haben wir aktuell keine Alternativen

**Comment by Highkovic** [comment]
Done: https://www.facebook.com/ImmunHelden
Done: https://www.instagram.com/immuneheroes/
Done: https://twitter.com/ImmunHelden

**Comment by Highkovic** [comment]
> # 2 Varianten mit transparentem Hintergrund
> Default:
> ![logo_default](https://user-images.githubusercontent.com/7307454/83170479-e0bb2380-a114-11ea-9168-fff3ca5a5a74.png)
> 
> Quadratisch:
> ![logo_square](https://user-images.githubusercontent.com/7307454/83170486-e1ec5080-a114-11ea-99e3-55bae2194678.png)
> 
> # 2 Varianten mit weißem Hintergrund
> Rund:
> ![logo_circle_wirvsvirus](https://user-images.githubusercontent.com/7307454/83170477-e0228d00-a114-11ea-9ce1-87785d93b765.png)
> 
> Rechteckig:
> ![logo_rect_wirvsvirus](https://user-images.githubusercontent.com/7307454/83170482-e153ba00-a114-11ea-8ca1-01668532be06.png)
> 
> Sollen wir noch mehr/andere Varianten machen?

Nein, das sollte aus meiner Sicht reichen
