### ISSUE TITLE
Partnerschaft mit ähnlichen Organisationen

### ISSUE THREAD

**Issue by vikiarn** [ImmunHelden/ImmunHelden.de#126]

**Comment by vikiarn** [comment]
Hallo: ich bin auf dieses Projekt (auch von wirvsvirus) gestoßen: https://www.immunspender.com/

Die machen so ziemlich das gleiche wie wir - die Seite ist ziemlich aufschlussreich und gut erklärt. Sie sind gerade im Crowdfundingverfahren.

Darüber könnten wir nächsten Montag mal sprechen.

**Comment by DominikGolle** [comment]
Anscheinend sind die das erste Projekt im Crowdmatching-Fonds, dass das Fundraising erfolgreich abgeschlossen hat. D.h. sie scheinen gute PR zu haben und haben spätestens durch das Crowdfunding auch einen gewissen Bekanntheitsgrad.

**Comment by Highkovic** [comment]
Verrückt, dass sie bislang nicht aufgefallen sind. Definitiv ein Thema für Montag! V.a., was uns von ihnen unterscheidet

**Comment by weliveindetail** [comment]
> Hallo: ich bin auf dieses Projekt (auch von wirvsvirus) gestoßen: https://www.immunspender.com/

Good catch! Wie können wir herausfinden wie hoch ihr Bekanntheitsgrad ist? Den könnten wir ja gut gebrauchen und die könnten unsere Map bestimmt gut gebrauchen.

**Comment by weliveindetail** [comment]
Hab mich interessehalber mal angemeldet.

> Übrigens: Wir haben eine Immunspender Gruppe bei Facebook eingerichtet, damit Du Dich mit anderen austauschen kannst: https://www.facebook.com/groups/immunspende/

Datenschutztechnisch spannend 😄 Bis jetzt "13 Mitglieder insgesamt" -- können wir aber mal auf dem Schirm behalten.

@Highkovic Du managest den FB Account oder? :)

**Comment by Highkovic** [comment]
Viki kontaktiert die ImmunSpender bzgl. einer möglichen Kooperation: wir könnten perspektivisch z.B. ihren Fragebogen nutzen und sie wiederum unsere Map.
Zwischenstatus dazu: nächster Call

**Comment by vikiarn** [comment]
Hierzu fand Gespräch statt - großes Interesse von Seiten der ImmunSpender an einer Kooperation (v.a. Marketing und Teilen von Kotakten etc.); gerne ein Group-Call mit ihnen - Terminfindung

**Comment by vikiarn** [comment]
Wir werden als Team mit den Immunspendern sprechen und vorab in Google Docs einige Fragen zusammenstellen.
Hier das Google Doc Dokument: https://docs.google.com/document/d/1BTSwmTfgjrEIcS9JwAPD2ALcKzONnBOztcqooK9pPL0/edit?usp=sharing
