### ISSUE TITLE
Outreach

### ISSUE THREAD

**Issue by DominikGolle** [ImmunHelden/ImmunHelden.de#13]
- Kampagne für Outreach zu ImmunHeld:innen planen
- Ballungszentrum mit den meisten Partnern für eine Beta Phase auswählen

**Comment by ImmunHeldin-CE** [comment]
Outreach via LinkedIn: LinkedIn.com/gemeinsamhelfen --> Corona-Jobs und Möglichkeiten, sich zu engagieren. Siehe https://github.com/weliveindetail/ImmunHelden.de/issues/28

**Comment by weliveindetail** [comment]
Outreach via Vodafone Institute. Sie bieten uns ihre Social Media Kanäle an. Siehe: https://github.com/weliveindetail/ImmunHelden.de/issues/31

**Comment by weliveindetail** [comment]
Hi @SonjaJDoering. Das Ticket war ja bis jetzt sehr allgemein. Damit wir unseren Fortschritt dokumentieren können, hab ich zunächst den Zeitraum eingeschränkt (bis Milestone Vodafone). 

Die nächste Frage wäre vielleicht, was wir in der Zeit schaffen oder probieren wollen (z.B. Freunde und Bekannte involvieren, YouKnow Video verbeiten, etc.) und was wir dafür brauchen (z.B. Facebook Account, Grafiken, Banner, Erfahrungsberichte, etc.).

Wenn wir dafür Ideen sammeln und für uns selbst einen/verschiedene Paths to Action formulieren können, bringt uns das bestimmt schon voran.

**Comment by weliveindetail** [comment]
Sorry, hab jetzt erst im Nachhinein https://github.com/ImmunHelden/ImmunHelden.de/issues/88 gesehen. Outreach wird eines der wichtigen Punkte im Board sein richtig?

**Comment by DominikGolle** [comment]
Läuft unter #88
