### ISSUE TITLE
Map erweitern um neue Anzeigen

### ISSUE THREAD

**Issue by Highkovic** [ImmunHelden/ImmunHelden.de#134]
Bislang lediglich Blutplasmaspende, es sollen sich aber künftig auch tafeln, Pflegestellen, etc. wiederfinden, die ein eigenes Legendensymbol benötigen und filterbar sein sollen

**Comment by weliveindetail** [comment]
Mit https://github.com/ImmunHelden/ImmunHelden.de/commit/40e8a1876766261243f0a1c0e47515cb9f63d660 ist ein erstes Beispiel online: https://immunhelden.de/maps/all/#stadtmission-U0_m7opAy9

Das Icon kommt aus diesem Bild aus deren Webseite:
![bsm](https://user-images.githubusercontent.com/7307454/84577211-a27f5e80-adba-11ea-9066-b95dc1f93b23.png)

Könnte man im Falle des Seniorenzentrums aber auch missverstanden werden 😬

**Comment by weliveindetail** [comment]
Hier nochmal die Anzeigen als PDF:
[liebevoll Erinnernde in Corona-Zeiten.pdf](https://github.com/ImmunHelden/ImmunHelden.de/files/4780066/liebevoll.Erinnernde.in.Corona-Zeiten.pdf)
[Produktionsassistenz für die Masken-Produktion.pdf](https://github.com/ImmunHelden/ImmunHelden.de/files/4780067/Produktionsassistenz.fur.die.Masken-Produktion.pdf)
[Ehrenamtliche Helfer für die Mund-Nasen-Masken-Produktion.pdf](https://github.com/ImmunHelden/ImmunHelden.de/files/4780064/Ehrenamtliche.Helfer.fur.die.Mund-Nasen-Masken-Produktion.pdf)


Um sie auf die Map zu bringen, brauchen wir die folgenden Angaben (am Beispiel der [einen die ich schon eingebaut habe](https://immunhelden.de/maps/all/#stadtmission-U0_m7opAy9)):

> Titel Karte: Seniorenzentrum Bestensee
> Koordinaten (lat, lng): 52.241663, 13.642343
>
> Titel Details: Liebevoll Erinnernde bei Besuchen in Corona-Zeiten
> Adresse: Hauptstraße 11, 15741 Bestensee
> Email: zentgraff@berliner-stadtmission.de
> Webseite: https://www.berliner-stadtmission.de/sz-bestensee
>
> Text:
> Besuche sind erlaubt und das ist wunderbar! Die Freude über ein Wiedersehen ist riesig. Damit das noch lange so bleibt, benötigen wir Ihre Unterstützung!
>
> **Tätigkeit:** Wir suchen Ehrenamtliche für unser Seniorenzentrum, die Besucher:innen und Bewohner:innen liebevoll an die Abstandsregelungen erinnern und damit helfen, Besucher weiterhin zu ermöglichen.
>
> **Voraussetzungen:** Sie sollten Geduld und ein Herz für ältere Menschen mitbringen. Ein Engagement ist nur möglich, wenn Sie nicht zur Risikogruppe gehören und frei von den üblichen Covid19-Symptomen sind.
>
> **Erwartete Haltung:** Sie sind überzeugt, dass jedem Menschen eine unverlierbare Würde gegeben ist. Dem christlichen Glauben sowie anderen Religionen und Weltanschauungen stehen Sie respektvoll gegenüber.
>
> Ihre Unterstützung können wir nach Absprache flexibel einplanen. Bei Interesse kontaktieren Sie bitte Frau Zentgraff:


Koordinaten und andere fehlende Daten finden sich oft bei Google Maps:
<img width="916" alt="Screenshot 2020-06-15 at 14 14 26" src="https://user-images.githubusercontent.com/7307454/84656405-eab19480-af12-11ea-8eeb-a3fbb572dd56.png">

Danke!

**Comment by weliveindetail** [comment]
@vikiarn Wenn du im Laufe der Woche hier neue Posts wie die oben machst, übernehm ich sie in die Karte. Danke!

**Comment by vikiarn** [comment]
Titel Karte: Haus der Statistik
Koordinaten (lat, lng): 52.5269521,13.3621109,15
Titel Details: Ehrenamtliche Helfer/innen bei der Mund-Nasen-Masken Produktion
Adresse: Otto-Braun-Straße 70-72, 10178 Berlin-Mitte – nahe Karl-Marx-Allee 1
Email: watertowine@berliner-stadtmission.de
Webseite: https://www.berliner-stadtmission.de/ehrenamtliche-helfer-innen-bei-der-mund-nasen-masken-produktion 
Text:
Sie nähen gerne oder haben Freude daran, bei der Vor- und Nachbereitung der Masken-Produktion zu helfen? Dann helfen Sie uns dabei, für obdachlose und bedürftige Menschen, Masken zu produzieren!
Tätigkeit: Wir suchen Ehrenamtliche für die Maskenproduktion bei der „Komm & Sieh“ gGmbH der Berliner Stadtmission. Vor Ort oder zu Hause könne Masken mit Industrie-Nähmaschinen produziert werden. 
Voraussetzungen: Sie sollten ggf. Erfahrung mit Industrie-Nähmaschinen haben. Ansonsten können Sie den Umgang mit den Maschinen auch vor Ort erlernen. Es wäre vorteilhaft, wenn Sie sich kontinuierlich engagieren können. Ein Engagement ist nur möglich, wenn Sie nicht zur Risikogruppe gehören und frei von den üblichen Covid19-Symptomen sind.
Erwartete Haltung: Sie sind überzeugt, dass jedem Menschen eine unverlierbare Würde gegeben ist. Dem christlichen Glauben sowie anderen Religionen und Weltanschauungen stehen Sie respektvoll gegenüber.
Ihre Unterstützung können wir nach Absprache flexibel einplanen. Bei Interesse kontaktieren Sie bitte Frau Schwarz:
Kontaktperson: Antonia Schwarz
Telefon: 0151 6483 5037

**Comment by vikiarn** [comment]
Titel Karte: Haus der Statistik
Koordinaten (lat, lng): 52.5269521,13.3621109,15
Titel Details: Produktionsassistenz für die „Berliner Schnauze“ gesucht
Adresse: Otto-Braun-Straße 70-72, 10178 Berlin-Mitte – nahe Karl-Marx-Allee 1
Email: lichtwer@berliner-stadtmission.de
Webseite: https://www.berliner-stadtmission.de/produktionsassistenz-fuer-die-berliner-schnauze-gesucht 
Text:
Das Projekt „Berliner Schnauze“ ist zuständig für die Mundmaskenproduktion, welche kostenlos an bedürftige Menschen und den entsprechenden Einrichtungen wir unserer Kleiderkammer, Notübernachtungen und Mitarbeitenden in nothelfenden Bereichen und Altenheimen weitergeben werden. Die Masken werden aus Berliner Stoffen hergestellt.
Tätigkeit: Folgende Aufgaben erwarten dich: Unterstützung und Koordination des Arbeitsplans, Kontakt mit Helfer*innen, Kontaktaufnahme mit potentiellen Helfer*innen, Unterstützung bei allen anfallenden Aufgaben, Mitbetreuung der Maschinen vor Ort und Hilfestellung bei Maschinenstillstand, Ausgabe von Material, Unterstützung bei der Auswahl von Material, Unterstützung in der Qualitätskontrolle
Voraussetzungen: Das Ehrenamt setzt keine Nähkenntnisse voraus, denn es gibt viele Arbeiten rund um die Entstehung der Mundmasken. Falls Sie nähen wollen, sollten Sie ggf. Erfahrung mit Industrie-Nähmaschinen haben. Ein Engagement ist nur möglich, wenn Sie nicht zur Risikogruppe gehören und frei von den üblichen Covid19-Symptomen sind.
Erwartete Haltung: Sie sind überzeugt, dass jedem Menschen eine unverlierbare Würde gegeben ist. Dem christlichen Glauben sowie anderen Religionen und Weltanschauungen stehen Sie respektvoll gegenüber.
Ihre Unterstützung können wir nach Absprache flexibel einplanen. Bei Interesse kontaktieren Sie bitte Frau Lichtwer:

**Comment by vikiarn** [comment]
@weliveindetail Ist es so wie oben richtig?

**Comment by Highkovic** [comment]
Hi zusammen, ich würde die Beschreibung der Map auch ändern:
_________________

aktuell:

**Blutplasmaspende**
Während deines Kampfes gegen COVID-19 hat dein Immunsystem Antikörper gegen das Virus gebildet. Sie haben dir geholfen, das Virus zu besiegen und finden sich nun in deinem Blutplasma.

Wenn du alle gesundheitlichen Kriterien erfüllst, kannst du mit deiner Spende schwer Erkrankten im Kampf gegen COVID-19 helfen. Oder einen Beitrag zur Forschung über Antikörper leisten.

Eine passende Spendeeinrichtung in Deiner Nähe findest du auf unserer ImmunHelden Map.

_______________________________
Neu:
**Anlaufstellen**
Während deines Kampfes gegen COVID-19 hat dein Immunsystem Antikörper gegen das Virus gebildet. Sie haben dir geholfen, das Virus zu besiegen und finden sich nun in deinem Blutplasma.

Damit reduzieren sie das Risiko einer Re-Infektion und Du kannst damit Gutes tun. So kannst Du z.B. Blutplasma spenden. Geeignete Anlaufstellen dafür und für weitere Heldentaten findest Du auf unserer ImmunHeldenMap.

**Comment by weliveindetail** [comment]
Hier gibt es jetzt endlich mal die beiden neuen Anzeigen, sorry dass das so lange gedauert hat:
https://immunhelden.de/maps/all/#stadtmission-SFsdfiD8y8

@vikiarn 
In den PDFs hab ich die Frau Lichtwer nicht gefunden. Steht da nicht textilhafen@berliner-stadtmission.de? Und: ob watertowine@berliner-stadtmission.de die Adresse ist von Frau Schwarz? Aktuell macht es jetzt so den Anschein. Hab auch die Aufzählung wieder als Liste mit Anstrichen formatiert.

Interessant ist, dass wir hier zwei Anzeigen am gleichen Ort haben. Ich hab sie in den Details einfach untereinander gepackt. Allerdings haben sie nun auch denselben Permalink. Weiß noch nicht, wie man das am besten organisiert..

Was denkt ihr?

**Comment by ImmunHeldin-CE** [comment]
Stuttgarter Tafel:
[Tätigkeitsbeschreibung EA.pdf](https://github.com/ImmunHelden/ImmunHelden.de/files/4805579/Tatigkeitsbeschreibung.EA.pdf)

Wäre cool, das schnell auf die Karte zu bekommen, dann hätten wir ein gutes Argument für die anderen Tafeln.

**Comment by ImmunHeldin-CE** [comment]
> Interessant ist, dass wir hier zwei Anzeigen am gleichen Ort haben. Ich hab sie in den Details einfach untereinander gepackt. Allerdings haben sie nun auch denselben Permalink. Weiß noch nicht, wie man das am besten organisiert..
> 
> Was denkt ihr?

Top! Das Tätigkeitsfeld ist ja auch das gleiche :)

**Comment by weliveindetail** [comment]
> Stuttgarter Tafel:
> [Tätigkeitsbeschreibung EA.pdf](https://github.com/ImmunHelden/ImmunHelden.de/files/4805579/Tatigkeitsbeschreibung.EA.pdf)
> 
> Wäre cool, das schnell auf die Karte zu bekommen, dann hätten wir ein gutes Argument für die anderen Tafeln.

Haben wir eine/mehrere Adresse(n) dafür? Sonst nehm ich die hier (ist aber evtl. "nur" die Zentrale): Hauptstätter Str. 75, 70178 Stuttgart

**Comment by ImmunHeldin-CE** [comment]
> Haben wir eine/mehrere Adresse(n) dafür? Sonst nehm ich die hier (ist aber evtl. "nur" die Zentrale): Hauptstätter Str. 75, 70178 Stuttgart

So wie ich das am Tel verstanden hatte, ist das die richtige Adresse und der Tafelladen gehört zur Zentrale. Schade ist halt wieder, dass man sich per Mail melden soll und gar nicht über uns, aber da können wir ggf. nachfragen, sobald wir einen Chat haben :)

**Comment by weliveindetail** [comment]
Voila: https://immunhelden.de/maps/all/#tafel-Usi8y3JjBB
Telefon kommt von der Webseite: https://www.tafel-stuttgart.de/zeit-spenden/

**Comment by ImmunHeldin-CE** [comment]
Vielen Dank! :) Vielleicht könnten wir noch hinzufügen, dass man sich per Mail bei der Tafel melden soll? Das stand im Text und die Frau von der Tafel hat auch am Tel stark betont, dass die Leute die Tafel per Mail kontaktieren sollen.

**Comment by weliveindetail** [comment]
Alles klar, ist drin. Hab auch gleich noch die beiden fehlenden Seniorenheime der Stadtmission gemacht:
https://immunhelden.de/maps/all/#stadtmission-y8scAiQvwn
https://immunhelden.de/maps/all/#stadtmission-iudDZ87_23

**Comment by weliveindetail** [comment]
Und die drei Wohnstätten der Behindertenhilfe der Stadtmission:
https://immunhelden.de/maps/all/#stadtmission-pMMik9_jn7
https://immunhelden.de/maps/all/#stadtmission-98uffnUG_N
https://immunhelden.de/maps/all/#stadtmission-8yhBYJB0kc

Damit sollte alles online sein, was wir bis jetzt bekommen haben.

**Comment by weliveindetail** [comment]
Mit https://github.com/ImmunHelden/ImmunHelden.de/commit/7e1c18f86ae01615eabaee0623803a287fc76515 ist auch die Verlinkung auf der Landing Page aktualisiert. Hab deinen Text noch ein wenig abgeändert @Highkovic

Wenn ich etwas übersehen oder falsch eingetragen hab, dann schreibt mir gern und/oder macht das Ticket wieder auf. Bis wir die Eintragungen auf der Map im Login-Bereich machen können, machen wir am besten separate Tickets für die nächsten Anfragen. Danke!
