### ISSUE TITLE
Einleitungstext für "Team" auf Webpage schreiben

### ISSUE THREAD

**Issue by Highkovic** [ImmunHelden/ImmunHelden.de#135]
Vom Hackathon über de Enabler hin zu: wer wir aktuell sind

**Comment by Highkovic** [comment]
Hier der Draft - danke an Viki für die tolle Vorlage!
https://docs.google.com/document/d/1jlKWRkDGDGiOHLLAkHvyhFc5M_MODosvQwwuNjRazGQ/edit?usp=drivesdk

**Comment by weliveindetail** [comment]
Eingebaut mit https://github.com/ImmunHelden/ImmunHelden.de/commit/bad9de547b9235d97ae0ae243a1bf92595f770a7#diff-93889109348cf84786fdadabe3d88afa und deployt: https://immunhelden.de/about/

**Comment by Highkovic** [comment]
Top, danke!--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 13.06.20, 13:56 schrieb "Stefan Gränitz" <notifications@github.com>:

   
  Eingebaut mit bad9de5#diff-93889109348cf84786fdadabe3d88afa und deployt: https://immunhelden.de/about/
