### ISSUE TITLE
In Slack für neue Teammitglieder werben

### ISSUE THREAD

**Issue by ImmunHeldin-CE** [ImmunHelden/ImmunHelden.de#136]
Wir brauchen Unterstützung im Marketing und im Business Development.

**Comment by ImmunHeldin-CE** [comment]
Simon, unsere Marketing-Hoffnung, ist inzwischen leider schon anders eingebunden. Nächste Woche hat er mehr Übersicht bzgl. Kapa und meldet sich nochmal.

**Comment by weliveindetail** [comment]
Ist das ein kontinuierlicher Task den wir in Slack besser abbilden könnten?

**Comment by weliveindetail** [comment]
In diesen Bereichen könnten wir Unterstützung gebrauchen:
Account Manager / Business Development
Marketing / PR
Social Media
Development (mind. Markdown und Github bedienen)

IMHO könnten wir werben mit unserem außerordentlich guten Teamspirit, vielfältigen Aufgaben und der Stundenkompensation via Timesheet. Was denkt ihr?

**Comment by DominikGolle** [comment]
Stefan postet in Slack, Frage 8 wird eine "Stellenausschreibung" über Insta, Twitter & Facebook

**Comment by weliveindetail** [comment]
Slack ist done. Für die Stellenausschreibung brauchen wir noch Text.
