### ISSUE TITLE
Map Header Redesign mit Filter

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#137]
Nach ersten Experimenten stellt sich heraus, dass die Integration von Filtern in den Mobile View der Map im aktuellen Ansatz schwierig ist. Wie können wir das möglichst generisch lösen?

**Comment by weliveindetail** [comment]
Der Mobile View macht es kompliziert. Aktuell sieht das so aus:
<img width="368" alt="Screenshot 2020-06-15 at 19 30 31" src="https://user-images.githubusercontent.com/7307454/84688098-0a5eb200-af3f-11ea-8703-94767eff45f4.png">

Perspektivisch sieht man vor lauter Kategorien die Karte nicht mehr.

**Comment by weliveindetail** [comment]
Die robusteste Lösung wäre hier wohl dieselbe wie für Details & Subscribe:

<img width="368" alt="Screen Recording" src="https://user-images.githubusercontent.com/7307454/84688705-126b2180-af40-11ea-9e51-edf3bbd2ad4f.gif">

Dann bräuchten wir noch ein Symbol im Header. Ein erster Draft:

<img width="368" alt="MapHeaderRedesign" src="https://user-images.githubusercontent.com/7307454/84688768-3169b380-af40-11ea-9220-81edc090a2aa.png">

**Comment by vikiarn** [comment]
Vorschläge: 
https://icons8.de/icon/60730/erinnerung-hinzuf%C3%BCgen 
https://icons8.de/icon/81262/verfolgen
https://icons8.de/icon/111488/anmelden

**Comment by weliveindetail** [comment]
Nice danke für die Links. Gleich das erste sieht super aus. Statt eines Filters könnte ich vielleicht auch ein Listensymbol verwenden, z.B. sowas wie https://icons8.de/icon/111399/list ?

Die müssen dann nur möglichst noch zusammen passen 🙂

**Comment by vikiarn** [comment]
Ich persönlich finde immer noch einen schreibenden Stift am Eindeutigsten - aber das ist auch nur meine persönliche Perspektive. Die Liste ist denke ich auch gut - lass die gerne nehmen :) - das könnten uns dann ja auch die Tester*innen rückmelden!

**Comment by weliveindetail** [comment]
> Ich persönlich finde immer noch einen schreibenden Stift am Eindeutigsten

In meinem Kopf steht der Stift immer für Editieren oder Unterschreiben :)

> das könnten uns dann ja auch die Tester*innen rückmelden

Stimmt, das hab ich hoffentlich online bis dahin....

**Comment by weliveindetail** [comment]
Implementiert mit https://github.com/ImmunHelden/ImmunHelden.de/commit/5702995b5403d7711f06fb15bf3c6ddd060aa32c Die Icons bringen einen eigenen Stil mit, weiß nicht ob das in der jetzigen Form schon perfekt ist, aber good for now denke ich.

Gerne testen auf Desktop und Mobile, verschiedenen Browsern, auf Windows und richtigen Betriebssystemen 😄
