### ISSUE TITLE
Google (Tech)

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#145]
Angefragt hatten wir: Software Engineering, UX / UI Design, Kommunikation & PR

Ansprechpartner ist Marlene Meissner, siehe Team Emails zum Ressourcen Match.

**Comment by weliveindetail** [comment]
> Hallo Stefan, 
es klingt wahrscheinlich ein bisschen unglaublich, aber ich kann leider beim besten Willen bei uns intern keinen Ansprechpartner für FireChat finden. Tut mir Leid! 
Was wäre denn der zweitwichtigste Bereich, in dem wir euch aktuell unterstützen könnten? :) 
Liebe Grüße, 
Marlene

Meine Antwort: Ich spreche im Laufe der Woche mit dem Team ab, wie wir weiter vorgehen können und melde mich dann wieder.

**Comment by ImmunHeldin-CE** [comment]
Das ist ja schade :( 
Beim Marketing wäre Hilfe von Google bestimmt auch total nützlich! Vielleicht hat die Init am Freitag ja Ideen, an welchen Stellen Unterstützung sinnvollen wäre (wir würden ihnen natürlich sagen, dass das bisher nur ein Gedankenspiel ist)

**Comment by weliveindetail** [comment]
Firebase Beratung Freitag ab 11:00 Uhr in Meeting mit cloudwuerdig.de

Google Form für Cloud Credits: https://forms.gle/L7B3aXLG2pVjVs498

Google Ads Grants müssen wir gemeinnützig sein: [Google Ad Grants für #WirVsVirus (1).pdf](https://github.com/ImmunHelden/ImmunHelden.de/files/4801092/Google.Ad.Grants.fur.WirVsVirus.1.pdf)

**Comment by ImmunHeldin-CE** [comment]
> Google Ads Grants müssen wir gemeinnützig sein

Was ist denn eine "Gesellschaft mit Steuervorteilen"? Fallen wir da als GbR ohne Gewinnerzielungsabsicht vielleicht drunter? Könnten wir ja mal nachfragen.

**Comment by weliveindetail** [comment]
Verein oder gUG gründen steht IMHO aber sowieso an

**Comment by weliveindetail** [comment]
In dem Ticket würde ich gern erstmal die technischen Aspekte tracken, für Cloud Credits und Ad Grants können wir separate Tickets öffnen wenn es soweit ok.

**Comment by weliveindetail** [comment]
> Firebase Beratung Freitag ab 11:00 Uhr in Meeting mit cloudwuerdig.de

Das war hands-on und sehr hilfreich. Nächste Woche wieder für Feedback, gleiche Zeit, gleicher Ort!

Firechat ist tatsächlich schon zu lange nicht aktiv weiterentwickelt worden und hat viele offene Issues. Es nutzt wohl auch noch die alte Realtime-Database und nicht den Cloud Firestore. Zudem bietet Firebase von Haus aus schon die meisten Backendfunktionen um selbst einen Chat aufzusetzen. Für das Frontend könnte man ggf. eine Library wie diese verwenden:
https://github.com/Detaysoft/react-chat-elements

Chat mit anonymer Authentifizierung sollte kein Problem sein. Einen "Account" hat die ImmunHeld:in dann in Form eines konversationsspezifischen Cookies. Wenn sie den mal verliert, können wir eine Restore-Funktion anbieten, die eine Email mit einem Link schickt, der einmalig alle Cookies wieder herstellt.

**Comment by weliveindetail** [comment]
On hold, bis wir wieder Kapazitäten haben
