### ISSUE TITLE
Registrierung von Partnerorgas: Feld für Jobbeschreibung/Kontakt

### ISSUE THREAD

**Issue by ImmunHeldin-CE** [ImmunHelden/ImmunHelden.de#148]
Es würde professioneller wirken und uns Arbeit ersparen, wenn interessierte Organisationen direkt einen Eintrag zu ihrer benötigten Hilfe erstellen könnten.

**Comment by weliveindetail** [comment]
Ja das wäre prima und wir sollten einen Preview anbieten. Die Felder wo einfach nur Kontaktinformationen etc. erscheinen, sind recht straightforward. Aber wie wird die Eingabe für die Beschreibung hier rechts machen, weiß ich noch nicht genau:

<img width="669" alt="Screenshot 2020-06-19 at 12 02 35" src="https://user-images.githubusercontent.com/7307454/85121359-ed6afd00-b224-11ea-9b41-fd279a9d99ab.png">

Ganz ohne Formatierung ist es jedenfalls nutzlos. Mindestens müssten sie Absätze und Fett/Kursiv/Unterstrichen angeben können. Markdown ist genau die richtige Lösung dafür. Leider befürchte ich, dass das schon zu kompliziert ist......

**Comment by weliveindetail** [comment]
Wir könnten es mit https://prosemirror.net/ versuchen:

<img width="450" alt="Screenshot 2020-06-19 at 12 09 13" src="https://user-images.githubusercontent.com/7307454/85121800-c2cd7400-b225-11ea-8a7f-8fc6b622d4b3.png">

**Comment by ImmunHeldin-CE** [comment]
Prosemirror sieht doch gut aus! Ansonsten können wir, wenn wir damit Schwierigkeiten haben, bestimmt das Match4Healthcare Team fragen, die haben da schon eine Lösung gefunden: https://match4healthcare.de/mapview/

**Comment by weliveindetail** [comment]
Wo genau bei match4healthcare? Wie sieht das bei ihnen aus?

**Comment by ImmunHeldin-CE** [comment]
Schau mal auf die Karte (Link oben), da kann man auf die Einrichtungen klicken (blaue Punkte) und dann nochmal auf "Detailansicht" und dann erscheint da eine Beschreibung - bzw. für die Detailansicht muss man registriert sein, das hatte ich vor längerer Zeit aus Interesse gemacht.

**Comment by ImmunHeldin-CE** [comment]
![image](https://user-images.githubusercontent.com/62710987/85123842-3ae96900-b229-11ea-873a-dec2171bd7cf.png)

**Comment by weliveindetail** [comment]
Ja genau, so etwas meinte ich mit "nutzlos" -- also nicht total nutzlos, aber hier muss man sich schon echt anstrengen beim Lesen, weil es eben keine Formatierung hat 🙂

**Comment by weliveindetail** [comment]
Ich versuch mal David zu erreichen, damit wir zumindest eine Plain-text Version wie diese Hinbekommen und dann können wir im zweiten Schritt einen Editor wie ProseMirror einbauen.

**Comment by ImmunHeldin-CE** [comment]
Naja, finde ich jetzt nicht so wahnsinnig wichtig... Sie haben immerhin ein Formular, wo sich die Orgas direkt eintragen die Freiwilligen sich direkt bei ihnen melden können, also z.B. schonmal die Basisfunktionen. Schöner ist natürlich auf jeden Fall besser aber zur Zeit haben wir das Problem, dass jede interessierte Orga uns eine Mail mit einer Tätigkeitsbeschreibung schicken muss. Hatte gerade die Stuttgarter Tafel am Tel, wo die Verantwortlichen nicht so recht verstehen konnten, dass sie uns mailen müssen.

**Comment by weliveindetail** [comment]
Naja, bisher hat sich noch niemand überhaupt einen Account erstellt. Daher war die Prio für die Details noch nicht so mega. Aber ja, sorry, das müssen wir wohl komplett fertig machen, bevor sich jemand überhaupt darauf einlässt..

**Comment by c0un7-z3r0** [comment]
Ich würde eher ein simpleren Editor als ProseMirror empfehlen :D ... Die meisten features werden eh net gebraucht ... https://draftjs.org/

**Comment by weliveindetail** [comment]
> Ich würde eher ein simpleren Editor als ProseMirror empfehlen :D ... Die meisten features werden eh net gebraucht ... https://draftjs.org/

Stimmt sicher, ich kenne ProseMirror nur zufällig weil ich den Autor kenne 😄 Ja gerne einfacher, solange die Buttons für die Formatierung nicht auf Englisch sind 😉 🤣

Erster Schritt wäre wohl ohnehin erstmal den User für `Add` und `Edit` auf eine separaten Seite zu leiten. Dort könnten wir dann nach und nach neue Features unterbringen oder?
