### ISSUE TITLE
Gemeinnützige Organisation gründen

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#153]
UG? gUG? e.V.?

**Comment by Highkovic** [comment]
**Empfehlung: gUG** - gemeinnützige Unternehmergesellschaft (kleine GmbH)
Weil: im Vergleich zur Stiftung oder zum Verein haftungsbeschränkt. Und genau darum geht es uns ja in erster Linie.
Vorteile:
haftungsbeschränkt begrenzt auf gUG-Vermögen, Gesellschafter nur in Höhe ihrer Einlage)
schlanke Entscheidungsprozesse
Steuervorteile (keine Körperschafts- und Gewerbesteuer)
ab 1€ Stammkapital
kann Spenden erhalten


"Gemeinnützigkeit" wird vom Finanzamt vorläufig vergeben, wenn gemeinnütziger Zweck gemäß §52 oder §53 AO vorliegt. Festgestellt wird es erst rückwirkend mit dem Jahresabschluss.
Auf uns triftt m.E. das zu:
§52 (2), Pt. 25: die Förderung des bürgerschaftlichen Engagements zugunsten gemeinnütziger, mildtätiger und kirchlicher Zwecke. (bearbeitet) 

**Kosten der Gründung:**
450€ Notar- und Amtsgebühren bei Gründung mit (Musterprotokoll (lässt allerdings nur 3 Gesellschafter zu)
(bearbeitet)

**Gründungsschritte:**
Finde heraus welche Unterlagen du für die Gründung brauchst und sorge dafür, dass du alles rechtzeitig zusammen hast. (fantastischer Tip, ey, :augen_verdrehen:)
Fülle das Musterprotokoll aus und lass es dir von einem Notarbüro beglaubigen.
Eröffne dein Geschäftskonto.
Zahl das nötige Stammkapital ein.
Lass deine UG ins Handelsregister eintragen.
Melde die UG beim Gewerbe- und beim Finanzamt an.

**weitere Bedingungen der gUG**
keine Gewinnausschüttung möglich (jo, wollen wir ja eh net)
eine begünstigte gemeinnützige Orga muss in der Satzung festgelegt werden, diese erhält im Fall einer Auflösung der gemeinnützigen UG erwirtschaftete Überschüsse.

**Comment by weliveindetail** [comment]
Wo stehen wir hier?

**Comment by Highkovic** [comment]
Vorschläge für begünstigte gemeinnützige Orga:
- Ärzte ohne Grenzen https://www.aerzte-ohne-grenzen.de/

**Comment by Highkovic** [comment]
zentrale Frage:
wollen wir überhaupt eine gUG gründen?
was ist das Ziel? → **Haftung ausschalten**, Projekt parken?

- Vorteile gUG: Haftung
- Nachteile: sehr aufwändig

im Verein: Haftung sehr ähnlich
- Kosten Verein: ca. 100€
- Steuererklärung müssen wir machen
- Aufzeichnungspflichten
- Entscheidungsprozesse mühsam? --> Mehrheitsbeschluss der Mitglieder

Vergleich gUG (gGmbH) vs. Verein: https://www.gruenderkueche.de/fachartikel/checkliste-gemeinnuetzige-gmbh-ggmbh-und-verein-im-vergleich/

Haftung im Verein: https://www.gruenderkueche.de/fachartikel/checkliste-gemeinnuetzige-gmbh-ggmbh-und-verein-im-vergleich/

Wenn wir einen Verein gründen, dann verwalten wir ihn bitte digital, z.B. druch: https://easyverein.com/vereinssoftware/funktionen/

**Comment by Highkovic** [comment]
Entscheidung steht an: Verbleib als GbR (und GbR kommt als inhaltlich verantwortliche Einheit ins Impressum der Webpage) oder wir gründen einen Verein, der dann inhaltlich verantwortlich ist und auch das operative Business für die ImmunHelden führt. D.h. wir können Überschüsse aus unserer Tätigkeit an den Verein spenden.

Eine GbR wiederum kann nicht so einfach Spenden erhalten.
