### ISSUE TITLE
Double Opt-In scheint nicht zu funktionieren

### ISSUE THREAD

**Issue by DominikGolle** [ImmunHelden/ImmunHelden.de#159]
Laut Rapid User Test

**Comment by weliveindetail** [comment]
Hmm. Die überwiegende Mehrheit der `@muellmail.com` & co User hat das Double Opt-In gemacht. Hab an zwei Stichproben die Email herausgesucht, wo es gefehlt hat und einen Klick auf den enthaltenen Link simuliert. Dort ist der Eintrag dann korrekt in der Datenbank aufgetaucht.

**Comment by weliveindetail** [comment]
@DominikGolle Bevor ich alle Videos durchschaue: In welchem Bericht wurde es gemeldet? Was genau war die Beschreibung? Hab in der Nachbefragung nichts gefundnen außer "anmeldeprozess hinkt etwas"

**Comment by DominikGolle** [comment]
Ich hab das gestern nur protokolliert - @ImmunHeldin-CE: Kannst Du genauer sagen, wo dieses user feedback zu finden ist? 
Danke!

**Comment by ImmunHeldin-CE** [comment]
Ich hab das leider auch nur aufgeschnappt, als ich mir eines der Videos ganz "diagonal" angeguckt habe, um zu sehen, wie die aufgebaut sind. Wenn ich es am Freitag wiederfinde, sag ich Bescheid, zur Not könnten wir das auch selbst nochmal testen.

**Comment by weliveindetail** [comment]
Neuigkeiten?

**Comment by ImmunHeldin-CE** [comment]
Funktioniert wahrscheinlich doch, ich glaube, ich hatte die Kritik im Video des folgenden, des etwas verwirrten Testusers XXXPlanetXXX aufgeschnappt (Text unter Frage 1 im Feedback zur Desktop-Version:  https://rapidusertests.com/customer/dashboard/question)
"Etwas verwirrend die zwei Registrierungsmöglichkeiten und das man auf der Seite vergeblich nach einer Navi sucht. Diese ist auch bei einer One Page Site immer sehr gut bezüglich der Übersichtlichkeit.
WAs nicht gefallen hat war, nach der Registrierung auf der Seite ist der Versuch über das Logo auf die ursprungsseite zu kommen gescheitert und hat dann ein sehr fragmentarisches Bild präsentiert."

Also das Double Opt-In ist nicht das Problem, sondern eher das, was nach der Registrierung passiert und vor allem, dass unsere Testuser:innen die Registrierung für Orgas und die für ImmunHelden nicht unterscheiden können (siehe vor allem Texte und Videos zur Registrierung als Orga).

**Comment by weliveindetail** [comment]
Ob die User es checken oder nicht, ist eine andere Frage. Das Double Opt-In sollte funktional sein. Falls sich das Gegenteil herausstellt, bitte in einem neuen Ticket erklären wie es zu reproduzieren ist. Danke!
