### ISSUE TITLE
thanks-prototypefund.jpg scheint defekt zu sein

### ISSUE THREAD

**Issue by wirths** [ImmunHelden/ImmunHelden.de#160]
Das genannte Image ist im Repo vorhanden, aber scheinbar defekt und wird auf der Website (Startseite) somit auch nicht angezeigt.

**Comment by weliveindetail** [comment]
Hi @wirths danke für den Hinweis! Es geht um dieses Bild: https://immunhelden.de/images/thanks-prototypefund.jpg

**Comment by weliveindetail** [comment]
Bei mir wird es auf macOS und Android jeweils in Firefox und Chrome korrekt angezeigt, aber auf den zweiten Blick muss ich feststellen, dass die Vorschau der Datei im Finder nicht funktioniert 🤔 Schau ich mir gleich an.

@wirths Darf ich in der Zwischenzeit nach deinem Betriebssystem/Browser fragen? Kannst du das Problem immer oder nur in einer bestimmten Kombination reproduzieren?

**Comment by weliveindetail** [comment]
Korrigierte Datei hier: https://immunhelden.de/images/thanks-prototypefund.png

Sollte nun auch auf der Startseite korrekt dargestellt werden.

**Comment by wirths** [comment]
Funktioniert nun auch bei mir :-)
