### ISSUE TITLE
Andere Initiativen analysieren

### ISSUE THREAD

**Issue by DominikGolle** [ImmunHelden/ImmunHelden.de#17]
- https://helpunity.eu/ (Heike)
- https://service.careship.de/nachbarschaftshilfe/ (Heike)
- https://www.wirgegencorona.com/ (Heike)
- https://www.saisonarbeit-in-deutschland.de/ (Heike)
- Digital Immunity Evidence (Dominik)
- https://hilf-helfern.de/ (Dominik)

**Comment by weliveindetail** [comment]
**Ähnlich Initiativen die wir im Team Meeting #2 gelistet hatten
Danke @Highkovic für die kurzen Beschreibungen**

https://helpunity.eu/
Hilfegesuche und -angebote auf lokaler Ebene, Geomatching wie wir bzgl. PLZ, ebenfalls interaktive Karte
Unspezifisch: 1 Formular für Angebote und Gesuche
Keine E-Mail-Bestätigung bei Registrierung
Fokus nicht klar: kollaborativer Kalender verfügbar, in den jeder Online-Events eintragen kann
Wie könnten wir zusammenarbeiten? M.E. keine für beide Seiten gewinnbringende Partnerschaft. Eher: sie sollten sich aufsplitten in nebenan.de und sich foksussieren auf die Bündelung von Online-Events

https://service.careship.de/nachbarschaftshilfe/
Hilfegesuche und -angebote auf lokaler Ebene, Geomatching wie wir (vermutlich) und bzgl. spezifischer Verrichtungen
Fokus: Kontaktlose ehrenamtliche Nachbarschaftshilfe, Immunität NICHT erforderlich
Keine E-Mail-Bestätigung bei Registrierung
Wie könnten wir zusammenarbeiten? Synergiepotentiale: wir erweitern ihr Portfolio, doch wenn, dann bietet die nächste Plattform mehr Potential:

https://www.saisonarbeit-in-deutschland.de/
Hilfegesuche und -angebote mit Fokus Saisonarbeit
Funktioniert über Präsentation der Betriebe wie auf einer Stellenbörse. D.h. der Betrieb gibt seine Eckdaten ein und präsentiert sich über ein profil, der designierte saisonarbeiter kann Profile filtern, nach PLZ des Betriebes, Produktionsausrichtungen und Pflanzkultur
Wie könnten wir zusammenarbeiten? Sehe keine Potentiale, da Immunität in den gefragten Bereichen m.E. kein Kriterium ist

(https://www.die-heldenboerse.de/einkaufshelden/)
Hilfegesuche und -angebote für Einkäufe und Behelfsmasken
Keine Info ersichtlich, wie gematcht wird
Offline-Hilfe durch Ausdrucke möglich
Positiv: ein Account für die Selbstverwaltung wird geschaffen
Wirres Konzept der Jungen Union:
Masken und Einkäufe. Und Einkäufe von Masken:
Ich möchte für andere Einkaufen
Ich möchte Masken anbieten
Wie könnten wir zusammenarbeiten? wir erweitern ihr Portfolio. Ich persönlich finde die politische Nähe schwierig

https://seniorenheim-digital.herokuapp.com
Für das Projekt werden Leute benötigt, die den Senioren bei der Installation der Geräte helfen. Außerdem könnten ImmunHelden Senioren sogar besuchen, sodass ggf. ein komplementäres Angebot entstehen würde.

https://match4healthcare.de/
gut laufendes Projekt mit vielen Hilfesuchenden und Helfer:innen, die auch an unserem Angebot interessiert sein könnten (notfalls gehen wir auf Partnerklau) 

http://klinikhero.de/
Vermitteln Kliniken Helfer:innen → es wäre besser, wenn diese Helfer:innen immun wären. Das Projekt hat viele Kliniken als Partner, die für uns interessant sein könnten.

Postleitzahl-basiertes Matching auch in:
https://www.quarantaenehelden.org
https://aid.sumofus.org/de
https://nebenan.de/corona
https://wirhelfen.eu/

**Comment by weliveindetail** [comment]
"einzige interessante Option, Kontaktaufnahem steht noch aus, mache ich bis spätestens Donnerstag"

https://www.wirgegencorona.com/
Kurzum: wie Careship, nur bekannter, mehr Reichweite durch Industriepartner, 4.300 Follower auf Instagram, erster Beitrag: 18.März (wir folgen ihnen nun auch :-))
Hilfegesuche und -angebote auf lokaler Ebene, Geomatching wie wir (vermutlich) und bzgl. spezifischer Verrichtungen
Keine FAQS
Fokus: Kontaktlose ehrenamtliche Nachbarschaftshilfe, Immunität NICHT erforderlich
Offline-Hilfe durch Ausdruck möglich
E-Mail-Bestätigung bei Registrierung
Wie könnten wir zusammenarbeiten? Synergiepotentiale: wir erweitern ihr Portfolio

@Highkovic Können wir hier Details sammeln, falls eine Antwort kommt? Danke

**Comment by weliveindetail** [comment]
Aus dem Slack Channel, gefunden von @c0un7-z3r0 

https://reach4help.org/
Hat schon Mal jemand sich die hier angeschaut? Ist komplett open source auf github auch verfügbar. Die haben auch eine Map ;) https://github.com/reach4help/reach4help

https://thestaysafeapp.com/
Noch ein spannendes evtl auch  ähnliches project StaySave  https://www.youtube.com/watch?v=102NsmOCDgc

**Comment by weliveindetail** [comment]
https://maps.maskefuerdich.de/page/ich-bin-neu-bei-maskefurdich
Noch eine Matching-Plattform, diesmal Masken.

**+** Karte wird beim ersten Aufruf gut erklärt
**+** Angebote werden geclustert (so wie es aussieht via https://github.com/Leaflet/Leaflet.markercluster wie match4healthcare, reach4help und andere)
**+** Login via Plattform-Account, Google oder Facebook
**-** Login erforderlich auch für einfache Kontaktaufnahme

Interessant:
- "Powered by [Mapotic](https://www.mapotic.com)" einem Whitelabel Kartendienst
- Beworben vom Gesundheitsministerium https://twitter.com/BMG_Bund/status/1255825364800155654
