### ISSUE TITLE
Quick-Fixes Landing Page

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#172]
"und gesellschaftlich engagieren" raus, Einstiegshürde runter

**Comment by Highkovic** [comment]
--> anstatt "Frage ImmunHelden" an viell. besser ""Erbitte Untersützung durch ImmunHelden"
--> hat keiner der RapidUser auf den ersten Blick als Registrierungsmöglichkeit für Orgas erkannt, klingt eher nach einer Hilfsfunktion/FAQ-Rubrik

**Comment by Highkovic** [comment]
--> anstatt "Suchst Du oder Deine Organisation Unterstützung? Möchstest Du eine ImmunHeld:in für eine Tätigkeit finden? Dann mach mit und **registriere Dich hier.**"

besser: "Suchst Du oder Deine Organisation Unterstützung? Möchtest Du eine ImmunHeld:in für eine Tätigkeit finden? Hier geht's zur **Anmeldung**."
--> umfasst damit sowohl die Registrierung als auch den Login nach erfolgter Registrierung. Der Weg ist nämlich der Gleiche, was für eine Orga nicht sofort zu erkennen ist, wenn man für den Login auch auf den Link mit dem Namen "registriere Dich hier" klicken muss

siehe Feedback RapidUser: https://rapidusertests.com/customer/dashboard/viewVideo/508352

**Comment by Highkovic** [comment]
anstatt "Du hast die COVID-19-Erkrankung schon hinter dir und möchtest dich nun gesellschaftlich engagieren?
Dann mach mit und werde Immunheld:in! Wir informieren Dich, wenn es in Deiner Region Möglichkeiten gibt zu helfen."

--> Du hast die COVID-19-Erkrankung schon hinter dir?
Dann mach mit und werde Immunheld:in! Wir informieren Dich, wenn es in Deiner Region Einsatzmöglichkeiten für Dich gibt"

**Comment by weliveindetail** [comment]
Und deployt: https://immunhelden.de

**Comment by weliveindetail** [comment]
@Highkovic Danke für die Auflistung. Gibt es noch weitere Änderungswünsche? Dann bitte einfach weiter posten. Wenn wir für den Moment fertig sind bitte schließen. Danke!

**Comment by weliveindetail** [comment]
Social Media Previews beispielsweise. Die lesen sich derzeit so:

> Nutze Deine Immunreaktion zum Wohle aller
> Du hast die COVID-19-Erkrankung schon hinter dir und möchtest dich nun gesellschaftlich engagieren? Dann mach mit und werde Immunheld:in! Wir informieren Dich, wenn es in Deiner Region Möglichkeiten gibt zu helfen.

🤔

**Comment by ImmunHeldin-CE** [comment]
Wenn man vom Login für Organisation auf das Logo klickt, gelangt man scheinbar z.T. zum Twitter Link: [https://rapidusertests.com/video/bDM0UkxaWHYySHNJZWlISzBxaWJoUT09]
Konnte ich so nicht nachstellen, ich gelange da nur auf eine ältere bzw. verzerrte Version der Home-Seite.
![image](https://user-images.githubusercontent.com/62710987/89127929-00ded880-d4f2-11ea-9851-e1608ad613ac.png)

**Comment by ImmunHeldin-CE** [comment]
![BMBF_gefördert vom_deutsch](https://user-images.githubusercontent.com/62710987/89128671-916be780-d4f7-11ea-9216-2435358d982e.jpg)
Das Logo des BMBF muss eingebaut werden:

**Comment by weliveindetail** [comment]
Yes, plus das Logo von Silberpu
[SilberpulsLogo.svg.zip](https://github.com/ImmunHelden/ImmunHelden.de/files/5015646/SilberpulsLogo.svg.zip)

Ich will diese Woche klären, ob wir die Landing Page in Gatsby neu bauen. Sonst mach ich es halt selbst aber dann alles in einem Rutsch zusammen mit dem neuen Design.

**Comment by weliveindetail** [comment]
+ Map auf Landing Page als Bild einbinden, damit Leute die noch mit einem 10+ Jahre alten Browser unterwegs sind 🙄 erkennen, dass dort eigentlich etwas kommen sollte..

**Comment by weliveindetail** [comment]
Eingebaut mit https://github.com/ImmunHelden/ImmunHelden.de/commit/193d9f3f6fa6bcedacb0eaf069798fd527067d79 und https://github.com/ImmunHelden/ImmunHelden.de/commit/e3d83aadfc2f7ed636611d2eb577960714bd9062

**Comment by weliveindetail** [comment]
Bitte neues Ticket falls es neue Quick-fixes notwendig werden.
