### ISSUE TITLE
Registrierungsprozess für Orgas funktioniert nicht

### ISSUE THREAD

**Issue by Highkovic** [ImmunHelden/ImmunHelden.de#175]
Nachdem sich eine Orga regsistriert hat und wieder einloggen möchte, kann kein Angebot ausgeschrieben werden. Es erscheint folgender Hinweis: "Sie sind noch keiner Organisation zugeordnet, bitte kontaktieren Sie..." 

Siehe u.A. Feedback RapidUser-Test:
https://rapidusertests.com/customer/dashboard/viewVideo/509274

**Comment by weliveindetail** [comment]
Derzeit ist die Implementierung wohl noch so, dass wir ihnen eine Partner ID manuell zuweisen müssen, richtig @c0un7-z3r0 ? Was wir hier als Vorgehensweise wollen wäre vielleicht, dass man:
* bei bei Registrierung erst mal eine eigene neue Organisation anlegt (Partner ID zuweisen)
* die Möglichkeit hat einer existierenden Organisation beizutreten (deren Partner ID hinzufügen)

Kann ich mir ansehen, sobald die Map-Tasks durch sind. Würde mich erst mal um den ersten Teil kümmern und den zweiten Teil manuell lassen (via Support Anfrage).

**Comment by c0un7-z3r0** [comment]
Ja genau. Würde das erstmal als Support Ticket lassen. Aber halt mit einer ordentlichen Nachricht. Denn wenn wir erlauben das jeder orgas hinzufügen kann/darf dann wird es anstrengend werden das wieder aufzuräumen und duplikate zu löschen.

Idee war ja ein/zwei Personen von jeder Orga die wir haben wollen als admin zu definieren die dann wiederum über ein Link/Code was auch immer neue Leute zu ihrer Orga hinzufügen können

**Comment by weliveindetail** [comment]
Ideal wäre eigentlich, wenn wir einen **one-time secret Link** generieren könnten, der dazu führt dass nach der Registrierung automatisch eine Partner ID zugewiesen wird. Im Detail sehe ich den Registrierungsprozess so:

* ein neuer Partner meldet sich
* ich leg in Firebase manuell eine neue PartnerID an, also eine Zeichenfolge wie z.B. `isudfg7612`
* ebenfalls manuell hinterleg ich einen one-time key für die PartnerID, also z.B. `oi8u987hdfbff`
* aus den beiden Infos bau ich manuell einen Link a la: https://dev.immunhelden.de/de/partner/signup/?partnerID=isudfg7612&key=oi8u987hdfbff
* den Link schick ich dem Partner für die Registrierung
* im Zuge der Registrierung wird geprüft, ob der angegebene key für die PartnerID (noch) hinterlegt ist
* wenn ja, kriegt der User die PartnerID zugeordnet und der key wird gelöscht
* wenn nicht, machen wir Meldung an Sentry

Sonst muss ich Neukunden immer schreiben, dass sie sie anmelden müssen UND sich dann bei mir melden UND dann erst loslegen können. Ist echt unnötig kompliziert.

**Comment by ImmunHeldin-CE** [comment]
Bisher sieht man nach der Bestätigung der E-Mail-Adresse als Orga nur einen Hinweis, dass eine Anmeldung jetzt möglich ist. Ist es technisch schwierig, hier einen Link zum Login einzubauen, @weliveindetail ? 
![image](https://user-images.githubusercontent.com/62710987/89128025-bf026200-d4f2-11ea-93d5-39bc77ed5ab1.png)

**Comment by ImmunHeldin-CE** [comment]
Bisher hat man als Orga noch keine Möglichkeit, einen Anzeigetext einzugeben. Ist es in der Zwischenzeit technisch ohne viel Aufwand möglich, den Hinweis "Sie sind noch keiner Organisation zugeordnet" zu ändern? Idealerweise in so etwas wie "Unsere Website wird momentan überarbeitet. An dieser Stelle habt ihr bald die Möglichkeit, einen Anzeigetext zu verfassen. Bis dahin übernehmen wir das gern für euch, wenn ihr uns eine Mail an team@immunhelden.de schreibt". 
![image](https://user-images.githubusercontent.com/62710987/89128104-7dbe8200-d4f3-11ea-8c49-32c89b495f94.png)

**Comment by weliveindetail** [comment]
> Ist es technisch schwierig, hier einen Link zum Login einzubauen?

Ja das ist auch builtin Firebase Funktionalität, die leider nicht ohne Weiteres anpassen kann. Ähnlich wie die Email: https://github.com/ImmunHelden/ImmunHelden.de/issues/176#issuecomment-664588748

**Comment by weliveindetail** [comment]
> Bisher hat man als Orga noch keine Möglichkeit, einen Anzeigetext einzugeben. Ist es in der Zwischenzeit technisch ohne viel Aufwand möglich, den Hinweis "Sie sind noch keiner Organisation zugeordnet" zu ändern?

Ja

> Idealerweise in so etwas wie "Unsere Website wird momentan überarbeitet. An dieser Stelle habt ihr bald die Möglichkeit, einen Anzeigetext zu verfassen. Bis dahin übernehmen wir das gern für euch, wenn ihr uns eine Mail an team@immunhelden.de schreibt".

Ich kann es kurz erklären heute Abend. Wir können den Text ändern in sowas wie "Aus Sicherheitsgründen muss dein Account für die Erstellung von Anzeigen noch von unser freigeschaltet werden. Bitte schick dafür eine Email an team@immunhelden.de"

**Comment by weliveindetail** [comment]
Um nach der Registrierung automatisch eine Partner zuzuweisen, kann man hier einhaken (danke David):
https://github.com/ImmunHelden/ImmunHelden.de/blob/master/functions/index.js#L463

**Comment by weliveindetail** [comment]
Wir nehmen den einfachen Ansatz for now.

**Comment by weliveindetail** [comment]
Ok ist implementiert und deployt. Ich musste mich bei meinem Test nach der Registrierung nochmal aus- und wieder einloggen. Aber das erscheint mir gut genug für den Moment.
