### ISSUE TITLE
Ressourcenanfragen

### ISSUE THREAD

**Issue by DominikGolle** [ImmunHelden/ImmunHelden.de#18]

**Comment by ImmunHeldin-CE** [comment]
Call mit dem Accenture-Team nächsten Mittwochabend (29.04), auf eine Uhrzeit müssen wir uns noch kurzfristig einigen.

**Comment by weliveindetail** [comment]
**Ressourcen Match: msg systems AG**

Unterstützung in den Bereichen: User Experience & User Interface Design (UX/UI), (Native) App Entwicklung, Frontend Entwicklung, Backend Entwicklung

Wir bieten an euch mit unseren Mitarbeitern (10-15 Vollzeit Entwicklern) bei der Umsetzung euer Apps zu unterstützen, sowie Logistik und Infrastruktur kostenlos bereitzustellen.

Ich spreche heute mit Björn und meld mich dann bei ihnen.

**Comment by ImmunHeldin-CE** [comment]
Ressourcen Match: initAG 
Unterstützung in den Bereichen Kommunikationsstrategie und Business Development angefragt (Mail über ImmunHelden-Adresse)

**Comment by DominikGolle** [comment]
5minds setzt zwei issues (Backend) um

**Comment by DominikGolle** [comment]
Stefan spricht mit Projektmitglied von Machbarschaft zu Unterstützung im Bereich Social Media Marketing

**Comment by weliveindetail** [comment]
Followup füs msg abgesendet

**Comment by weliveindetail** [comment]
Neuer Ressourcen-Match
Unternehmen: Boston Consulting Group (BCG)
Unternehmensvertreter:in: Tim Scherer

**Comment by weliveindetail** [comment]
Neuer Ressourcen-Match
Unternehmen: incowia GmbH
Unternehmensvertreter:in: Ingo Schrewe

**Comment by weliveindetail** [comment]
**Feedback: msg systems AG**

Im Moment sind alle unsere Entwickler, die mitmachen wollen, in #WirVsVirus Projekten vergraben. Deshalb kann ich dir zur Zeit nicht helfen. Ich könnte dir noch einen erfahrenen Kollegen im  Business Consulting anbieten, das trifft aber eher nicht deinen Bedarf, vermute ich.

Ich bin dabei, firmenintern Werbung für weitere Unterstützung zu machen. Wenn sich da noch was ergibt, melde ich mich.

**Comment by ImmunHeldin-CE** [comment]
Feedback: InitAG
Harald Felling von der InitAG hat sich 1 Stunde Zeit genommen, um herauszufinden was wir brauchen und was unsere nächsten Schritte sind. Er meldet sich voraussichtlich nächste Woche, weil sich wahrscheinlich eine Mitarbeiterin um unser Outreach-Konzept kümmern will :) 
Weiteres nützliches Feedback: Es ging wieder viel um Immunität und darum, dass sie nicht 100% bewiesen ist. Er ist der Meinung, dass wir unseren Namen überdenken sollten, weil er seiner Meinung nach direkt eine gewisse Skepsis auslöst.

**Comment by ImmunHeldin-CE** [comment]
Kontakt Leitung Altenpflegeverband: 

nach eingeholtem Einverständnis leite ich Dir hiermit die Kontaktdaten des Vorsitzenden des Deutschen Berufsverbands für Altenpflege (DBVA), Bodo Keissner-Hesse, sowie die des Geschäftsführers des DBVAs, Dr. Thomas Kunczik, weiter:

Bodo Keißner-Hesse

Bildungsakademie für Gesundheits- und Sozialberufe
des Kreises Mettmann GmbH
Jubiläumsplatz 19
40822 Mettmann

E-Mail  keissner@bildungsakademie-mettmann.de
Tel.       02104/1418-18
Fax      02104/1418-22
www.bildungsakademie-mettmann.de


Dr. Thomas Kunczik
Geschäftsführer

Deutscher Berufsverband für Altenpflege e.V. 
Bundesgeschäftsstelle 

Postfach 1366
51657 Wiehl 

E-Mail: kunczik@dbva.de
Tel.: 02262 / 999 99 14

**Comment by weliveindetail** [comment]
> Harald Felling von der InitAG hat sich 1 Stunde Zeit genommen, um herauszufinden was wir brauchen und was unsere nächsten Schritte sind. Er meldet sich voraussichtlich nächste Woche, weil sich wahrscheinlich eine Mitarbeiterin um unser Outreach-Konzept kümmern will :)

Yey! 🙌 

> Er ist der Meinung, dass wir unseren Namen überdenken sollten, weil er seiner Meinung nach direkt eine gewisse Skepsis auslöst.

Ui, ja derzeit hat er damit vielleicht gar nicht mal unrecht. Aber wäre natürlich hart. Und die Dinge ändern sich ja hin und wieder. In meinen Augen ist das genau unsere Spekulation: Wenn sich der Wind dreht haben wir die perfekte Nische. Wenn nicht müssen wir sehen welche Assets wir "verkaufen" können 😄

**Comment by ImmunHeldin-CE** [comment]
BCG: Unterstützung im Business Development angefragt

**Comment by ImmunHeldin-CE** [comment]
In welchen Bereichen brauchen wir noch Hilfe? Welche Ressourcen könnten für uns nützlich sein?

**Comment by ImmunHeldin-CE** [comment]
BCG: Unterstützung abgelehnt, weil sie nur Projekten helfen wollen, die nach Überwindung der Coronakrise weiterlaufen - Komische Aussage bei einem WirVsVirus-Hackathon, aber da kann man nichts machen.

**Comment by Highkovic** [comment]
Das habe ich mir auch gedacht... Naja, wir laufen danach ja auch noch weiter, denn es kann ja noch andere Pandemien geben. Aber verkämpfen müssen wir uns nicht--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 22.05.20, 18:10 schrieb Christine <notifications@github.com>:

   
  BCG: Unterstützung abgelehnt, weil sie nur Projekten helfen wollen, die nach Überwindung der Coronakrise weiterlaufen - Komische Aussage bei einem WirVsVirus-Hackathon, aber da kann man nichts machen.

**Comment by ImmunHeldin-CE** [comment]
initAG hat sich heute (25.05.) gemeldet, eine Kollegin wird uns jetzt helfen, nächstes Gespräch Ende der Woche! :) 
TenMedia bietet Unterstützung in UX/UI-Design an. Sollen wir das anfragen?

**Comment by vikiarn** [comment]
--> Christine wendet sich an Sonja
--> incowia GmbH: ggf. bezüglich internem Chat anschreiben --> Stefan? - nicht unbedingt notwendig; ansonsten eventuell auch Bundesdruckerei - Google Chat für Firebase ist sehr speziell; ggf. könnte man sich direkt bei Google melden -> nach Google Personen im Chat suchen?

**Comment by vikiarn** [comment]
Die Webseite von Rapidusertest überprüfen lassen - transparent kommunizieren, ab welchem Stadium der Webseite eine Untersuchung "Sinn macht"

**Comment by vikiarn** [comment]
Graphikdesigner für Design der Webseite - morgen 26.5. sollte jemand ein Design vorstellen (Betina?)

**Comment by weliveindetail** [comment]
Ich werd unser Projekt mal im nächsten Remote Community Meeting von https://uplink.tech/ vorstellen. Vielleicht findet sich da jemand für technische Unterstützung.

**Comment by ImmunHeldin-CE** [comment]
Harald Felling von der Init und seine Mitarbeiterin bieten uns ein Gespräch am Do, 15:30 Uhr an. @SonjaJDoering hast du dann Zeit?

**Comment by ImmunHeldin-CE** [comment]
Rapidusertests: erste Anfrage ist raus (26.05.)

**Comment by ImmunHeldin-CE** [comment]
Google bietet neuerdings Unterstützung in ganz unterschiedlichen Bereichen an!! Was genau sollen wir anfragen? Unterstützung beim Marketing? Kommunikation und PR? UX? Grafikdesign? Backend Entwicklung mit Firebase (dazu bräuchte ich eine kurze Beschreibung @weliveindetail @c0un7-z3r0 ?

**Comment by weliveindetail** [comment]
> Google bietet neuerdings Unterstützung in ganz unterschiedlichen Bereichen an!! ...

Nice! Kurz zusammengefasst (nicht notwendigerweise vollständig):

* Umsetzung unsere Webdesigns mit ReactJS und Gatsby auf Firebase
* FireChat für Kommunikation unserer Nutzer aufsetzen (Backend) und das Frontend an unser Design anpassen (Frontend, UI/UX)
* Weitere Features für die Verwaltung von Anzeigen durch unsere Partner implementieren (Frontend & Backend)
* Marketing & Social Media Kampagnen zusammen mit uns planen und umsetzen

**Comment by ImmunHeldin-CE** [comment]
1. Ressourcenanfrage an Google ist raus (29.05.)

**Comment by ImmunHeldin-CE** [comment]
Ergebnis des Calls mit Benedikt von RapidUsertests: Sie unterstützen uns jetzt direkt und dann nochmal im späteren Verlauf, wenn wir z.B. erste Partnerorgas dabei haben! 
Bis Ende nächster Woche geben wir ihnen das "Go", dann lassen sie ein Panel von ca. 5-10 fiktiven UserInnen über unsere Website schauen lassen (fragen uns vorher nochmal nach Feedback zur Eingrenzung der Zielgruppe). Es soll kein quantitativer, sondern ein qualitativer Test werden, daher das kleine Panel. Wir bekommen nicht nur schriftliches Feedback, sondern können uns auch den Userflow ansehen, weil der Bildschirm der Testpersonen aufgezeichnet wird. 
-> Bis nächste Woche sollten FAQs und Willkommensmails aktualisiert sein :)

**Comment by ImmunHeldin-CE** [comment]
Rapidusertests: Ein Befragungskonzept erhalten wir anfang nächster Woche per Mail, dann geht's los :)

**Comment by weliveindetail** [comment]
Super! Wenn ich es richtig verstanden habe, müssen wir heute Abend im Team Meeting einen Termin für die Rücksprache finden.

**Comment by weliveindetail** [comment]
Das Ticket sieht eigentlich nach einer kontinuierlichen Aufgabe aus. Sollen wir das lieber in Slack machen?

**Comment by ImmunHeldin-CE** [comment]
> Super! Wenn ich es richtig verstanden habe, müssen wir heute Abend im Team Meeting einen Termin für die Rücksprache finden.

Bene schickt uns einen ersten Aufschlag per Mail, wir können ihm glaube ich einfach schriftlich antworten - er würde sich bestimmt melden, wenn dann noch etwas geklärt werden müsste. Im Team könnten wir uns ja eigentlich auch in Docs absprechen und schauen, ob wir dann noch in einem Call Rücksprache halten sollten. 

> Das Ticket sieht eigentlich nach einer kontinuierlichen Aufgabe aus. Sollen wir das lieber in Slack machen?

Stimmt, warum nicht! :)

**Comment by weliveindetail** [comment]
Hab für laufende Unterstützungsangebote in eigene Tickets erstellt:
https://github.com/ImmunHelden/ImmunHelden.de/issues/147 (Silberplus)
https://github.com/ImmunHelden/ImmunHelden.de/issues/146 (Init AG)
https://github.com/ImmunHelden/ImmunHelden.de/issues/145 (Google)
https://github.com/ImmunHelden/ImmunHelden.de/issues/144 (RapidUsertests)

Wenn etwas fehlt, bitte noch nachholen.
