### ISSUE TITLE
Research technische Realisierung und Prozess Immunitätsnachweis

### ISSUE THREAD

**Issue by DominikGolle** [ImmunHelden/ImmunHelden.de#19]
Ggf. hilfreiche Projekte:

- https://devpost.com/software/reden-jetzt (https://gitlab.com/reden.jetzt) 
- https://devpost.com/software/018_mentalhealth_communication-carousel_group2 (https://github.com/KreLou/DosenTelefon_Backend)

**Comment by c0un7-z3r0** [comment]
Jitsi Meet could be used for starting a video call. A room name could be generated automatically and as long it is a 1 on 1 conversation it will be peer to peer. A password and room name can be generated at random.

**API Docs**
- https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md

**How to host own Jitsi Docs:**
- https://github.com/jitsi/jitsi-meet/blob/master/doc/README.md#devops-guide

**Comment by c0un7-z3r0** [comment]
**Other Video Ident Software:**
- https://play.google.com/store/apps/details?id=au.com.infotrack.trivoi&hl=en
- https://www.idnow.io/
- https://www.deutschepost.de/en/p/postident/identifizierungsverfahren/verfahren-videochat.html

**Comment by c0un7-z3r0** [comment]
Alternative to jitsi:
- https://peerjs.com/index.html

**Comment by DominikGolle** [comment]
Hinweise des ehem. Projekts Immunitätsnachweis:

- https://ubirch.de/fileadmin/user_upload/2020-04-16_digital_corona_health_certificate.pdf
- https://www.covidcreds.com/

Da es diese Initiativen schon gibt, haben sie ihren Ansatz nicht weiter verfolgt.

**Comment by DominikGolle** [comment]
Ergebnis Telefonat Markus Mummert:

- [https://www.covidcreds.com/](https://www.covidcreds.com/) will eine internationale Lösung, mit der nationale Gesundheitssysteme mit dezentraler Verifizierung (Blockchain) Zertifikate u.a. für Covid19-immunität ausstellen können.

Meine Einschätzung: technisch für unsere Zielgruppe zu kompliziert (man braucht einen Wallet) und Pandemie vermutlich vorbei, bis Gesetzgeber nationale Gesundheitssysteme entsprechend anpassen

- [https://www.digital-health-germany.org/](https://www.digital-health-germany.org/) ist laut Markus eine Initiative aus Köln, die erstmal mit den lokalen Gesundheitsämtern dort zusammenarbeitet.

Meine Einschätzung: Zwar zunächst nicht deutschlandweit interoperabel, aber die Empfehlung aus dem WirVsVirus-Call mit Gesundheitsbehörden letzten Freitag war wohl, bottom-up vorzugehen anstatt den großen, deutschlandweiten Wurf zu wagen. Könnte interessant für uns sein, v.a. wenn wir diese Gegend anvisieren.

- [https://www.doctorbox.de/](https://www.doctorbox.de/) ist eine bestehende App für eine digitale Gesundheitsakte. Markus will auf sie zugehen und erfragen, ob man dort auch das Theam Covid19-Status unterbringen könnte.

Meine Einschätzung: Bestehende Gesundheitsapp, in die man eine "individuelle Identifikationsnummer" eines Covid19 Abstrichs eingeben kann: [https://www.doctorbox.de/covid19.jsp](https://www.doctorbox.de/covid19.jsp). Ggf. könnte man darüber sagen, dass Personen mit einem min. 2-3 Wochen alten, positiven Test eine "ungesicherte Immunität" oder so etwas haben. Mir war allerdings bisher nicht bekannt, dass es eine "individuelle Identifikationsnummer" bei Testergebnissen gibt bzw. ich hatte gehört, dass man vom Gesundheitsamt angerufen wird und eine mündliche Rückmeldung ohne ID etc. erhält.

Insgesamt: Das deutsche Gesundheitssystem ist so fragmentiert, dass es lange dauern wird, bis es eine standardisierte Lösung gibt. Bis dahin würde ich auf eine leichtgewichtige Lösung setzen - also entweder das Dokument der Wahl + Ausweis in die Kamera halten oder mit Doctorbox bzw. ähnlichen Initiativen kooperieren.
Markus meldet sich, wenn eine der von ihm beobachteten Initiativen, also https://www.covidcreds.com/ und https://www.digital-health-germany.org/, einen Stand erreicht, wo sie für uns interessant sein könnten. Wie gesagt könnten wir https://www.digital-health-germany.org/ auch selbst kontaktieren. Markus war etwas verhalten, den Kontakt weiterzugeben, aber über die Webseite kommen wir ja ran.

**Comment by weliveindetail** [comment]
> Bis dahin würde ich auf eine leichtgewichtige Lösung setzen - also entweder das Dokument der Wahl + Ausweis in die Kamera halten oder mit Doctorbox bzw. ähnlichen Initiativen kooperieren.

Technischen Ablauf des Video-Ident hab ich hier mal genauer durchdacht:
https://github.com/ImmunHelden/ImmunHelden.de/issues/44#issuecomment-633189155

Kooperieren können wir darüber hinaus trotzdem gern jederzeit. Zu dem Zweck behalten wir den Research hier natürlich. Gibt es für das Ticket noch etwas zu tun?
