### ISSUE TITLE
Plasmaspende der Bayrischen DRK eintragen

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#191]
Webseite: https://www.blutspendedienst.com/blog/covid-19-rekonvaleszenten-plasmaspende

Im alten Datensatz hatten wir sie wohl schon mal.

**Comment by Highkovic** [comment]
Partner-Account anlegen, Blutspendedienste anlegen, Login-Daten an Bayr DRK
