### ISSUE TITLE
Extra Willkommens-Email an Orgas nach Bestätigung

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#194]
Sobald klar ist, was in der Email stehen soll, bitte hier aufschreiben:
https://github.com/ImmunHelden/ImmunHelden.de/blob/markdown/email/de/org_welcome.md

**Comment by DavidKo-ImmunHelden** [comment]
Moin, 

hier https://drive.google.com/drive/u/0/folders/1g_WVlQzpZAZyhE8y2cGg-W5xGd8XpOa0 findet ihr meinen Vorschlag für eine Autoreply-Email. So wie ich das verstanden habe, müssen aber noch wichtige Punkte ergänzt werden, sodass ich noch keine Änderung der aktuellen E-Mail vorgenommne habe.

**Comment by Highkovic** [comment]
Hallo zusammen,

ist geändert. @weliveindetail : Bitte überprüfe nochmals, ob ich das richtig in HTML umgesetzt habe. Nicht, dass da Fehler im Code sind, das wäre ungünstig.
Danke @DavidKo-ImmunHelden für die top Vorlage!

Viele Grüße
Heike

**Comment by weliveindetail** [comment]
@Highkovic Super, Glückwunsch zum ersten Commit! Hab mit https://github.com/ImmunHelden/ImmunHelden.de/commit/dec5c06e235a4f564ce8bfca868625c51ef5e794 nur noch ein paar Links eingefügt und Details vereinfacht. HTML braucht man in [Markdown](https://guides.github.com/features/mastering-markdown/) eigentlich nur selten.

Hier kann man schauen wie es am Ende aussieht:
https://immunhelden.de/sendExampleMail?template=email/de/org_welcome.md

Ich schick dann gleich mal ne Test Email an den Team Account.

**Comment by weliveindetail** [comment]
Mit https://github.com/ImmunHelden/ImmunHelden.de/commit/4ae3d585f45e86f107a5ea4c6d791944e4e8756d wird die Email nun beim Erstellen neuer User Accounts versendet. Bei mir hat das in einem schnellen Test funktioniert. Wäre toll wenn das nochmal jemand double-checken könnte. Wenn es dabei Probleme gibt, bitte das Ticket wieder öffnen. Danke!
