### ISSUE TITLE
Vereinssatzung: Anregungen und Fragen

### ISSUE THREAD

**Issue by DavidKo-ImmunHelden** [ImmunHelden/ImmunHelden.de#197]
"Sammel-Issue" rund um rechtliche und organisatorische Fragen, die unsere Vereinsgründung (insbesondere unsere Satzung) betreffen und vorab zu klären sind.

**Comment by ImmunHeldin-CE** [comment]
- Welche "Spezialmitglieder" (Vorstand usw.) brauchen wir? Was sind ihre Verantwortlichkeiten?
- Wer aus dem Team möchte freiwillig mehr Verantwortung übernehmen?
- Wie treffen wir offiziell Entscheidungen?

**Comment by Highkovic** [comment]
Hi zusammen,

ich schlage einen gesonderten Call zu dem Thema vor mit allen designierten Gründungsmitgliedern. Diese Woche Mittwoch oder Donnerstagabend?

**Comment by DavidKo-ImmunHelden** [comment]
Wie angekündigt, habe ich die Satzung angepasst und auf ImmunHelden "zugeschnitten". Den Entwurf, den wir ja noch diskutieren wollen, findet ihr hier:  https://drive.google.com/drive/u/0/folders/1Fb4JFibBoGvUrX4-nh-2mOYs4ATkYic4


Die internen Abläufe sind jetzt deutlich vereinfacht, ohne Mindestanforderungen an die Satzung oder formale Gemeinnützigkeitserfordernisse zu verletzen. Außerdem ist die Satzung insgesamt ärmer an Detailregelungen; die vereinsinterne Organisation kann so freier gestaltet werden. Damit werden spätere Anpassungen auch eher vermieden.

Zentrales Entscheidungs- und Kontrollorgan ist die Mitgliederversammlung

Anregungen / Korrekturen / etc. werden gern entgegengenommen! Danach geht das Ganze noch zu unserem Pro bono_  Rechtsanwalt Felix.

**Comment by DavidKo-ImmunHelden** [comment]
Update: Nach unserer Entwurfsbesprechung, steht jetzt unsere Satzung: https://drive.google.com/drive/u/0/folders/1Fb4JFibBoGvUrX4-nh-2mOYs4ATkYic4
-> Dok. mit dem Namen "ImmunHelden eV_ Satzung nach Entwurfsbesprechung"

Der nächste Schritt: I) Abnahme bei den Rechtsanwälten II) Annahme von den mindestens sieben Gründungsmitgliedern

**Comment by DavidKo-ImmunHelden** [comment]
Update II: Die Rechtsanwälte (die übrigens als einer der Top Wirtschaftskanzleien in D gelten), haben uns gerade eben Feedback zu unserer Satzung gegeben: Sehr gelungen heißt es :)

Die Änderungsvorschläge werde ich mir heute Abend ansehen und einpflegen, sodass Ihr euch die Satzung übers Wochenende ansehen könnt.

**Comment by weliveindetail** [comment]
@DavidKo-ImmunHelden Kannst du ihre Antwort nochmal an die Team Email Adresse weiterleiten? Danke!

**Comment by DavidKo-ImmunHelden** [comment]
[E-Mail – Lupp und Partner.pdf](https://github.com/ImmunHelden/ImmunHelden.de/files/5110183/E-Mail.Lupp.und.Partner.pdf)


hier noch einmal die Mail für alle

**Comment by DavidKo-ImmunHelden** [comment]
Hier ist die neueste Version gerade eingestellt (inhaltliche Änderungen sind gelb hervorgehoben zur besseren Nachvollziehbarkeit): https://drive.google.com/drive/u/0/folders/1Fb4JFibBoGvUrX4-nh-2mOYs4ATkYic4
