### ISSUE TITLE
Unsaubere Adressangabe bei der Erstellung einer Anzeige führt zu hunderten Leerzeilen

### ISSUE THREAD

**Issue by Highkovic** [ImmunHelden/ImmunHelden.de#201]

**Comment by weliveindetail** [comment]
Hallo @Highkovic, können wir konkretisieren wie das Verhalten zu produzieren ist? Bei meinen Tests ist es nie paassiert. Danke!

**Comment by DavidKo-ImmunHelden** [comment]
![image](https://user-images.githubusercontent.com/68906732/90441121-b1470200-e0d8-11ea-956d-3cd9c97c1454.png)

Hilft das weiter?

**Comment by weliveindetail** [comment]
Ok wenn ich es richtig verstehe geht es um Folgendes:
* Chrome auf Windows nutzen
* einen nagelneuen Account anlegen
* in der Übersichtstabelle via "+" einen neuen Eintrag anlegen
* 100+ neue leere Einträge erscheinen in der Tabelle

Korrigiert mich bitte, wenn falls das nicht eurem Vorgehen entspricht. Ich versuch das bei Gelegenheit zu reproduzieren, dann kann ich es fixen. Danke.

**Comment by DavidKo-ImmunHelden** [comment]
Genauso war der Ablauf. Vielen Dank :)

**Comment by weliveindetail** [comment]
@ChristinaSchath KLJDi

**Comment by weliveindetail** [comment]
Problem identifiziert und Fix in https://github.com/ImmunHelden/ImmunHelden.de/commit/66425b632ab8efaa0bcf30e18db327df614475f7 commitet. Deployment läuft: https://github.com/ImmunHelden/ImmunHelden.de/actions/runs/214012370

**Comment by weliveindetail** [comment]
Ok sollte ab sofort wieder korrekt funktionieren. @Highkovic  und @DavidKo-ImmunHelden könnt ihr bitte testen ob das Problem bei euch gelöst ist? Danke!

**Comment by weliveindetail** [comment]
Mit https://github.com/ImmunHelden/ImmunHelden.de/commit/7bdc1b8059b9ff356ddd37bdcaa628caa29e7f91 hab ich nun auch die leeren Einträge aus der Datenbank gekehrt. Falls doch noch welche zurück geblieben sind, bitte Bescheid geben.

**Comment by DavidKo-ImmunHelden** [comment]
Super, vielen Dank! Also bei mir taucht das Problem nicht mehr auf.

**Comment by weliveindetail** [comment]
Cool, dann seh ich das als Done an.
