### ISSUE TITLE
Setup basic gatsby project.

### ISSUE THREAD

**Issue by c0un7-z3r0** [ImmunHelden/ImmunHelden.de#21]
Expected outcome:
* Basic hello world page setup
* Generated from Markdown

**Comment by weliveindetail** [comment]
https://github.com/weliveindetail/ImmunHelden.de/issues/25#issuecomment-618882818 explains the staging environment for the new frontend. Let me know if you have questions.

**Comment by c0un7-z3r0** [comment]
@weliveindetail The basic setup is done in  #33
