### ISSUE TITLE
Aktualität der FAQ-Infos durch Datumsangabe anzeigen

### ISSUE THREAD

**Issue by Highkovic** [ImmunHelden/ImmunHelden.de#217]

**Comment by Highkovic** [comment]
![image](https://user-images.githubusercontent.com/63495989/102803444-8affde80-43b8-11eb-95e8-16d31356b3ea.png)

Wenn wir angeben, welchen Stand die aufgeführten Informationen haben, geben wir den Nutzer:Innen einen Hinweis darauf, wie sehr sie sich auf die Aktualität verlassen können. Das nimmt uns aus auch aus der Schusslinie - insbesondere beim aktuellen Tempo, in dem sich die Erkenntnisse ändern.

**Comment by weliveindetail** [comment]
Jo

**Comment by weliveindetail** [comment]
Voila: https://immunhelden.de/faq/

<img width="476" alt="date_added" src="https://user-images.githubusercontent.com/7307454/102810534-319dac80-43c4-11eb-8ffc-38d3a78d1fb0.png">
