### ISSUE TITLE
Setup CI/CD.

### ISSUE THREAD

**Issue by c0un7-z3r0** [ImmunHelden/ImmunHelden.de#22]
AC:
* Automatic deploy to staging and prod envs in firebase on merge of PR
* basic test setup done. (If there are tests then they should be run)

**Comment by broeber** [comment]
Ich denke, hier können wir mit 5Minds unterstützen.

**Comment by weliveindetail** [comment]
IIUC ist https://github.com/ImmunHelden/ImmunHelden.de/pull/54 der erste Schritt hier.

@c0un7-z3r0 ist das noch Todo / In Progress? Wenn fertig dann gern `Rebase & Merge`.
Ich kann gern testen, aber sonst selbst leider nicht viel beitragen.

**Comment by c0un7-z3r0** [comment]
@weliveindetail currently we do not have manual deploys with github actions yet. https://github.community/t5/GitHub-Actions/GitHub-Actions-Manual-Trigger-Approvals/td-p/31504.
 So I suggest to go the GitFlow way as described here. https://datasift.github.io/gitflow/IntroducingGitFlow.html

So meaning on develop branch we merge the PRs this is getting deployed to the dev envs.
Then when we want to deploy to production a new feature we can do this by merging develop into master. Would right now probably skip the release branch idea just to keep it simple.
