### ISSUE TITLE
Partner über LinkedIn Corona Initiative

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#28]
> Wollen wir "nur" Ehrenamt vermitteln oder auch Jobs?
> In beiden Fällen könnten wir die Corona-Aktion von LinkedIn sehr gut nutzen, um Partner für die Beta-Phase zu finden: https://news.linkedin.com/de-de/coronavirus-resource-hub

**Comment by ImmunHeldin-CE** [comment]
In Deutschland leider nicht doch nicht aktiv im Bereich Ehrenamt.

**Comment by weliveindetail** [comment]
Aber für Jobs oder? Sobald die Frage der Immunität geklärt ist und wir die arbeitsrechtlichen Aspekte kennen.
