### ISSUE TITLE
Schritt 2 bei Registrierung von ImmunHelden

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#3]
Um einen Indikator zur Immunität unserer Nutzer zu erfassen, gab es im Team Slack die Überlegung einen "Schritt 2" für die Registrierung von ImmunHelden einzuführen. Inhaltlich wurde bereits ein Konzept erarbeitet (siehe [ImmunHeldSchritt2.pdf](https://github.com/weliveindetail/ImmunHelden.de/files/4415811/ImmunHeldSchritt2.pdf)). Technisch würde es sehr ähnlich funktionieren, wie bei der Verifikation der Pin-Position von Hilfesuchenden:
https://immuneheroes.de/verifyStakeholderPin.html?lat=52.520173&lng=13.373354&map-opt-out=true

**Comment by weliveindetail** [comment]
Erster Draft: https://immunhelden.de/immunstatus.html

> Meine Immunität wurde mithilfe des [...] bestätigt.

Bin mir nicht sicher ob wir das derzeit schreiben können, bzw. ob es gegenüber unseren Partnern eher zu Skepsis führt als zu Vertrauen.

TODO: Farben (grün/gelb?), Datenschutz, Backend (wenn man Absenden klickt)

**Comment by weliveindetail** [comment]
Status: First draft ImmunStatus page https://github.com/weliveindetail/ImmunHelden.de/commit/e362c0ffa034fa10a8b375a2d3715a72f116439e

**Comment by ImmunHeldin-CE** [comment]
Stimmt! Vielleicht eher "meine überstandene Infektion bzw. sehr wahrscheinliche Immunität"?

**Comment by weliveindetail** [comment]
Immunität => überstandene Infektion https://github.com/weliveindetail/ImmunHelden.de/commit/443fcd3b65eb5e59577d409db861409832e4ad11

**Comment by weliveindetail** [comment]
Offen ist noch die Implementierung im Backend und das Routing nach https://immunhelden.de/heldeninfo.html wenn man im ersten Schritt Absenden klickt.

**Comment by weliveindetail** [comment]
Wir können Seite vorläufig auch zum editieren von Profilen benutzen. Die vorhandenen Informationen müssen dann als URL Parameter mitgeschickt werden. Das ist nicht professionell aber maybe enough for the time being, z.B.:
https://immunhelden.de/heldeninfo.html?key=-M6_O1Q5Km_XO1nvRCNr&firstName=Stefan&lastName=Gr%C3%A4nitz&frequency=daily&availability=parttime&status=assumed-contact&edit=true
