### ISSUE TITLE
Material für Vodafone Institute

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#31]
Vodafone bietet an uns über ihre Kommunikationskanäle (Social Media, Magazine, Blogs) zu promoten und Reichweite zu geben. Da Vodafone ein Unternehmen mit globaler Reichweite ist, wollen sie alle Informationen auf Englisch.

Unsere Notizen:
https://docs.google.com/document/d/1ddoi6-U3OjYCpnpsbmZ9SAiqCBrMOYGyRdy4jRTZXBw/edit?usp=sharing

**Comment by weliveindetail** [comment]
Bin mit noah für Rückfragen in Kontakt:
* Sollen/Müssen unsere Materialien (Zitate Grafiken, Videos) auch auf Englisch sein?
* Würde ein Zeitraum ab Mitte Mai passen? Welche zeitliche Planung hatten sie im Sinn?

**Comment by weliveindetail** [comment]
Wir bekommen einen Slot in der ersten Juniwoche. Materialien auf Englisch wäre sehr wichtig.

**Comment by DominikGolle** [comment]
Wir könnten hierfür auch den Podcast mit Pierre nutzen - den kann man bestimmt auch auf Englisch machen.

**Comment by weliveindetail** [comment]
Die Vodafone Kampagne ist jetzt ein Milestone: https://github.com/ImmunHelden/ImmunHelden.de/milestone/7

**Comment by Highkovic** [comment]
Besprochen im Call vom 1. Juni 2020, Stefan schickt es so raus

**Comment by weliveindetail** [comment]
[ImmunHelden_Vodafone_v2_2020-06-01.pdf](https://github.com/ImmunHelden/ImmunHelden.de/files/4729835/ImmunHelden_Vodafone_v2_2020-06-01.pdf)

Das war der finale Stand.
