### ISSUE TITLE
YouKnow Erklärfilm

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#32]
@DominikGolle hats gefunden und Viktoria hat uns angemeldet:
https://you-know.de/erklaerfilme-awareness/

Rückmeldung kommt am 30. April. Was müssen wir vorbereiten, falls das klappt?

**Comment by vikiarn** [comment]
Ich habe soeben eine Rückmeldung erhalten, dass sie sich in der Woche ab dem 4. Mail bei uns melden würden.
Es gibt vier Kategorien: animated, icon-based, handmade und customed
Bezüglich der Anforderungen nach unserer möglichen Nominierung, habe ich leider keine Informationen gefunden - könnte gerne eine E-Mail schreiben allerdings würde das ggf. unsere Bewerbung beeinflussen nicht?

**Comment by weliveindetail** [comment]
Ok, also läuft die Ausschreibung wohl noch eine Woche länger. Das klingt ja schon fast nach einer geringen Zahl von Bewerbern! Gut für uns. Wenn wir unsere Bewerbung positiv beeinflussen können dann gern eine E-Mail schreiben 😄 Sonst können wir abwarten denke ich. Danks für das schnelle Feedback!

**Comment by weliveindetail** [comment]
Eine Sache noch, falls wir uns an sie wenden oder im Nachhinein wenn es klappt: können wir den Film auf deutsch UND englisch bekommen? Eine englische Version wäre perfekt für die Vodafone Kampagne Mitte Mai https://github.com/weliveindetail/ImmunHelden.de/issues/31

**Comment by weliveindetail** [comment]
> Nachfrage an youknow ist verschickt

**Comment by weliveindetail** [comment]
QuarantäneHelden hat seit heute morgen ein Video:
https://twitter.com/QuarantaeneHeld/status/1255065463492616192

**Comment by weliveindetail** [comment]
WirVsVirus macht auch sog. "Check-In" Videos:
https://www.youtube.com/watch?v=sSoaA2H0RL0

**Comment by vikiarn** [comment]
Hallo hallo, wir müssen heute Abend unsere Sprecherin/unseren Sprecher auswählen: https://intern.you-know.de/speaker/?p=IMU-05573&l=de&s=de-DE&t=1589198992124

**Comment by vikiarn** [comment]
Und hier der Link zum Text, der noch 1/2 neue Vorschläge beinhaltet: https://docs.google.com/document/d/1enTVVHMiEahppROIum0q9P9ZwPlpDC2mUH6w6usj7TU/edit?usp=sharing

**Comment by vikiarn** [comment]
Hier die zweite Version des Storyboards: https://app.filestage.io/#!/review/bb159547a4cf48b2a3585b69fdddc933/file/3188728171ff46dfa61a5d6050ca7021/v2

**Comment by weliveindetail** [comment]
Unser Video kann dann sofort in den neuen Slack Channel `#pitch_videos`. Gutes Timing! 🙂

**Comment by vikiarn** [comment]
Die englische Version folgt Ende Mai

**Comment by vikiarn** [comment]
https://youtu.be/fyPF3RUv00A

**Comment by weliveindetail** [comment]
Hier ist für uns nichts mehr zu tun. Gute Arbeit! Zur abschließenden Frage nach den Grafiken: Wenn ich es richtig verstanden habe, können wir die Grafiken aus dem Storyboard verwenden solange sie unverändert bleiben.

**Comment by vikiarn** [comment]
Ja genau - wir können die Graphiken aus dem Storyboard entnehmen und diese dann an youknow schicken - sie stellen sie uns dann in guter Qualität zur Verfügung.
