### ISSUE TITLE
Finale "Bewerbung" BMBF vorbereiten

### ISSUE THREAD

**Issue by ImmunHeldin-CE** [ImmunHelden/ImmunHelden.de#39]

**Comment by weliveindetail** [comment]
Hier die Vorlage zur Anmeldung der GbR: [VorlageGbR.pdf](https://github.com/ImmunHelden/ImmunHelden.de/files/4546891/VorlageGbR.pdf)

**Comment by weliveindetail** [comment]
Weitere Unterlagen und Informationen, die uns bei der Antragstellung helfen könnten https://cloud.prototypefund.de/s/NLfxCjsH7ZgQg8A

**Comment by Highkovic** [comment]
GbR als Rechtsform für den Anfang gesetzt, da Voraussetzung für die BMBF-Förderung. 

Eine GbR kann auch von mehreren juristischen Personen gegründet werden (https://gruenderplattform.de/rechtsformen/gbr-gruenden)


Abschluss einer Betriebshaftpflichtversicherung für eine GbR ist möglich (https://www.betriebshaftpflicht.info/ratgeber/betriebshaftpflicht-fuer-eine-gbr/) (bearbeitet)

**Comment by weliveindetail** [comment]
Relevante Angaben aus dem Fragebogen "Wichtige Fragen vor der Förderung" der heute kurzfristig ausgefüllt werden musste

Wann ist dein gewünschter Förderbeginn? *
1.6.2020

Werdet ihr die Förderung als GbR annehmen? *
Ja, weil wir als Team gefördert werden möchten.

Wenn ihr als GbR gefördert werden möchtet, wie lautet der vollständige Name der GbR? *
noch keine Angabe

An welchem Ort ist der Projektsitz (Wohnsitz Einzelperson oder Geschäftsführer:in der GbR)? *
Berlin

Wie lautet die amtliche Postleitzahl des Projektsitzes (Wohnsitz Einzelperson oder Geschäftsführer:in der GbR)? *
12045

**Comment by weliveindetail** [comment]
Infos aus unserem Slack Channel die hier vielleicht besser aufgehoben sind:
* Im Förderantrag 5% für Gemeinkosten angeben

Für Gründer:innen der GbR:
* Wohnsitz in Deutschland ist Voraussetzung
* Bei Angestellten muss Nebentätigkeit vom Arbeitgeber schriftlich bestätigt werden
* Auszahlung nachschüssig
* Förderung ist "echter Zuschuss" und damit steuerfrei, aber einkommensteuerpflichtig (Einkommen aus selbstständiger Tätigkeit)

Auswirkung Kurzarbeit:
* Freistellung vom Arbeitgeber muss trotzdem erfolgen
* Kurzarbeitergeld verringert sich dann um den Stundenanteil der Freistellung
* Aufstocken bis Normalgehalt bzw. Normalstunden typischerweise unproblematisch

Zur GbR:
* Kann im Nachhinein nicht erweitert werden
* Name = alle Nachnamen hineinander gereiht + "GbR"
* Einen Geschäftsführer definieren, andere sind Mitglieder
* Positiver Kontostand auf gewähltem GbR Konto nachweisen

**Comment by weliveindetail** [comment]
> Eine GbR kann auch von mehreren juristischen Personen gegründet werden

DLR sagt wir sollen "Einen Geschäftsführer definieren, andere sind Mitglieder"

**Comment by Highkovic** [comment]
> > Eine GbR kann auch von mehreren juristischen Personen gegründet werden
> 
> DLR sagt wir sollen "Einen Geschäftsführer definieren, andere sind Mitglieder"

Dann würde ich sagen: Du bist der GF, Stefan, wir anderen sind Mitglieder, d.h. Gesellschafter

**Comment by Highkovic** [comment]
> Hier die Vorlage zur Anmeldung der GbR: [VorlageGbR.pdf](https://github.com/ImmunHelden/ImmunHelden.de/files/4546891/VorlageGbR.pdf)

Zu unterzeichnen dann als Umlaufbeschluss

**Comment by ImmunHeldin-CE** [comment]
Alles muss am 15.05. eingereicht werden....

Für alle anderen mit dem *Start zum 1. Juni* gibt es eine *wichtige Info* vom DLR:
Reicht bitte so früh wie möglich, spätestens aber zum 15.05. euren Antrag elektronisch ein und umgehend danach die rechtsverbindlich unterschriebenen Papieranträge plus Anlagen. Nur Angaben zu Steuernummern und GbR-Konten können nachgereicht werden.
Eure *Checkliste *für die Anträge:
- Antrag
- GbR-Vertrag (eine Person muss einzelvertretungsberechtigt sein)
- De-Minimis Erklärung
- 1 Kontoauszug (mind. Saldo des Eigenanteils)
- Postadressen aller GbR-Mitglieder
- Kontoverbindung der GbR (kann auch nach Buchung der Bewilligung erfolgen)
- GbR Steuernummer - zunächst Gewerbeanmeldung (s.u.), dann Anmeldung beim Finanzamt (kann nach Buchung der Bewilligung erfolgen)

Bitte alles nach dem elektronischen einreichen alles unterschrieben per Post an das DLR senden.

**Comment by ImmunHeldin-CE** [comment]
An die Berliner hier @weliveindetail @vikiarn aus dem Prototype-Fund Chat noch eine Frage: "Wer von euch wohnt denn in (der Nähe von) Berlin und hätte evtl. Lust auf einen Termin beim BMBF? 🙂"

**Comment by SandraPlantLocal** [comment]
Für einen Termin in Berlin stehe ich auch zur Verfügung (wenn es zeitlich passt).

**Comment by weliveindetail** [comment]
Von Lust würde ich nicht sprechen, aber wenn nötig machbar

**Comment by vikiarn** [comment]
Sobald ich dann aus meiner Quarantäne bin - kann ich das auch gerne machen. Ich wohne recht zentral :)

**Comment by ImmunHeldin-CE** [comment]
Eine erste XML-Datei zur Einsicht des Formulars auf Easy-Online habe ich auf Slack gepostet (Github unterstützt den Dateityp nicht). Was wir noch dringend brauchen: 
- Eine GbR und im Idealfall ein GbR-Konto, auf das wir insgesamt 2.500 € übertragen (Eigenanteil) - ansonsten tatsächlich eine Kontoauskunft von ALLEN in der GbR
- Eine Auflistung der Personen, die offiziell Gehälter aus der Förderung bekommen samt Begründung (ein Satz dazu, welche Aufgaben er/sie im Team übernimmt)
- Einen Geschäftsführer (Stefan), eine bzw. einen Bevollmächtigte*n (@weliveindetail ?) 2 Ansprechpersonen für administratives (ich könnte gern eine sein): All diese Personen müssen Adresse, Email-Adresse (Immunhelden-Adressen verwenden?) und Telefonnummer angeben.

Der Rest ist zwar aufwändig aber (hoffentlich) unproblematisch.

**Comment by weliveindetail** [comment]
> Eine GbR und im Idealfall ein GbR-Konto, auf das wir insgesamt 2.500 € übertragen (Eigenanteil) - ansonsten tatsächlich eine Kontoauskunft von ALLEN in der GbR

Hatte es so verstanden, dass wir dafür eins unserer Konten angeben. Oder ist der Kontoinhalt irgendwie Teil der GbR?

> Einen Geschäftsführer (Stefan), eine bzw. einen Bevollmächtigte*n (@weliveindetail ?) 2 Ansprechpersonen für administratives (ich könnte gern eine sein): All diese Personen müssen Adresse, Email-Adresse (Immunhelden-Adressen verwenden?) und Telefonnummer angeben.

Aye aye! Ansprechperson und Bevollmächtigte müssen verschiedene Personen sein? Immunhelden-Adressen klaro 🙂

**Comment by weliveindetail** [comment]
> Der Rest ist zwar aufwändig aber (hoffentlich) unproblematisch.

Yippie!

@ImmunHeldin-CE Du bist natürlich Chief Administrative Officer 🙂

**Comment by Highkovic** [comment]
Okay, dann bereite ich heute den GbR-Vertrag vor, ggf. nehme ich ein ausführliches Muster als das oben. Ich kann es am Freitag in 6facher Ausfertigung ausdrucken, unterzeichnen und danach in Umlauf bringen. Wichtig: am 15.05. muss das Ding bei Stefan in Berlin sein spätestens, damit er es hochladen kann. Das Dokument muss von über Augsburg (@DominikGolle ) nach Hamburg (@ImmunHeldin-CE ) und schließlich nach Berlin (@weliveindetail @SandraPlantLocal @vikiarn ), richtig? @c0un7-z3r0 , Du bist ja wegen Deines AG außen vor.

**Comment by Highkovic** [comment]
Gewerbeanmeldung in Berlin ist auch online möglich: https://www.berlin.de/ea/emeldung/emeldung/?op=emeldung-start-meldeart
Vorschlag: Die Gebühr (15 €) teilen wir unter uns auf, sammeln das Geld per Paypal ein.

**Comment by Highkovic** [comment]
> > Eine GbR und im Idealfall ein GbR-Konto, auf das wir insgesamt 2.500 € übertragen (Eigenanteil) - ansonsten tatsächlich eine Kontoauskunft von ALLEN in der GbR
> 
> Hatte es so verstanden, dass wir dafür eins unserer Konten angeben. Oder ist der Kontoinhalt irgendwie Teil der GbR?
>
Für den Anfang reicht ein privates Konto, das mindestens 2.500 € aufweist. Wir müssen dann allerdings ein GbR-Konto eröffnen und 2.500 € einlegen, das kann dann das private ablösen.

**Comment by ImmunHeldin-CE** [comment]
> > > Eine GbR und im Idealfall ein GbR-Konto, auf das wir insgesamt 2.500 € übertragen (Eigenanteil) - ansonsten tatsächlich eine Kontoauskunft von ALLEN in der GbR
> > 
> > 
> > Hatte es so verstanden, dass wir dafür eins unserer Konten angeben. Oder ist der Kontoinhalt irgendwie Teil der GbR?
> 
> Für den Anfang reicht ein privates Konto, das mindestens 2.500 € aufweist. Wir müssen dann allerdings ein GbR-Konto eröffnen und 2.500 € einlegen, das kann dann das private ablösen.

Ah stimmt, ein Kontoauszug reicht! :) Wer meldet sich freiwillig? Wir bräuchten so eine Art Online-Roulette!

**Comment by ImmunHeldin-CE** [comment]
> Aye aye! Ansprechperson und Bevollmächtigte müssen verschiedene Personen sein? Immunhelden-Adressen klaro 🙂

Nein. Du bist aber unser unterschriftsberechtigter Geschäftsführer laut GbR-Vertrag, magst du dann auch unser Bevollmächtigter sein @weliveindetail ?

**Comment by weliveindetail** [comment]
Geht klar. Von mir aus können wir auch mein Konto nehmen.

**Comment by DominikGolle** [comment]
- Gbr Vertrag ist auf dem Postweg
- Gbr wird nicht auf Webseite genannt
- Es fehlt noch eine Beschreibung der Tätigkeiten aller Personen, die Teil der Gbr werden
- Saskia und Sonja sind im Vertrag genannt - wenn sie nicht Teil der Gbr werden, einfach streichen

**Comment by weliveindetail** [comment]
BMBF Bewerbung ist bei "easy-online" des DLR eingegangen und in Papierform am Montag in die Post. GbR Anmeldung liegt seit Dienstag beim Finanzamt Neukölln. Dort werd ich mich nächste Woche nochmal melden und checken, dass der Prozess läuft. Von meiner ist hier sonst nichts mehr zu tun. Falls doch, dann bitte wieder auf machen.
