### ISSUE TITLE
Krankenhäuser als Partner für die Beta-Phase anschreiben

### ISSUE THREAD

**Issue by ImmunHeldin-CE** [ImmunHelden/ImmunHelden.de#41]
Fokus auf einfachen Tätigkeiten, z.B. Reinigung, Essensausgabe o.ä.

**Comment by weliveindetail** [comment]
Super, ja wir sollten möglichst früh verstehen, was es auf unserer Seite braucht um ihr Interesse zu wecken.

**Comment by weliveindetail** [comment]
Bitter weiterführen in https://github.com/ImmunHelden/ImmunHelden.de/issues/127
