### ISSUE TITLE
Accounts und Login für Partner

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#45]
Jeder Partner braucht einen Account. Der Login kann über eine eigene Authentifizierung laufen und/oder einen externen Identity-Provider wie Google, Apple, (LinkedIn?) (Facebook?), etc.

Für den Anfang sollte ein Login pro Account genügen (mehrere Ansprechpartner pro Account ggf. später).

**Comment by broeber** [comment]
@weliveindetail Habt ihr die Authentifizierungsfrage und das Identity Management schon geklärt? Falls nicht, könnten wir hier unterstützen.

**Comment by weliveindetail** [comment]
Hatte schon mal mit @c0un7-z3r0 davon gesprochen, technisch ist dafür aber noch nichts passiert. Wir würden uns über eure Unterstützung hier sehr freuen.

**Comment by broeber** [comment]
Okay, dann assigne ich mich hier auch mal und mache euch Anfang der Woche einen Vorschlag.

**Comment by weliveindetail** [comment]
Hier eine erste Sammlung von "Stories" in Kurzform. Dabei sind Organisationen (= Partner) diejenigen die einen Login. ImmunHelden wollen wir bis auf weiteres anonym halten (nur E-Mail und PLZ).

* Organisationen legen einen Account an, um Angebote zu erstellen und zu verwalten (ggf. in der Map).
* ImmunHelden finden Angebote in ihrer Region schnell und leicht (Map).
* ImmunHelden registrieren sich mit minimalen Angaben, um benachrichtigt zu werden, sobald es in ihrer Region neue Angebote gibt.
* ImmunHelden senden Kontaktanfragen für Angebote (Map). Dafür müssen sie registriert sein oder eine Kontaktmöglichkeit hinterlegen. (Sie können sich von der Bestätigungsnachricht aus nachträglich registrieren.)
* ImmunHelden können auf der Plattform ihren Immunitätsnachweis hinterlegen oder vernüpfen?
* Organisationen nehmen Kontaktanfragen an, um Konversationen zu beginnen.
* Organisationen haben durch einen Login Zugriff auf all ihre Konversationen.
* ImmunHelden haben durch einen Link in der Benachrichtigung Zugriff auf genau diese Konversation.
* Während einer Konversation wird mit Zustimmung beider Teilnehmer ein Video-Chat gestartet (ggf. mit Vereinbarung des Zeitpunkts).

**Comment by weliveindetail** [comment]
Wie gestern besprochen: Wenn wir unsere "Standard-Anforderungen" über die integrierte Sign-In Möglichkeit abwickeln können, wäre das wohl die schnellste & einfachste Lösung. Alternativ via Identity-Server mit Daten in der Realtime DB bei uns und Hosting (wahrscheinlich) bei euch auch ok.

Zu Firebase: Die CLI via npm funktioniert bei mir prima für Deployment und Serving via localhost. Bin kein Firebase Experte, kann aber gern versuchen zu helfen, wenn es Fragen gibt. Deploy ins Staging-Environment für das neue Frontend via `dev` Target: `firebase deploy --only hosting:dev` (IIUC wird Production mit überschrieben, wenn man das Target weglässt)

**Comment by roblen45** [comment]
Ich habe mir gestern die Firebase Authentifizierung angesehen und wir können damit die Anforderungen abbilden. Das soll dann aber nur in der neuen Webseite und den bestehenden Funktionen eingebaut werden oder?

**Comment by weliveindetail** [comment]
Richtig. @c0un7-z3r0 können wir fürs Login von Organisationen schon ein Frontend vorbereiten? Dabei ist das Design ja erstmal Nebensache oder?

**Comment by weliveindetail** [comment]
Wir brauchen hier bald eine Lösung. Evtl findet sich nächste Woche jemand vom DRK um deren Spendeeinrichtungen zu verwalten. Dafür sollten wir mindestens:
* einen Account anlegen können (notfalls manuell)
* ein Frontend für den Login anbieten (Design egal)
* [existierende Einträge](https://github.com/ImmunHelden/WirVsVirusMap/blob/data/blutspenden.de/blutspenden-clean.json) darstellen können

Idealerweise würden wir das Frontend direkt in React bauen.

**Comment by weliveindetail** [comment]
@c0un7-z3r0 Es gibt jetzt einen Test-User team@immunhelden.de (Passwort siehe Slack sensitive Channel). Vielleicht krieg ich eine Backend Funktion für die Authentication heute noch hin.

**Comment by weliveindetail** [comment]
Das klingt so, als ob man die Auth direkt vom Frontend aus machen kann, ganz ohne eigenen Backendcode:
https://firebase.google.com/docs/auth/web/password-auth

Ist das plausibel?

**Comment by roblen45** [comment]
Ja genau damit kannst du deine backend absichern

**Comment by weliveindetail** [comment]
Danke @c0un7-z3r0! Login und Signup mit Double-Opt-In sind jetzt onine auf der Dev Site:
https://dev.immunhelden.de/de/partner/login/

Geile Grafiken und sogar schon im richtigen Farbton oder? Sind die von undraw.co?

Habs mehrmals getestet:
* Basic Register-Login Workflow funktioniert gut!
* Login mit falschen Credentials wird korrekt abgelehnt.
* Login für noch nicht bestätigten Account leitet korrekt weiter zur Double-Opt-In Seite.
* Signup für einen Account der schon existiert wird korrekt abgelehnt (Das war nicht so leicht zu testen. Setzen wir einen Cookie, dass man sich bereits registriert hat und Double-Opt-In noch aussteht?)
* Signup mit zu schwachem Passwort wird korrekt abgelehnt.
* Double-Opt-In nach Ablauf der Frist (im Test hab ich meinen Account manuell gelöscht) wird korrekt abgelehnt.

Einziger Bug:
* Bestätigungsmail fürs Double-Opt-In kommt bei mir erst, wenn ich auf Resend drücke.

Noch ein paar Details fürs Polishing - ich schau mal, dass ich hier auch was übernehmen kann:
* Link für Double-OptIn enthält einen `apiKey`. Nur um sicher zu gehen: das ist ein public key, richtig? :) https://immunhelden.firebaseapp.com/__/auth/action?mode=verifyEmail&apiKey=AIzaSy..
* Das Ziel des Bestätigungslinks bräuchte noch einen Link zurück zur Login Seite.
* Inhalt der Mail würde ich noch etwas anpassen.

**Comment by weliveindetail** [comment]
Läuft  jetzt! Yey
