### ISSUE TITLE
Übersetzung Webseite auf Englisch

### ISSUE THREAD

**Issue by vikiarn** [ImmunHelden/ImmunHelden.de#48]

**Comment by weliveindetail** [comment]
Hi Viktoria, die Texte von der Webseite stehen mit ein paar zusätzlichen "HTML Tags" so auch im Quellcode, z.B. ist die Einleitung auf der Landing Page (neben der Map) hier: https://github.com/ImmunHelden/ImmunHelden.de/blob/master/website/index.html#L149

Die Tags sind schnell erklärt: `<a>` wird ein Link, `<b>` **bold**, `<br>` ein Line-Break, `<hX>` Heading und `<img>` ein Bild. Wenn wir die Überarbeitung und Übersetzung direkt in dem Format machen könnten, macht das den Einbau am Ende deutlich einfacher. Du könntest die Datei herunterladen (oben Rechtsklick auf `Raw` & `Save as..`), mit einem Texteditor öffnen und bearbeiten und im Browser öffnen um zu sehen wie es aussieht. Dann kann ich es zum Schluss sehr leicht einchecken.

**Comment by vikiarn** [comment]
Hallo Stefan - vielen Dank! Ich habe es versucht. Klappt das so für dich? Gibt es eine Möglichkeit, dass ich mir das nochmal ansehe? Es ist recht schwierig, es auf Richtigkeit in diesem Dokument zu überprüfen. Die FAQ habe ich auch übersetzt - allerdings sind die sehr stark auf die Immunität abgezielt. Ich frage mich, wie sinnvoll diese sind - daher habe ich sie vorerst in einem Word-Dokument bearbeitet und übersetzt. Liebe Grüße Viktoria
[Landing Page_eng.txt](https://github.com/ImmunHelden/ImmunHelden.de/files/4551949/Landing.Page_eng.txt)
[Landing Page_verbessert.txt](https://github.com/ImmunHelden/ImmunHelden.de/files/4551950/Landing.Page_verbessert.txt)

**Comment by weliveindetail** [comment]
Hey das sieht ja schon echt gut aus. Hab die Korrekturen im deutschen Text schon eingecheckt: https://github.com/ImmunHelden/ImmunHelden.de/commit/5cabc1aaff5a0e472afe882ca78d12303f066499

> Gibt es eine Möglichkeit, dass ich mir das nochmal ansehe?

Mit Endung `.html` speichern und im Browser öffnen 🙂 

> Die FAQ habe ich auch übersetzt - allerdings sind die sehr stark auf die Immunität abgezielt.

Wir sollten wohl auch Fragen zu unserem Prozess beantworten. Vielleicht hilft da [unser Statusupdate von dieser Woche](https://docs.google.com/document/d/1btvLS9NAxgc1mZ6diiYJmM2S_c8zRtUjltLfKfuToEw/edit#heading=h.z9qvlk56v1ay). Ich denke sonst sind Immunitätsfragen schon der wichtigste Punkt in der FAQ. Es zeigt auch dass wir uns damit auseinander setzen. Ich versuche wichtige Entwicklungen dazu bei Twitter zu sammeln: https://twitter.com/ImmunHelden

**Comment by weliveindetail** [comment]
Hab Marie von JOWOMO kontaktiert wegen rechtlichen Fragen. Sie haben eine gute FAQ: https://jowomo.de/info/faq

Wenn wir an unserer ohnehin dran sind, können wir auch gern auch Fragen zu Nutzergruppe/Nutzung hinzufügen. @vikiarn @DominikGolle was denkt ihr?

**Comment by vikiarn** [comment]
Ich denke auch. Sobald das Konzept feststeht (für mich ist es zumindest noch nicht 100% klar) dann sollten wir gezielt alle Fragen mit aufnehmen, die unsere Nutzer*innen haben. Ich habe gestern auch mit einem ehemaligen Kollegen gesprochen - er ist jetzt in einer Kanzlei tätig, die AN vertritt und uns daher sicherlich auch gut Fragen zu Arbeitsverträgen beantworten können. Bei dem Versuch, einige Fragen zu finden, ist mir aufgefallen, dass ich den neuen Ansatz noch nicht ganz gefasst habe. Morgen werde ich versuchen die FAQ gemeinsam mit den von dir, Stefan, vorgeschlagenen zu überarbeiten und mir dazu auch die von JOWOMO anzusehen. Kann dann ja gerne mal einen Vorschlag machen, der dann auch ins Englische übertragen werden kann. LG

**Comment by weliveindetail** [comment]
Um gemeinsam ein besseres Verständnis zu entwickeln, können wir hier "User Stories" sammeln:
https://github.com/ImmunHelden/ImmunHelden.de/wiki

Im Fragenkatalog zum Design der Webseite haben sich einige Use-Cases gesammelt 🙂 
https://docs.google.com/document/d/14NOZCeu-ajN7WtEGFOfTpc_77wqYIAlgPzh3_knF5LQ/edit#

Ist auch ein guter Punkt für die Agenda in Call am Montag.

**Comment by weliveindetail** [comment]
Für die FAQ von @vikiarn 👍 
https://docs.google.com/document/d/101LAovqqrFEenTW8CI0gHyg92QrofqqNVWgKG5Y0aWs/edit?usp=sharing

@ImmunHeldin-CE Den Stand der FAQ hier müssten wir wohl ohnehin nochmal besprechen. Ich finde es wäre eine gute Gelegenheit das zusammen gleich mit Saskia zu tun. Dann haben wir es auch gleich aus medizinischer Sicht reviewed 🙂

**Comment by ImmunHeldin-CE** [comment]
Vielen Dank, Viktoria! 
Bei der Antwort auf die Frage zu den Mutationen habe ich noch was geändert, da der Stand vom letzten Mal inzwischen überholt ist.

**Comment by weliveindetail** [comment]
Todo: deploy english page in old design

**Comment by weliveindetail** [comment]
Todo: FAQ Änderungswünsche klären

**Comment by weliveindetail** [comment]
Entwurf für englischsprachige Landing Page findet sich nun hier: https://immunhelden.eu

**Comment by ImmunHeldin-CE** [comment]
Super, dass die englischsprachige Landing Page schon so weit ist! 
Mir ist aufgefallen, dass wir in der englischen Version viel stärker von Immunität sprechen - das können wir ja bisher eigentlich nicht.
Daher 2 Vorschläge: "I have **recovered** from COVID-19, how can I help" statt "I am immune" (finde ich auch in der deutschen Version störend, weil noch nicht bewiesen) und "Use your **immune reponse** for the benefit of all" statt "immunity".

**Comment by weliveindetail** [comment]
> Daher 2 Vorschläge: "I have recovered from...

Eingebaut: https://immunhelden.eu/

**Comment by weliveindetail** [comment]
IMHO good enough for now. Ich würde das schließen
