### ISSUE TITLE
Gemeinsamer Kalender

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#49]
Möglichst einfach und übersichtlich. Von mir aus ist Google hier akzeptabel.

Den WirVsVirus Kalender gibt es hier mit Google:
https://calendar.google.com/calendar/embed?src=projecttogether.org_6431985qcidblp5ksq136tmo0c%40group.calendar.google.com&ctz=Europe%2FBerlin

Und hier im iCal Format:
https://calendar.google.com/calendar/ical/projecttogether.org_6431985qcidblp5ksq136tmo0c%40group.calendar.google.com/public/basic.ics

**Comment by DominikGolle** [comment]
Löschung der alten Eventbot-Nachrichten gestaltet sich schwierig, aber ich bin dran.

**Comment by DominikGolle** [comment]
Hatte das issue fälschlicherweise geschlossen, jetzt aber wiedergefunden und geöffnet.
Ich such grad noch nach einem online Gruppenkalender, den alle editieren können - also auch Personen ohne Google Account.

**Comment by DominikGolle** [comment]
Der eventbot ist wiederauferstanden und hat dieses issue geschlossen.
