### ISSUE TITLE
Tafeln als potenzielle Partner für Beta-Phase kontaktieren

### ISSUE THREAD

**Issue by ImmunHeldin-CE** [ImmunHelden/ImmunHelden.de#50]
Die Tafeln suchen Helfer:innen in der Coronakrise: https://www.tafel.de/themen/coronavirus/

**Comment by weliveindetail** [comment]
Hier noch mal die E-Mail für künftige Kontaktanfragen: [Kontakt Tafel Hamburg.pdf](https://github.com/ImmunHelden/ImmunHelden.de/files/4552502/Kontakt.Tafel.Hamburg.pdf)

**Comment by weliveindetail** [comment]
@ImmunHeldin-CE Bisher bei mir keine Antwort. Bei dir? Denkst du ein Follow-up macht Sinn?

Im Rahmen von https://github.com/ImmunHelden/ImmunHelden.de/issues/11 will die drei Previews für Plasma auf die Karte bringen. Sollen wir auch ein Preview für die Tafel machen? Für ein Follow-up brauchen wir auf jeden Fall was konkretes, denk ich.

**Comment by Highkovic** [comment]
Vorsitzender Tafel Deutschland über info@ kontaktiert, Buttom-Up-Kontakt über Tafel Bremerhaven und Stuttgart avisiert

**Comment by Highkovic** [comment]
Tafel Deutschland hat sich zurückgemeldet: wollen wegen fehlender Sicherheit zur Immunität nicht mitmachen - nochmals nachgefasst unter Verweis auf geringeres Risiko.

Tafel Bremerhaven über Kontakt von Sonja angeschrieben

**Comment by ImmunHeldin-CE** [comment]
Ach, verdammt :( 
Haben sie gesagt, was genau ihnen zu riskant ist? Sie suchen ja zurzeit Helfer*innen. Ist es ihnen zu riskant, auf einer Website zu erscheinen, die Immunhelden heißt? Wäre sehr interessant zu wissen!

**Comment by Highkovic** [comment]
> Ach, verdammt :(
> Haben sie gesagt, was genau ihnen zu riskant ist? Sie suchen ja zurzeit Helfer*innen. Ist es ihnen zu riskant, auf einer Website zu erscheinen, die Immunhelden heißt? Wäre sehr interessant zu wissen!

Leider nicht, die Absage war sehr generisch, daher habe ich auch nochmals nachgehakt. Strategie: wenn nichts zurückkommt, dafür aber bei Bremerhaven, nehme ich das als Aufhänger für einen Anruf :-)

**Comment by ImmunHeldin-CE** [comment]
Tafel Hamburg heute (25.05.) mehrfach angerufen, wurde an unterschiedliche Personen weitergeleitet, die alle keine Auskunft geben konnten, mir aber versprochen haben, dass die Verantwortlichen zurückrufen. Nächster telefonischer Kontaktversuch am Freitag (29.05.).

**Comment by ImmunHeldin-CE** [comment]
Update Hamburger Tafel: Sie sind dabei und hatten keinerlei Bedenken, wenn sich auch ImmunHelden an die für alle geltenden Schutzmaßnahmen halten! :)

**Comment by Highkovic** [comment]
Wir dürfen die Tafel-Suche auf unserer Webpage verlinken: "Gerne können wir Ihnen anbieten, dass Sie unsere Tafel-Suche – mit der Sie alle Tafeln mit Kontaktdaten finden – auf Ihrer Webseite verlinken (bitte ohne unser Logo): http://www.tafel.de/ueber-uns/die-tafeln/tafel-suche/ " (genehmigt durch Frau Willmann von Tafel Deutschland e.V.), Einbindung der Anlaufstellen in unsere eigene Karte angefragt.

**Comment by weliveindetail** [comment]
> Update Hamburger Tafel: Sie sind dabei und hatten keinerlei Bedenken, wenn sich auch ImmunHelden an die für alle geltenden Schutzmaßnahmen halten! :)

Da https://dev.immunhelden.de/en/partner/signup/ ja nun sicher funktioniert und sogar auf deutsch ist, wäre ein Follow-up vielleicht gut?

**Comment by weliveindetail** [comment]
Das ist jetzt Teil von #127 oder? Dann vielleicht zusammenführen?
