### ISSUE TITLE
FAQs und Infos zum aktuellsten Forschungsstand aktualisieren

### ISSUE THREAD

**Issue by ImmunHeldin-CE** [ImmunHelden/ImmunHelden.de#51]
- mind. wöchentliche Recherche
- Aktualisierung auf der Website

**Comment by weliveindetail** [comment]
War auch Thema im Übersetzungstask https://github.com/ImmunHelden/ImmunHelden.de/issues/48

**Comment by weliveindetail** [comment]
Hey aber das könnten wir trotzdem offen lassen. Wollte nur den Zusammenhang deutlich machen. Denn bevor es übersetzt wird: Was ist denn der aktuelle Forschungsstand.

**Comment by weliveindetail** [comment]
Hey aber das könnten wir trotzdem offen lassen. Wollte nur den Zusammenhang deutlich machen. Denn bevor es übersetzt wird: Was ist denn der aktuelle Forschungsstand?

**Comment by weliveindetail** [comment]
Ich versuch aktuellen Entwicklungen auf Twitter zu sammeln: https://twitter.com/ImmunHelden
Das müsste man mal zusammenfassen.

**Comment by ImmunHeldin-CE** [comment]
Neuer Aufschlag FAQs (müssten dringend überarbeitet werden, was die Infos zur Immunität angeht): https://drive.google.com/file/d/1M-pNHapokqsXi2fR8VpPv6svOnNxIUF1/view?usp=sharing

**Comment by weliveindetail** [comment]
Wenn die Fragen und Antworten ausgearbeitet sind gebt mir gern Bescheid. Ich kann es hoffentlich diese Woche online bringen.

**Comment by ImmunHeldin-CE** [comment]
> Wenn die Fragen und Antworten ausgearbeitet sind gebt mir gern Bescheid. Ich kann es hoffentlich diese Woche online bringen.

Saskia hat am Donnerstag eine Klausur, am Freitag machen wir weiter, über das WE wird es dann hoffentlich fertig.

**Comment by weliveindetail** [comment]
Vielleicht eine gute Quelle: https://www.aerzteblatt.de/nachrichten/112734/COVID-19-Fast-alle-Patienten-mit-bestaetigter-Erkrankung-entwickeln-eine-Immunantwort

>Fast alle rekonvaleszenten Patienten, die sich nach einer dokumentierten COVID-19-Erkrankung einer Klinik in New York als potenzielle Plasmaspender angeboten hatten, waren Antikörper-positiv. Bei vielen waren jedoch weiterhin (bis zu 28 Tage) Virusgene in den Abstrichen nachweisbar. 

> dass „über 99 %“ der Patienten nach einer COVID-19-Erkrankung Antikörper gegen das Virus bilden.

> Um sicher zu gehen, müsste die Infektiosität an Zellkulturen überprüft werden, wo es nach der Infektion durch die Viren zum Zelluntergang kommt

**Comment by ImmunHeldin-CE** [comment]
Sagt gern Bescheid, wenn euch weitere Fragen einfallen!

**Comment by DominikGolle** [comment]
@weliveindetail: Derzeit sind die FAQs nur im Text unter "Häufige Fragen" verlinkt, oder? 
Ich fände es gut, wenn wir noch prominenter und an mehr Stellen darauf verlinken. Zum Beispiel direkt die Überschrift "Häufige Fragen" und/oder im Footer.

**Comment by weliveindetail** [comment]
Für Feedback heute Abend: https://immunhelden.de/faq.html

**Comment by weliveindetail** [comment]
Hab ich letzte Woche eingebaut mit https://github.com/ImmunHelden/ImmunHelden.de/commit/d5c43e749ec73d6eb7a5bef571906536265e55d8 und https://github.com/ImmunHelden/ImmunHelden.de/commit/7b0448872628bb21801b99acf962715edb93cede

Gibt es noch etwas zu korrigieren oder zu tun was die Formatierung angeht? Hier ist das Markdown dafür: https://github.com/ImmunHelden/ImmunHelden.de/blob/markdown/faq/faq.md

**Comment by ImmunHeldin-CE** [comment]
Die Quellen sollten wahrscheinlich verlinkt und im Text nur in Kurzform zitiert werden, sonst ist das zu sperrig. Können wir ja wieder als Gemeinschaftsaufgabe im FAQ-Team angehen? :)

**Comment by weliveindetail** [comment]
Fix mobile view + alle Antworten anfangs ausblenden

**Comment by weliveindetail** [comment]
Zum Editieren des Markdown für die FAQ müsst ihr dem Link folgen, auf den kleinen Stift drücken, Änderungen machen und am Ende auf `Commit changes` klicken: https://github.com/ImmunHelden/ImmunHelden.de/blob/markdown/faq/faq.md

* Ihr könnt `Update faq.md` als Kommentar beibehalten oder selbst einen eingeben
* Bei der Auswahl darunter `Commit directly to the markdown branch.` bitte beibehalten.

Eine Einführung zur Syntax gibt's hier: https://guides.github.com/features/mastering-markdown/

Es funktioniert genauso wie in diesem Editor hier, nur dass der für manche Kommandos schon Shortcuts anbietet, z.B.: wenn ihr Text selektiert und oben auf **B** drückt, dann erscheinen links und rechts von der Selektion je zwei Sternchen. Das ist Markdown Syntax für Bold.

Beim Editieren des `faq.md` Dokuments gibt's diese Unterstützung noch nicht. Dort muss man die Sternchen also selbst eintippen. Zwei weitere wichtige Kommandos sind:

* \# (Rauten) für Überschriften (\## für einen Unterpunkt, \### für einen Unter-Unter-Punkt, usw.)
* Links gehen so: `[link zu ImmunHelden](https://immunhelden.de)`

Schreibt mir auf Slack, wenn etwas nicht klappt. Danke!

**Comment by weliveindetail** [comment]
Seit https://github.com/ImmunHelden/ImmunHelden.de/commit/edaf9451d028692f5dc5c0a50e75cc39c45f7449 sind Antworten initial zugeklappt. Sie klappen auf wenn nötig (aktuell via Permalink oder Klick). Die Permalinks muss ich doch nochmal anfassen. Im Falle von Umlauten und Sonderzeichen funktioniert das automatische Aufklappen leider nicht.. 🙁

**Comment by weliveindetail** [comment]
Seit https://github.com/ImmunHelden/ImmunHelden.de/commit/fe63cbbe343dd89d1e5988d07d64de00ad9da97c sind die Permalinks safe und können jetzt sorgenfrei weitergegeben werden, solange wir die Fragen nicht umformulieren 😄

**Comment by weliveindetail** [comment]
Zum Layout der FAQ auf Mobile: der Footer war kaputt https://github.com/ImmunHelden/ImmunHelden.de/commit/1aaa5163494a534ec29e980c5b5dacb9446513c0 und das Wort Rekonvaleszentenplasmaspende zu lang https://github.com/ImmunHelden/ImmunHelden.de/commit/5134297e271bf8b21ae3d7614f180b79bb2612c0

**Comment by weliveindetail** [comment]
TODO ist jetzt noch, die Links in den Text einzuarbeiten, siehe mein Kommentar hier: https://github.com/ImmunHelden/ImmunHelden.de/issues/51#issuecomment-644312890

**Comment by vikiarn** [comment]
Hier meine Vorschläge - grundsätzlich ist es schon viel übersichtlicher mit den eingeklappten Fragen!
[Häufige Fragen_Änderungsvorschläge.docx](https://github.com/ImmunHelden/ImmunHelden.de/files/4791847/Haufige.Fragen_Anderungsvorschlage.docx)

**Comment by weliveindetail** [comment]
> Hier meine Vorschläge

@vikiarn Mir fehlt hier ein bisschen der vorher-nachher Vergleich. Also was hat sich eigentlich geändert? (Oder liegt es daran dass ich kein Word hab und es falsch angezeigt wird?)

Wir könnten solche Änderungen auch direkt im Markdown File machen: https://github.com/ImmunHelden/ImmunHelden.de/blob/markdown/faq/faq.md Dort sieht man [in der History](https://github.com/ImmunHelden/ImmunHelden.de/commits/markdown/faq/faq.md) was sich mit jedem Commit geändert hat.

Ich sehe zwei Kommentare, die vielleicht am besten von @ImmunHeldin-CE und @koolss82 beantwortet werden können (Details siehe Dokument):

> Sollen wir hier auch Prävalenz mit aufnehmen? (bei Begriffe “Sensitivität” und “Spezifität”)

> Ich würde diese Fragen als erste Kategorie nennen, da unsere Webseite gerade darauf den Fokus legt. Wir könnten diesen Teil ggf. auch wie vorgeschlagen in zwei Unterkategorien teilen.

**Comment by ImmunHeldin-CE** [comment]
> Sollen wir hier auch Prävalenz mit aufnehmen? (bei Begriffe “Sensitivität” und “Spezifität”)

Meinetwegen gern, aber eher als zusätzliche Frage und nicht im Kontext "Sicherheit von Tests" @koolss82 was meinst Du? 

Ich würde diese Fragen als erste Kategorie nennen, da unsere Webseite gerade darauf den Fokus legt. Wir könnten diesen Teil ggf. auch wie vorgeschlagen in zwei Unterkategorien teilen.

Fände ich beides gut :)

**Comment by vikiarn** [comment]
Hier ist ein Ausschnitt von einem Artikel, weswegen ich auf die Prävalenz gekommen bin:

Das Problem: Zwar werben die Hersteller damit, dass diese Tests sehr zuverlässig seien, wirklich sichere Aussagen über eine überstandene Corona-Infektion können sie dennoch nicht geben. Um den Nutzen eines medizinischen Tests zu bewerten, gibt es drei Parameter. Die Sensitivität gibt an, wie viele Kranke richtig erkannt werden. Die Spezifität hingegen sagt aus, wie viele Gesunde korrekterweise ein negatives Testergebnis bekommen. Ganz entscheidend ist zudem die Prävalenz. Sie gibt den Anteil von Erkrankten an einer Bevölkerung an. Dabei gilt: Je seltener eine Krankheit ist, desto problematischer ist eine niedrige Spezifität.

https://www.zeit.de/wissen/2020-06/corona-tests-antikoeper-covid-19-infektion-faq

@weliveindetail hier nochmal die Änderungen Gelb-markiert gekennzeichnet.
[Haufige.Fragen_Anderungsvorschlage_Änderungen gekenn.docx](https://github.com/ImmunHelden/ImmunHelden.de/files/4799248/Haufige.Fragen_Anderungsvorschlage_Anderungen.gekenn.docx)

**Comment by weliveindetail** [comment]
Die Aufteilung der Blutplasma-FAQ hab ich bisher nicht gemacht, weil wir dann wieder darüber nachdenken müssen wie es am Ende auf der Webseite aussieht... Würde damit gern warten, bis wir das neue Design einbauen.

Zur Prävalenz: Bitte konkrete Änderung vorschlagen oder direkt selbst einbauen (das ist echt nicht schwer und wenn etwas schief geht kann ich jederzeit alles wiederherstellen!)

**Comment by ImmunHeldin-CE** [comment]
> Hier ist ein Ausschnitt von einem Artikel, weswegen ich auf die Prävalenz gekommen bin:
> 
> Das Problem: Zwar werben die Hersteller damit, dass diese Tests sehr zuverlässig seien, wirklich sichere Aussagen über eine überstandene Corona-Infektion können sie dennoch nicht geben. Um den Nutzen eines medizinischen Tests zu bewerten, gibt es drei Parameter. Die Sensitivität gibt an, wie viele Kranke richtig erkannt werden. Die Spezifität hingegen sagt aus, wie viele Gesunde korrekterweise ein negatives Testergebnis bekommen. Ganz entscheidend ist zudem die Prävalenz. Sie gibt den Anteil von Erkrankten an einer Bevölkerung an. Dabei gilt: Je seltener eine Krankheit ist, desto problematischer ist eine niedrige Spezifität.
> 
> https://www.zeit.de/wissen/2020-06/corona-tests-antikoeper-covid-19-infektion-faq
> 
> @weliveindetail hier nochmal die Änderungen Gelb-markiert gekennzeichnet.
> [Haufige.Fragen_Anderungsvorschlage_Änderungen gekenn.docx](https://github.com/ImmunHelden/ImmunHelden.de/files/4799248/Haufige.Fragen_Anderungsvorschlage_Anderungen.gekenn.docx)

Ich finde die Passage in diesem Artikel und die Erklärung des Begriffs der "Prävalenz" im Zusammenhang mit der Testsicherheit nach wie vor komisch. Erstens ist es dem/der Einzelnen doch für das eigene Testergebnis egal, wie viele andere Leute Corona haben und zweitens sagt das auch nichts zur Sicherheit eines Tests aus, sondern nur darüber, wie schlimm es im großen Maßstab ist, wenn die Tests nicht sensitiv und spezifisch genug sind.
Aber Du kannst gern einen Vorschlag machen, wenn Dir die Klärung dieses Begriffs wichtig ist, @vikiarn :)

**Comment by ImmunHeldin-CE** [comment]
Vorschlag Frage und Antwort 1: 
**Ab wann bin ich nach einer akuten Infektion nicht mehr ansteckend?** 
Wie lange eine Person ansteckend ist, lässt sich nicht pauschal sagen und hängt davon ab, wie schwer sie erkrankt ist (BZgA: https://www.infektionsschutz.de/coronavirus-alt/fragen-und-antworten/ansteckung-und-uebertragung.html). Zur Infektiosität kommen die bisherigen Studien zu unterschiedlichen Ergebnissen (RKI: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Steckbrief.html#doc13776792bodyText9), wobei praktisch angenommen wird, dass man Andere bis maximal 14 Tage nach Symptombeginn anstecken kann. 
Aus einer häuslichen Quarantäne wird man daher vorsichtshalber frühestens 14 Tage nach Symptombeginn und 48 Stunden nach Symptomfreiheit entlassen (RKI: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Entlassmanagement.html#doc13671260bodyText2).

**Comment by weliveindetail** [comment]
Änderungen übernommen und deployt. Wenn wir Prävalenz noch aufnehmen wollen, dann bitte neues Ticket dafür.
