### ISSUE TITLE
Hilfsdienste für Beta-Phase anschreiben (Unterstützung von Senior:innen)

### ISSUE THREAD

**Issue by ImmunHeldin-CE** [ImmunHelden/ImmunHelden.de#53]
DRK
Caritas
Essen auf Rädern

**Comment by weliveindetail** [comment]
Antwort zu unserem ProjectTogether Gesuch von heute Morgen 🎉 

**EXP_Juliane_Amlacher**
Hallo Stefan, bin eben die Gesuche durchgegangen und habe Euren Gesuch von vor 16 Tagen gesehen. Sofern noch aktuell: Ich kann Euch den direkten Kontakt zum Vorsitzenden und zum Geschäftsführer des Berufsverbands für Altenpflege als auch zum Vorsitzenden des Berufsverbands der Leitungskräfte der Behinderten- und Altenhilfe vermitteln. Wenn noch Bedarf besteht, meld Dich gern. Viele Grüße, Juliane

**INITL_Stefan_Gränitz**
Hallo Juliane, das wäre sehr hilfreich für uns! Danke! Wir schauen im Team, wer sich auf unserer Seite um die Kommunikation dafür kümmern möchte und melden uns dann möglichst bald zurück.

**Comment by weliveindetail** [comment]
Die Liste der WirVsVirus Paten könnte auch eine gute Grundlage sein für Kontakte: https://docs.google.com/document/d/1SEQNtebIGRDXLegLx6gjhOjwKaZy4L70qoSuEmK973I/edit

Ich bin bereits in Kontakt mit Hannes Jähnert (DRK), Max Neufeind (BMF/BMAS) und Jan Boaskamp (JOBLINGE, 10drei). Gab bis jetzt schon sehr guten Input!

**Comment by ImmunHeldin-CE** [comment]
Juliane habe ich kontaktiert, das klingt schonmal super! 
Von den Paten werde ich mal Mathias Hamann kontaktieren, er leitet ein Flüchtlingszentrum - das könnte m.E. auch eine gute Einsatzmöglichkeit für ImmunHeld:innen sein. Außerdem Hans-Josef-Vogel, der uns evtl. Kontakte in die Verwaltung geben könnte. 
Vielleicht wenn wir etwas weiter sind, sollten wir auch Claudia Röttger anschreiben, sie ist Chefredakteurin des Senioren Ratgebers.
Und Marion Föster könnte auch interessant sein, sie leitet die Unternehmenskommunikation der medizinsichen Gesellschaften in Hamburg.

**Comment by ImmunHeldin-CE** [comment]
Könnte das hier jemand übernehmen? 

Nach eingeholtem Einverständnis leite ich Dir hiermit die Kontaktdaten des Vorsitzenden des Deutschen Berufsverbands für Altenpflege (DBVA), Bodo Keissner-Hesse, sowie die des Geschäftsführers des DBVAs, Dr. Thomas Kunczik, weiter:

Bodo Keißner-Hesse

Bildungsakademie für Gesundheits- und Sozialberufe
des Kreises Mettmann GmbH
Jubiläumsplatz 19
40822 Mettmann

E-Mail keissner@bildungsakademie-mettmann.de
Tel. 02104/1418-18
Fax 02104/1418-22
www.bildungsakademie-mettmann.de

Dr. Thomas Kunczik
Geschäftsführer

Deutscher Berufsverband für Altenpflege e.V.
Bundesgeschäftsstelle

Postfach 1366
51657 Wiehl

E-Mail: kunczik@dbva.de
Tel.: 02262 / 999 99 14

**Comment by Highkovic** [comment]
> Könnte das hier jemand übernehmen?
> 
> Nach eingeholtem Einverständnis leite ich Dir hiermit die Kontaktdaten des Vorsitzenden des Deutschen Berufsverbands für Altenpflege (DBVA), Bodo Keissner-Hesse, sowie die des Geschäftsführers des DBVAs, Dr. Thomas Kunczik, weiter:
> 
> Bodo Keißner-Hesse
> 
> Bildungsakademie für Gesundheits- und Sozialberufe
> des Kreises Mettmann GmbH
> Jubiläumsplatz 19
> 40822 Mettmann
> 
> E-Mail [keissner@bildungsakademie-mettmann.de](mailto:keissner@bildungsakademie-mettmann.de)
> Tel. 02104/1418-18
> Fax 02104/1418-22
> [www.bildungsakademie-mettmann.de](http://www.bildungsakademie-mettmann.de)
> 
> Dr. Thomas Kunczik
> Geschäftsführer
> 
> Deutscher Berufsverband für Altenpflege e.V.
> Bundesgeschäftsstelle
> 
> Postfach 1366
> 51657 Wiehl
> 
> E-Mail: [kunczik@dbva.de](mailto:kunczik@dbva.de)
> Tel.: 02262 / 999 99 14

Übernehme ich gerne! Textvorlage für die Kontaktmail gibt es vermutlich noch nicht, oder? Dann entwerfe ich sie und teile sie mit Euch auch für alle künftigen Organisationen to come

**Comment by ImmunHeldin-CE** [comment]
Die Hamburger Tafel hatte ich so angeschrieben, allerdings nicht erfolgreich, also pass es gern an : 

Liebes Tafel-Team,

wir von Immunhelden.de möchten in der Coronakrise risikoarmes Engagement möglich machen.
Unsere Website verbindet hilfesuchende Personen oder Organisationen mit Immunheld:innen, d.h. Freiwilligen, die bereits von COVID-19 genesen und somit nach dem aktuellen Forschungsstand höchstwahrscheinlich immun gegen das Coronavirus SARS-CoV-2 sind und auch andere nicht mehr anstecken können.

Wir haben auf Ihrer Website gesehen, dass die Hamburger Tafel noch ehrenamtliche Helfer:innen in der Coronakrise sucht und würden Sie sehr gern (und natürlich kostenlos) mit unseren Immunheld:innen in Verbindung bringen.
Die Registrierung als hilfesuchende Organisation auf unserer Website ist ganz einfach - bei Fragen sind wir jederzeit über das Formular oder tagsüber auch telefonisch erreichbar.

Was wir davon haben? Unser ehrenamtlich geführtes und im Rahmen des Solution Enabler Programms von der Bundesregierung gefördertes Projekt (https://wirvsvirushackathon.org/) befindet sich noch in der Beta-Phase. Die Hamburger Tafel würde somit zu den ersten Organisationen gehören, die sich bei uns registrieren und unseren Frewilligen die Möglichkeit bieten, sich sinnvoll zu engagieren.

Wir freuen uns sehr, wenn wir gemeinsam mit Ihnen Helfer:innen für die Hamburger Tafel finden und zugleich dazu beitragen können, die Ausbreitung des Coronavirus zu verlangsamen!
 
Viele Grüße

Christine Eichkorn und das Immunhelden-Team

Tel. 0176-56894113

**Comment by Highkovic** [comment]
Tafel Deutschland e.V. ist kontaktiert, Deutscher Berufsverband für Altenpflege ebenfalls, Mails gingen in cc an team@immunhelden.de

**Comment by weliveindetail** [comment]
Dr. Joerg Traub hat ein spannendes Vernetzungsangebot für uns:

>Bzgl. Immunhelden würde ich gerne den Kontakt zwischen dem Team und meiner Kollegin Wallner, Raphaela <raphaela.wallner@bayern-innovativ.de> herstellen.
>
>Raphaela betreut das PPZ Projekt von unserer Seite (https://www.ppz-nuernberg.de/) Und organisiert gerade den Pflege „Clusterkonferenz Zukunft der Pflege – kann Pflege digital“ im September und hat ein gutes Netzwerk Richtung Pflegeheime durch diesen Cluster. Das Team darf sich direkt bei Ihr melden, sie weiss Bescheid."

@ImmunHeldin-CE das klingt gut oder? Wer kann den Kontakt herstellen?

**Comment by ImmunHeldin-CE** [comment]
Das klingt super! Ich schreibe ihr gleich mal!
Wer ist denn Dr. Joerg Traub?

**Comment by weliveindetail** [comment]
> Wer ist denn Dr. Joerg Traub

Er ist wohl einer der Paten. Vanessa Gstettenbauer schrieb eben noch, dass sie einen Stakeholder Call im Bereich Pflege Anfang nächster Woche haben. Franziska Gebhard wird sich bei uns melden.

**Comment by ImmunHeldin-CE** [comment]
Wow, echt klasse! Mail ist verschickt, warten wir mal ab :)

**Comment by ImmunHeldin-CE** [comment]
Mails an Caritas Berlin und DRK Hamburg-Eimsbüttel sind rausgeschickt, telefonische Rückfrage am Montag.

**Comment by ImmunHeldin-CE** [comment]
[Mail Raphaela Wallner.pdf](https://github.com/ImmunHelden/ImmunHelden.de/files/4678115/Mail.Raphaela.Wallner.pdf)
Rückmeldung Raphaela Wallner: Abwarten...

**Comment by ImmunHeldin-CE** [comment]
ASB-Initiative aus Hamburg-Harburg "In guter Gesellschaft", die Senior:innenbesuche organisiert, kontaktiert (25.05.). Tel. Rückfrage am 29.05.

**Comment by Highkovic** [comment]
> Tafel Deutschland e.V. ist kontaktiert, Deutscher Berufsverband für Altenpflege ebenfalls, Mails gingen in cc an [team@immunhelden.de](mailto:team@immunhelden.de)

Heute telefonisch beim BVDA nachgefasst: Ist ein Thema für den Vorstand und nicht für Herrn Dr. Kunczik, Mail wird intern weitergeleitet.

**Comment by ImmunHeldin-CE** [comment]
Stand kontaktierte Organisation (@Highkovic könntest du deine evtl. ergänzen?): https://drive.google.com/file/d/1w8KGnsS_yXX84_jKSkYjxWs-XYpNTORM/view?usp=sharing

**Comment by Highkovic** [comment]
Weitere Anlaufstelle für Kooperationen:  die Kassenärztliche Vereinigung

**Comment by Highkovic** [comment]
> > Tafel Deutschland e.V. ist kontaktiert, Deutscher Berufsverband für Altenpflege ebenfalls, Mails gingen in cc an [team@immunhelden.de](mailto:team@immunhelden.de)
> 
> Heute telefonisch beim BVDA nachgefasst: Ist ein Thema für den Vorstand und nicht für Herrn Dr. Kunczik, Mail wird intern weitergeleitet.

BVDA nachgefasst per Mail am 12. Juni

**Comment by weliveindetail** [comment]
Das ist jetzt Teil von #127 oder? Vielleicht können wir das zusammenfassen?
