### ISSUE TITLE
Seite "Wer wir sind" zu Website hinzufügen

### ISSUE THREAD

**Issue by Highkovic** [ImmunHelden/ImmunHelden.de#57]
Vorstellung des Teams hinter ImmunHelden - macht uns anfassbarer, vertrauenswürdiger und persönlicher. 

Vorschlag: Foto und kurzer Steckbrief (Rolle bei Immun:Helden) von jedem

**Comment by weliveindetail** [comment]
Hier nochmal das Doc: https://docs.google.com/document/d/1kpEABj7wT-8HkZiCTglvEEXXjVlLkxN5XHciJmS4S_A/edit?usp=sharing

Sollen wir ein Foto von jeder:m hinzufügen?

**Comment by Highkovic** [comment]
Bis Freitag liefert jeder Inhalt - ich poste den Aufruf nochmals auf Slack

**Comment by weliveindetail** [comment]
> Bis Freitag liefert jeder Inhalt - ich poste den Aufruf nochmals auf Slack

Aber zack zack! 😆 Hier ist ein erster Draft: https://immunhelden.de/about/
Mangels professionellem Design eben erstmal ohne viel Design 😄

**Comment by weliveindetail** [comment]
Gibt es Wünsche was die Reihenfolge angeht? (Wenn es nicht so viel Aufwand wäre hätt' ich es glatt randomisiert. Naja wär wohl eher nice-to-have.)

**Comment by DominikGolle** [comment]
Wie wärs mit einer kreisförmigen Anordnung? Das würde auch zur Soziokratie passen

**Comment by weliveindetail** [comment]
> Wie wärs mit einer kreisförmigen Anordnung? Das würde auch zur Soziokratie passen

Gute Idee. In einem finalen Design gern. Unter der Prämisse dass ich alles nochmal umbauen muss, aktuell leider auch etwas zu viel Aufwand. (Es sei denn es findet sich ein:e Freiwillige:r?)

**Comment by weliveindetail** [comment]
Hm. "Wer wir sind" könnt neben dem "ImmunHelden" Logo auch zu Verwechslungen zwiscvhen uns und unseren Usern führen. Sollen wir stattdessen etwas schreiben wie "Team" (oder ähnlich). Habs in meinem letzten Commit mal probiert..

**Comment by weliveindetail** [comment]
Jetzt mit Logo in groß, Mobile View und so:

<img width="1148" alt="Screenshot 2020-06-06 at 09 48 36" src="https://user-images.githubusercontent.com/7307454/83939169-fb5b5f80-a7da-11ea-878e-57adb8d418ae.png">

Will jemand die Hackathon-Story als Intro formulieren? Statt des "Lorem ipsum" 🙂

**Comment by weliveindetail** [comment]
<img alt="Screenshot 2020-06-08 at 17 06 15" src="https://user-images.githubusercontent.com/7307454/84046481-758e0e80-a9aa-11ea-8680-c11ca7cec0a9.png">

Der Text zur Teamfindung ist noch TODO und unsere beiden Fotos @ImmunHeldin-CE.
Ansonsten (finde ich) geht das erstmal so. https://immunhelden.de/about/
