### ISSUE TITLE
Datenschutzseite fertigstellen

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#6]
https://immunhelden.de/datenschutz.html ist noch nicht fertig formatiert. Der Anfang ist gemacht und demonstriert wie es funktioniert. Das könnte also einfach weitergeführt werden:
https://github.com/weliveindetail/ImmunHelden.de/blob/deployed/website/datenschutz.html

Die HTML Datei herunterladen (Rechtsklick auf `Raw` und dann `Save as..`), mit einem Texteditor öffnen und bearbeiten. Im Browser gucken wie es aussieht. Das Ergebnis gern an mich schicken, dann check ich es ein.

Alternativ hatten wir die Originalfassung im Nachhinein auch als HTML exportiert. Man könnte auch den Code nehmen und an unseren Webseiten Style anpassen -- könnte am Ende aber auch mehr Aufwand sein:
https://wirvsvirus.slack.com/files/U010GR63SKZ/F010NBDTESX/datenschutzerklaerung_immunhelden_html.docx

**Comment by weliveindetail** [comment]
Deployed: https://immunhelden.de/datenschutz.html

@DominikGolle Sieht ok aus? Könntest du bei dir testen, dass der E-Mail Kontakt funktioniert? Danke

**Comment by DominikGolle** [comment]
Ja, und beeindruckend lang, dafür, dass wir so wenig Daten verarbeiten :D
Ich gehe davon aus, dass das noch deutlich kürzer wird, wenn wir die Datenschutzberatung einschalten.

Wenn ich auf "E-Mail schreiben" klicke, öffnet sich mein Client und will an "immunhelden@posteo.de" - alles gut also, oder? 

--
 Dominik Golle
 dominikgolle@fastmail.com
 Public Key ID: A7C6A5DF (RSA 4096 bit)



Am Mi, 22. Apr 2020, um 17:23, schrieb Stefan Gränitz:

**Comment by weliveindetail** [comment]
Ja genau so sollte es funktionieren. Danke
