### ISSUE TITLE
MitarbeiterInnen für das Projekt bzw. die GbR suchen

### ISSUE THREAD

**Issue by ImmunHeldin-CE** [ImmunHelden/ImmunHelden.de#60]
Erster Vorschlag: 
Saskia Kools, kluge, nette und sehr zuverlässige Medizinstudentin an der Ruhr-Uni Bochum, arbeitet in der dortigen Uniklinik, die selbst Antikörpertests durchführt. Sie könnte unsere medizinischen Infos updaten, bzw. die FAQ, da wir ja umfangreich aufklären wollen, Partnerorganisationen anschreiben und sicherlich auch bei der Kommunikation (social media, outreach) mitarbeiten.

**Comment by weliveindetail** [comment]
Super! Können wir nächste Woche mal in einem Zoom Call zusammen mit ihr die FAQ anschauen?

**Comment by ImmunHeldin-CE** [comment]
Bestimmt, aber wir müssten die GbR-Frage ja früh klären. Die Einreichungsfrist unseres Förderantrags beim DLR ist der 15.05. Davor muss die GbR stehen, wir müssen das Budget (200%) ausschöpfen können und alle, die nicht selbstständig sind oder studieren müssen Bescheinigungen Ihrer Arbeitgeber vorliegen haben.

**Comment by weliveindetail** [comment]
Ok, welchen Tag würdest du vorschlagen?

**Comment by ImmunHeldin-CE** [comment]
Würd vorschlagen, wir reden über neue Teammitglieder, ihre Kompetenzen, Kapazitäten usw. direkt nachdem wir klar bestimmt haben, wer von uns Teil der GbR wird, wer offiziell wie viel Budget erhalten kann (also in Abstimmung mit dem Arbeitgeber offiziell wie viel Prozent Kapa hat) und ob und zu welchen Prozentsatz wir neue Mitglieder in die GbR aufnehmen. Also nach einem Call zur GbR-Gründung und möglichst schnell, oder wie seht ihr das?

**Comment by weliveindetail** [comment]
Jap dachte nur, wir können parallel dazu schon mal einen Termin finden um uns mit ihr zu unterhalten. Der sollte möglichst nach unserem GbR Call sein.
