### ISSUE TITLE
Flow to ask for help

### ISSUE THREAD

**Issue by c0un7-z3r0** [ImmunHelden/ImmunHelden.de#66]
## STEP 1

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/6809130/81194133-908ced80-8fbc-11ea-958c-2bd5f9c373b4.png">

## Step 2

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/6809130/81194958-84edf680-8fbd-11ea-869c-b44d3a3e92a4.png">

## Step 3

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/6809130/81195016-97683000-8fbd-11ea-9589-8e7ea7b8ed94.png">

**Comment by weliveindetail** [comment]
`Step 1` could be split into actions:
* Sign-Up: fields from Ansprechpartner -> submit creates accounts in Firebase backend #45 -> forward to `Step 3`
* Create request: fields from "Wo wird Hilfe gebraucht" -> submit creates new entry for account -> forward to `Step 2`

**Comment by weliveindetail** [comment]
We could have another page for Login. For now we could forward to the above "Create request" page on successful login. As @roblen45 can help us with the implementation of accounts in the backend now, it seems to be a good task to begin with.

What do you think?

**Comment by weliveindetail** [comment]
Done with https://github.com/ImmunHelden/ImmunHelden.de/issues/45
