### ISSUE TITLE
Definiere Milestones

### ISSUE THREAD

**Issue by c0un7-z3r0** [ImmunHelden/ImmunHelden.de#73]
Um klare Ziele zu haben und uns voranzubringen sollten wir Milestones (Ziele) definieren und bis wann wir diese erreichen wollen.

**Comment by weliveindetail** [comment]
Milestone Vodafone: 29.05.
* Erklärfilm #32 
* E-Mail Benachrichtigungen #1 
* Social Media Previews #8 
* Primitive Bearbeitungsmöglichkeit für ImmunHeld:innen Daten #4
* Frontend mit neuem Design? (klingt ehrgeizig)

☝️ Gern editieren und die Liste weiterführen.

**Comment by weliveindetail** [comment]
Milestone Plasmaspende live: ASAP

* Blutspendeeinrichtungen verifizieren #74 
* Provisorischer Umbau der Webseite für Plasmaspende #75
* Update Mail zu Angeboten für Plasmaspende ready #76 
* Datenschutz Vorschläge umsetzen #62 
* Forschungsstand aktualisieren #51

☝️ Gern editieren und die Liste weiterführen.

**Comment by weliveindetail** [comment]
Milestone Onboarding Organisationen: 22.05.

* Accounts und Login für Partner #45 
* Primitives erstellen und bearbeiten von Angeboten #66 

☝️ Gern editieren und die Liste weiterführen.

**Comment by weliveindetail** [comment]
https://github.com/ImmunHelden/ImmunHelden.de/milestones
