### ISSUE TITLE
blutspenden.de Locations verifizieren

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#74]
Nachdem wir in https://github.com/ImmunHelden/ImmunHelden.de/issues/11 nun eine große Zahl von [Spendeeinrichtungen auf die Map](https://immunhelden.github.io/WirVsVirusMap/plasma.html) gebracht haben, wäre es nun gut einige Mindestanforderungen für sie zu verifizieren, also z.B. dass sie tatsächlich existieren, die Adresse/Position stimmt und ihre die Webseite erreichbar ist.

**Comment by DominikGolle** [comment]
Hier kommentieren, welches Bundesland man gerade bearbeitet

- Schleswig-Holstein, Hamburg und Bremen sind fertig. Änderungen wie unten gepostet kommentiert (12.05., 12:49, Sonja). // Mecklenburg-Vorpommern, Niedersachsen ist fertig. Änderungen wie unten gepostet kommentiert (13.05., 10:50, Sonja)

- Hinweis - auch wenn es kein Bundesland ist: Die CSL Plasma Standorte sind alle bereits korrigiert, auch wenn das in der Liste+Map noch nicht sichtbar ist. (13.05.,10:15, Sonja)

**Comment by weliveindetail** [comment]
Wenn ihr Fehler findet oder Vorschläge habt für Verbesserungen, wäre es toll wenn ihr sie hier markieren könnt:
https://github.com/weliveindetail/WirVsVirusMap/commit/7862f956bb768339df8797686fd040d6fdeb411d

**Comment by SonjaJDoering** [comment]
Hier kommentieren, wenn einem zufällig fehlende Blutspendedienste (Plasma COVID-19) auffallen:
- Hannover: Blutspendedienst Medizinische Hochschule Hannover, RKP-Spende@mh-hannover.de, Carl-Neuberg-Straße 1, 30625 Hannover, +49 800 532 5325, https://www.mhh.de/institute-zentren-forschungseinrichtungen/institut-fuer-transfusionsmedizin/blutspende/die-erste-blutspende-1

- Regensburg: Universitätsklinikum Regensburg: https://www.ukr.de/service/aktuelles/06312.php, Tel. +49 941 944-5000, Franz-Josef-Strauß-Allee 11, 93053 Regensburg

**Comment by weliveindetail** [comment]
> fehlende Blutspendedienste

@SonjaJDoering Nehmen sie explizit Spenden von COVID-19 Genesenen entgegen?

**Comment by SonjaJDoering** [comment]
@weliveindetail Guter Punkt. Habe es jetzt detailliert recherchiert.
Ganz richtig ist bei Asklepios: Die entnehmen Covid-19-Plasma nur in Wandsbek (Quarree) und an keinem ihrer ganzen anderen Standorte. Soll ich die anderen in der Liste dann alle markieren mit " bitte löschen". 
Und beim Klinikum Bremerhaven finde ich dazu nichts.  
Eintrag oben ist angepasst.

**Comment by weliveindetail** [comment]
Zusätzliche Locations können wir erstmal sammeln (z.B. hier) und später entweder in einer separaten Liste führen oder an blutspenden.de zurück melden. Die Datei die wir jetzt bearbeiten, würde ich gern nur für Locations von blutspenden.de verwenden. Denn das macht es leichter, sie automatisiert auf dem neusten Stand zu halten.

**Comment by weliveindetail** [comment]
Wir haben schon echt viel geschafft. Super! Ich hab die Datenhaltung inzwischen etwas besser strukturiert. Für jede Datenquelle sollte ein separater Branch existieren, damit wir die Historie der Änderungen pro Datensatz verfolgen können und sie sich nicht mit Änderungen in anderen Datensätzen oder dem Code der Karte vermischen.

Die Daten von blutspenden.de (die einzigen die wir bis jetzt haben) finden sich demnach hier:
https://github.com/ImmunHelden/WirVsVirusMap/commits/data/blutspenden.de

Für die nächste Runde von Reviews in diesem Datensatz können wir Korrekturen hier sammeln:
https://github.com/ImmunHelden/WirVsVirusMap/commit/aae97c7fe54f435f2923225f5c7532a48053ac4c

Ich hab es auch extra so vorbereitet, dass es keine roten Zeilen mehr gibt. Dann sollte jeder Eintrag nur einmal auftauchen 🙂 

Toi toi toi 🎉

**Comment by koolss82** [comment]
> Hier kommentieren, welches Bundesland man gerade bearbeitet
> 
> * Schleswig-Holstein, Hamburg und Bremen sind fertig. Änderungen wie unten gepostet kommentiert (12.05., 12:49, Sonja). // Mecklenburg-Vorpommern, Niedersachsen ist fertig. Änderungen wie unten gepostet kommentiert (13.05., 10:50, Sonja)
> - NRW ebenfalls fertig (17.05. 12:30, Saskia)
> * Hinweis - auch wenn es kein Bundesland ist: Die CSL Plasma Standorte sind alle bereits korrigiert, auch wenn das in der Liste+Map noch nicht sichtbar ist. (13.05.,10:15, Sonja)

**Comment by weliveindetail** [comment]
Merci. Die Map aktualisiere ich dann wieder, sobald sich eine größere Anzahl von Korrekturen angesammelt hat. Kurze Zusammenfassung zur Übersicht:

Fertig sind: `Schleswig-Holstein, Hamburg, Bremen, Mecklenburg-Vorpommern, Niedersachsen, NRW`
Noch offen sind: `Baden-Württemberg, Bayern, Berlin, Brandenburg, Hessen, Rheinland-Pfalz, Sachsen, Sachsen-Anhalt, Saarland, Thüringen`

Für das Tracking könnt ihr auch einfach den Namen des Bundeslandes in einem neuen Kommentar hier unten hinzufügen 🙂

**Comment by ImmunHeldin-CE** [comment]
Baden-Württemberg: Korrekturen eingefügt (18.05.)
Saarland: OK (18.05.)
Thüringen: Korrekturen eingefügt (18.05.)

**Comment by weliveindetail** [comment]
Noch offen sind: Bayern, Berlin, Brandenburg, Hessen, Rheinland-Pfalz, Sachsen, Sachsen-Anhalt

**Comment by ImmunHeldin-CE** [comment]
Korrekturen eingefügt für Brandenburg, Sachsen und Berlin. 
Noch offen sind: Bayern, Hessen, Rheinland-Pfalz, Sachsen-Anhalt

**Comment by ImmunHeldin-CE** [comment]
Korrekturen eingefügt für Bayern, Hessen, Rheinland-Pfalz, Sachsen-Anhalt (25.05.)
Jetzt ist nur noch offen, ob die Uni-Blutbank Marburg schon RKP-Spenden annimmt, oder ob das noch in Planung ist (Rückruf am 26.05.)

Allgemeine Zusammenfassung (nicht unbedingt sehr übersichtlich im Kommentarmodus): 

- Alle Standorte von CSL und Octapharma sollten m.E. von der Map gelöscht werden, weil das COVID-19 Plasma dort nicht für besondere Zwecke (ind. Heilversuche und Impfstoff-Forschung), sondern wie immer zur kommerziellen Medikamentenherstellung verwendet wird. Es handelt sich um international agierende Pharma-Unternehmen mit fragwürdigen ethischen Prinzipien. 
- Bei den Haema-Standorten muss man zunächst einen Fragebogen ausfüllen, um RK-Plasma zu spenden, der Link ist für alle Standorte derselbe: https://www.haema.de/blutspendedienst.html
- Auch beim DRK muss ein Formular ausgefüllt werden, hier gibt es mehrere zentrale Websites, eine für Baden-Württemberg und Hessen: https://www.blutspende.de/rkp/, eine für Berlin, Brandenburg, Hamburg, Sachsen und Schleswig-Holstein: https://www.blutspende-nordost.de/rkp/, eine für NRW und das Saarland: https://www.blutspende-nordost.de/rkp/ und eine für Bayern https://www.blutspendedienst.com/ (in Bayern ist die RK-Plasmaspende erst ab dem 03.06. möglich). 
- Bei Plasmavita wird das RK-Plasma je nach Standort unterschiedlich verwendet (siehe Kommentare)

Generell sollten wir darauf hinweis, dass man für eine RK-Plasmaspende auf keinen Fall unangemeldet in ein Blutspendezentrum kommen sollte. 
Um die Standorte zu kompensieren, die wir löschen müssen, sollten wir weitere seriöse Standorte recherchieren.

**Comment by weliveindetail** [comment]
Wow sehr gute Analyse @ImmunHeldin-CE !!

> CSL und Octapharma

Vielleicht können wir heute Abend im Team Meeting klären, welche Anforderungen wir an privatwirtschaftliche Spendezentren setzen wollen und welche Spendezwecke wir unterstützen.

**Comment by ImmunHeldin-CE** [comment]
> Vielleicht können wir heute Abend im Team Meeting klären, welche Anforderungen wir an privatwirtschaftliche Spendezentren setzen wollen und welche Spendezwecke wir unterstützen.

Ja, das wäre super! Und ob wir nur Standorte berücksichtigen wollen, die COVID-19-Plasma zur Therapie von schwer Erkrankten und zur Impfstoff-Forschung verwenden.

**Comment by vikiarn** [comment]
Kommerzielle Anbieter: CSL und Octapharma --> aus ethischer Sicht sollten diese Orgs eher rausgenommen werden; zusätzlich zu Profitorientierung wird auch das Blutplasma nicht für COVID-19 Patient:innen verwendet --> internationale Organisation (Plasma wird nach Spanien geschickt etc.); Votum des Teams: "**Rausnehmen, da sie nicht die Aufgaben übernehmen, die wir bewerben; reine Profitorientierung wäre in Ordnung - allerdings sollten sie das Plasma für die Genesung von COVID-19 Patient:innen verwenden**"

Wir sollten Organisationen finden, die auf unserer Webseite die Daten verwalten wollen; da sollte etwas Überzeugungsarbeit geleistet werden. ggf. mit dem Argument, dass die Karte geteilt werden kann und kostenlose Werbung zu den Plasmaeinrichtungen auf Immunhelden.de - Vorteil für uns: Spendeeinrichtungen aktualisieren ihre Daten kontinuierlich; jetzt Tester zu haben wäre auch gut. 

--> Versuch mit dem BMG in Kontakt zu kommen und Informationen zu eventuell geplanten Kampagnen erhalten; Haema könnte ein guter Partner sein, die auf unserer Webseite ihre Daten aktualisieren

**Comment by weliveindetail** [comment]
Vielen Dank an alle! Ich denke hiermit haben wir unseren ersten Kraftakt gemeistert 💪 😄 
Ich werd die Änderungen sobald wie möglich übernehmen und das Ticket dann schließen, sobald sie online sind!
