### ISSUE TITLE
Provisorischer Umbau der Webseite für Plasmaspende

### ISSUE THREAD

**Issue by DominikGolle** [ImmunHelden/ImmunHelden.de#75]
- Karte Blutspendeeinrichtungen fertig, aber passt noch nicht zum derzeitigen Inhalt der Webseite
- Website relaunch? Anpassungen des Layouts allerdings schwierig

**Comment by weliveindetail** [comment]
Aktueller Draft: https://immunhelden.de/landing-page-new.html

Layout orientiert sich an https://bringandring.de/
Vorteile gegenüber der bisherigen Landing Page:
* Das Grundgerüst der alten Vorlage ist raus, Anpassungen sind daher deutlich leichter.
* Ist und kann noch besser auf Plasmaspende zugeschnitten werden.
* Für das Erklärvideo können wir einfach einen Absatz einfügen.
* Layout passt für Desktop und Mobile.

**Comment by weliveindetail** [comment]
Preview Desktop:
https://user-images.githubusercontent.com/7307454/81862865-a6755200-956a-11ea-983e-4180a62b1a9b.png

Preview Mobile:
https://user-images.githubusercontent.com/7307454/81862889-ac6b3300-956a-11ea-98ec-2ab8be35c859.jpg

**Comment by weliveindetail** [comment]
TODO: Map bei Plasmaspende muss ein Link sein!

**Comment by weliveindetail** [comment]
TODO: Map bei Plasmaspende muss ein Link sein!

**Comment by weliveindetail** [comment]
Deployed:
https://immunhelden.de/
https://immunhelden.de/map.html

**Comment by DominikGolle** [comment]
Derzeit werden beim Klicken auf Links zu Blutspendeneinrichtungen in der Map keine neuen Tabs geöffnet

PS: Ich hab keine Ahnung von github-Netiquette - öffnet man geschlossene issues bei sowas wieder oder legt man eher ein neues issue an?

**Comment by weliveindetail** [comment]
> Derzeit werden beim Klicken auf Links zu Blutspendeneinrichtungen in der Map keine neuen Tabs geöffnet

Good catch! Ist mir gestern auch aufgefallen und habs debugged. Ursache ist das Sandboxing der `iframe`s. Der Einfachheit halber hatte ich die Map von GitHub nur via `iframe` eingebunden. Aber embedding kann eben doch kompliziert sein. Vorübergehend hab ich in https://github.com/ImmunHelden/ImmunHelden.de/commit/90114af6224329d7b89c48cecb89c50155786a24 das sandboxing raus genommen.

Entgegen der Commit-Nachricht fixt das leider noch nicht die Permalinks. Denn die Inhalte der Seitenleiste werden in einen weiteren `iframe` geladen. Von dort ändert der Permalink-Link die Adresse des `parent`, der ist hier nun selbst nur ein `iframe` und entsprechend sieht man die Adresse dann nicht.

Long story short: Ich muss die Map bei uns hosten. Ursprünglich wollte ich das heute machen, aber dann kamen wieder andere Dinge. Morgen!

> öffnet man geschlossene issues bei sowas wieder oder legt man eher ein neues issue an?

Weiß nicht, ich denk von Fall zu Fall unterschiedlich. Hier ists eher ein Nebeneffekt des Umbaus, also hab ich ein neues Ticket angelegt: https://github.com/ImmunHelden/ImmunHelden.de/issues/82
