### ISSUE TITLE
Update Mail an 3 ImmunHeld:innen zu Angeboten für Plasmaspende

### ISSUE THREAD

**Issue by DominikGolle** [ImmunHelden/ImmunHelden.de#76]
Nach dem Website-Update individuelle Email an registrierte ImmunHeld:innen für User Feedback

**Comment by vikiarn** [comment]
Hier mein Vorschlag für die E-Mails: https://docs.google.com/document/d/1J9ftfRZG42KcxwgyUPa9Le4S2Wn-KpLfCzd_P2TDwFw/edit?usp=sharing

**Comment by weliveindetail** [comment]
Hey Viki das klingt super. Ich versuche das noch heute Nachmittag zu reviewen!

**Comment by vikiarn** [comment]
Danke - ich arbeite morgen nicht und habe daher mehr Zeit - und flexibel. Falls es sich heute nicht mehr ausgeht - passt es morgen sicher auch :)

**Comment by weliveindetail** [comment]
Hab endlich angefangen mit meinem Review. Vielleicht können wir versuchen die Texte noch ein bisschen zu kürzen? Für den Fragebogen: die wichtigsten Folien aus dem Themen-Call waren hier https://wirvsvirusenabler.slack.com/archives/C011Q35KKAP/p1589191463003200

**Comment by vikiarn** [comment]
Super danke - habe es mir durchgelesen. Allerdings sind die meisten Hinweise für ein persönliches Interview mit offenen Fragen. Ich mache gerade einen Workshop von IDEO zu Human-centred Design --> da haben wir auch einiger diese Aspekte besprochen. Ggf. könnten wir die User:innen fragen, ob sich auch für ein persönliches Interview zur Verfügung stehen würden. Was meinst du?

**Comment by weliveindetail** [comment]
> die User:innen fragen, ob sich auch für ein persönliches Interview zur Verfügung stehen würden

Ja, super Idee!

Die Webseite ist jetzt langsam soweit, dass wir die Umfrage raus schicken könnten.

**Comment by vikiarn** [comment]
Hat jemand von euch eventuell eine Premium Version von Survey-Monkey? Ansonsten scheitert es leider schon bei der Disqualifizierungsseite - das ist die einzige Frage, die ich für den JF habe.

**Comment by weliveindetail** [comment]
> Hier der Link zu Surveymonkey für unsere Nutzer:innen. Leider dürfen wir in der BASIC Version nur 10 Fragen stellen und keine "Verzweigungslogik" einfügen. Daher ist die Umfrage ein bisschen abgespeckt. Meldet euch gerne, wenn ihr noch Ideen habt oder etwas nicht funktionieren sollte. Danke an alle! https://www.surveymonkey.de/r/Y6KLPXW

* Beim Datenschutz ganz oben muss man den "Ok" Button klicken und dann nochmal "Ja" auswählen?
* In der zweiten Frage ist der Text gedoppelt: `Wie hast du von Immunhelden.de gehört? Wie hast du von Immunhelden.de gehört?`
* `dass` bei 4.: `Gibt es vielleicht etwas, das du dir`
* Mehrere Schritte finde ich toll, aber wenn man bei 7. `Nein` auswählt, kommt man trotzdem zu 8., 9. und 10. Von mir aus geht auch eine Seite.
* Die Reihenfolge in der man die Fragen auf einer Seite beantwortet, kann ich bei mir frei wählen. Dann könnten wir den Datenschutz auch ans Ende setzen (aber ja, wegen mir nicht kritisch).

Wenn wir die Punkte grob korrigieren, können wir das gern so rausschicken. Ich markier dir die  Empfänger gleich in Slack.

**Comment by vikiarn** [comment]
Hallo Stefan, vielen Dank für deine Rückmeldung.
- das mit dem "ok" sollte gelöst worden sein :)
- die zweite Frage habe ich rausgenommen
- ich bin mir ehrlich gesagt ziemlich sicher, dass in diesem Satz das "das" richtig ist, weil es sich auf den "Wunsch (etwas)" im Hauptsatz bezieht
- Ich habe die 7. Frage geändert in "Würdest du Immunhelden.de an deine Freunde und Familie weiterempfehlen?"
- In Bezug auf Reihenfolge etc. kann ich leider nicht viel ändern mit der gratis Version.

Ich schicke die E-Mail gerne raus an unsere Nutzer:innen

**Comment by weliveindetail** [comment]
Oh stimmt, mit dem `das` hast du Recht! Entschuldige bitte 🙂 E-Mail hab ich bekommen, sieht super aus. Morgen raus schicken klingt gut. Danke!!

**Comment by vikiarn** [comment]
Die E-Mails an die mittlerweile 4 User:innen sind raus. Jetzt fehlt dann nur noch die Auswertung der Beantwortungen

**Comment by vikiarn** [comment]
Stand: 5.6.2020: noch keine Beantwortung
