### ISSUE TITLE
CoVerified in Webseite einbinden

### ISSUE THREAD

**Issue by DominikGolle** [ImmunHelden/ImmunHelden.de#77]
WirvsVirus-Projekt: Infobutton zum Einbinden auf Webseiten, über den verfizierter Infos zu Covid19 angezeigt werden: https://coverified.info/
@weliveindetail & @c0un7-z3r0: Was meint ihr dazu?

**Comment by weliveindetail** [comment]
Nice! Leicht einzubauen und schafft evtl. Vertrauen. Was es leider noch nicht gibt, ist eine Möglichkeit nach Stichwörtern (wie z.B. Immunität) oder Sprache (de/en) zu filtern.

**Comment by weliveindetail** [comment]
Vorläufig eingebaut mit https://github.com/ImmunHelden/ImmunHelden.de/pull/79. Farbe anpassen oder etwas anderes ändern können wir gern jederzeit noch.
