### ISSUE TITLE
Webseite: Mission

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#81]
Wie sollen wir unsere Mission auf unserer Webseite präsentieren?

**Comment by weliveindetail** [comment]
Wir sollten dafür eine Sektion einfügen, z.B. so:

<img width="550" alt="Screenshot 2020-05-15 at 17 01 18" src="https://user-images.githubusercontent.com/7307454/82065429-6202c700-96ce-11ea-87fe-1bb1acfef297.png">

**Comment by weliveindetail** [comment]
**Alter Text - Passt er aktuell noch? - Was brauchen wir in den kommenden Wochen?**

Superhelden gibt es nicht? Jede:r denkt nur an sich? Stimmt nicht! Du hast die COVID-19-Erkrankung schon hinter dir und möchtest dich nun gesellschaftlich engagieren? Dann mach mit und werde Immunheld:in!

Wir möchten helfen, für notwendige Dienstleistungen Menschen zu finden, die gegen das neuartige Coronavirus wahrscheinlich immun sind, weil sie die COVID-19-Erkrankung schon hinter sich haben. Brauchst Unterstützung in einem wichtigen Lebensbereich? Dann mach mit und stelle hier eine Anfrage für eine Immunheld:in!

Wenn wir die im System entstehenden Lücken schnell mit Immunen besetzen können, wird die Versorgung der Gesellschaft besser sichergestellt und die Infektionskette gleichzeitig unterbrochen! Zusammen können wir die Virusausbreitung verlangsamen und Risikogruppen schützen.

**Comment by Highkovic** [comment]
_> **Alter Text - Passt er aktuell noch? - Was brauchen wir in den kommenden Wochen?**
> 
> Superhelden gibt es nicht? Jede:r denkt nur an sich? Stimmt nicht! Du hast die COVID-19-Erkrankung schon hinter dir und möchtest dich nun gesellschaftlich engagieren? Dann mach mit und werde Immunheld:in!
> 
> Wir möchten helfen, für notwendige Dienstleistungen Menschen zu finden, die gegen das neuartige Coronavirus wahrscheinlich immun sind, weil sie die COVID-19-Erkrankung schon hinter sich haben. Brauchst Unterstützung in einem wichtigen Lebensbereich? Dann mach mit und stelle hier eine Anfrage für eine Immunheld:in!
> 
> Wenn wir die im System entstehenden Lücken schnell mit Immunen besetzen können, wird die Versorgung der Gesellschaft besser sichergestellt und die Infektionskette gleichzeitig unterbrochen! Zusammen können wir die Virusausbreitung verlangsamen und Risikogruppen schützen._

Wir verbinden von COVI-19 Genesene mit allen, die ihre Unterstützung benötigen! Einfach, direkt, regional - und natürlich datenschützend. Wie das funktionieren kann? Z.B. mit einer Blutplasmaspende, mit der Du als COVID-19-Genesene:r die Rekonvaleszenz schwer Erkrankter unterstützen kannst. Oder Du vollbringst bei einer anderen hilfesuchenden Organisation [mit Deiner Superkraft] eine Heldentat. Du findest mögliche Anlaufstellen auf unserer Map. Und wenn Du Dich registrierst, bleibst Du auch über hinzukommende Einrichtungen und Organisationen auf dem Laufenden.

Suchst Du hingegen Unterstützung durch ImmunHeld:innen, bist Du hier ebenfalls richtig. Denn hier kannst Du für notwendige Dienstleistungen Menschen finden, für die das neuartige Coronavirus wahrscheinlich wahrscheinlich weniger gefährlich ist, weil sie die COVID-19-Erkrankung schon hinter sich haben. Brauchst Du Unterstützung in einem wichtigen Lebensbereich? Dann mach mit und stelle hier eine Anfrage für eine:n Immunheld:in!

**Comment by Highkovic** [comment]
_Und weil der Text von Christine für den Förderantrag in meinen Augen so supertreffend ist, sei er für das Brainstorming auch nochmals hier aufgeführt:_

Mit unserer Website verbinden wir Menschen, die von COVID-19 genesen sind, mit allen, die
ihre Unterstützung benötigen und prägen den Begriff “ImmunHelden”. Genesene sind nach
dem aktuellen Forschungsstand höchstwahrscheinlich für mindestens mehrere Monate immun
und können auch ihre Mitmenschen nicht mit dem Coronavirus Sars-CoV-2 infizieren. Ihr
Einsatz im beruflichen oder ehrenamtlichen Kontext ist daher von unschätzbarem Wert. Je
mehr Immunheld:innen kontaktintensive Aufgaben übernehmen, desto effektiver können
Infektionsketten unterbrochen werden. Bis ein wirksamer Impfstoff für den Großteil der
Bevölkerung zur Verfügung steht, können Immunheld:innen darüber hinaus einen wichtigen
Beitrag zur Erprobung neuer Therapiemöglichkeiten leisten. Aktuell werden sie händeringend
als Blutspender:innen gesucht. Einige COVID-19 Patient:innen können nicht so schnell
Antikörper gegen das Coronavirus Sars-CoV-2 bilden, wodurch es zu lebensbedrohlichen
Erkrankungsverläufen kommen kann. Plasma von Gesundeten könnte ihnen bei der
Überwindung ihrer Krankheit helfen. Der Vermittlung von Möglichkeiten zur
Blutplasmaspende möchten wir in der aktuellen Lage die höchste Priorität auf unserer
Plattform einräumen – und diese letztere so zugleich bekannter machen, „im Feld“ testen und
weiterentwickeln. Unsere ImmunHelden Map macht es Nutzern leicht, Angebote in ihrer Nähe
zu finden und ermöglicht es uns, Angebote aus existierenden Quellen und Datenbanken zu
bündeln. Unser Vermittlungsverfahren schützt die Identität der Immunheld:innen und kommt
ohne Gesundheitsdatenspeicherung aus.

**Comment by weliveindetail** [comment]
In meinem Screenshot hatte ich einfach den alten Einleitungstext benutzt. Im Nachhinein wurde mir klar, dass der auch schon recht lang ist für eine Landing Page. Die beiden Vorschläge hier oben sind klasse für die Langversion. Wie schon mal bemerkt, macht https://bringandring.de es glaub ich gut (auch was die Länge der Texte betrifft).

**Comment by weliveindetail** [comment]
Sollen wir die Langversion auf die "Wer wir sind" Seite #57 packen?

**Comment by Highkovic** [comment]
Wir verbinden von COVI-19 Genesene mit allen, die ihre Unterstützung benötigen! Einfach, direkt, regional - und natürlich datenschützend. Informiere Dich hier über hilfesuchende Organisationen. 
Suchst Du hingegen Unterstützung durch ImmunHeld:innen, kannst Du hier ganz einfach eine Anfrage für eine:n Immunheld:in stellen!

**Comment by weliveindetail** [comment]
Das würde ich dann bei der nächsten Gelegenheit zunächst mal auf unsere Landing Page packen. Die Langversion dann zusammen mit der "Wer wir sind" Seite.
