### ISSUE TITLE
Strategie konkretisieren

### ISSUE THREAD

**Issue by ImmunHeldin-CE** [ImmunHelden/ImmunHelden.de#86]
- Was sind unsere größten (kurz- und mittelfristigen) Herausforderungen?
- Wie gehen wir mit dem Thema Immunität um? Sollen wir unsere Kommunikation (von Genesenen sprechen) ändern oder unsere Strategie (z.B. abwarten, bevor wir hilfesuchende Organisationen als Partnerinnen ansprechen)? Ist die Vermittlung an Plasmaspendezentren ein Zwischenschritt bei unserer Vermittlung von Ehrenamt / Arbeit oder ein paralleler Schritt bzw. Schwerpunkt? 
- Was sind unsere nächsten Schritte und in welcher Reihenfolge? 
- Was sind unsere Ziele bis zur nächsten Woche?

**Comment by ImmunHeldin-CE** [comment]
**Brainstorming Dominik:** 

In meinen Augen ist die grundsätzliche Strategie derzeit:
Wir fokussieren uns derzeit darauf Personen, die bereits Covid19 hatten, eine Liste/Karte von Plasmaspendezentren bereitzustellen. Auf Wunsch können sich Besucher unserer Seite registrieren, um zu einem späteren Zeitpunkt Hilfsgesuche in ihrer Nähe zu erhalten.
So konnten wir schnell viele "Hilfsgesuche" (=Plasmaspendezentren) listen und ein Angebot machen, für das es einen Bedarf gibt (<-- den Bedarf an Plasmaspenden haben wir durch Telefonat mit blutspenden.de und Plasmaspendezentren verifiziert, aber die Lage bzgl. Antikörpertherapie ist nach wie vor unklar. Heißt das, die Spenden werden derzeit nur für Forschungszwecke genutzt?)
Der Erhöhung der Zahl von Blutplasmaspenden ist ein Ziel in sich, aber gleichzeitig auch ein Zwischenschritt für uns: Wenn viele Personen über unsere Seite Plasmaspendezentren finden und sich daraufhin bei uns registrieren, bauen wir eine Datenbank an Personen auf, die durch die Plasmaspende einen Antikörpertest gemacht haben (genau gesagt, haben nicht alle Personen, die sich  nach Aufruf eines Plasmaspendezentrums bei uns registrieren einen Antikörpertest gemacht, sondern nur die Personen, die zur Spende zugelassen werden und tatsächlich spenden - wenn ich den medizinischen Prozess richtig verstehe).
Der Knackpunkt ist meines Erachtens der Zeitpunkt, wann wir diesen Personen tatsächlich Hilfsgesuche zukommen lassen - denn wenn man als ImmunHeld:in irgendwo hilft, spielt das Thema Immunität eine Rolle und nicht nur das Vorhandensein von Antikörpern. Hier sehe ich mehrere Möglichkeiten:
Wenn wir einen Bedarf an immunen Helfer:innen verifizieren können, legen wir direkt los mit der Vermittlung.
Wenn wir einen Bedarf an immunen Helfer:innen verifizieren können, warten wir auf gesicherte, wissenschaftliche Erkenntnisse und/oder auf politische Entscheidungen, Gutachten der Ethikkommission zum Thema Immunität etc.
Wir können derzeit keinen Bedarf verifizieren - das würde uns die Entscheidung für den Moment abnehmen, oder?

Zum Thema "Bedarf" noch folgende Gedanken: Derzeit - soweit zumindest mein Stand - gibt es zwar eine politische Diskussion um das Thema Immunität, aber noch keine Rechtssprechung. Es ist also nicht klar, ob Auswahl nach Immunität z.B. ein Verstoß gegen das AGG wäre. Auch sind Arbeitgeber ja zum Gesundheitsschutz ihrer Mitarbeiter:innen verpflichtet - was, solange Immunität noch nicht wissenschaftlich gesichert ist, Probleme bereiten könnte. Ob das und ähnliche, rechtliche Unsicherheitsfaktoren einen Einfluss auf hilfesuchende Organisationen hat, fände ich eine interessant Frage. Das könnte den Bedarf an ImmunHeld:innen mindestens im Bereich Arbeitskräftevermittlung mindern.
Eine weitere, wichtige Frage ist, ob es einen Bedarf an Immunheld:innen gibt, die ohne Nachweis glaubhaft versichern, dass sie bereits Covid19 hatten? Falls eh immer ein Nachweis erbracht werden muss, könnten wir uns einen Fragebogen zum Thema Immunitätsstatus in dem Sinne sparen, dass wir einfach schreiben, dass alle Personen, die vermittelt werden wollen, einen schriftlichen Immunitätsnachweis haben müssen.
Kurz zum 'wie' der Vermittlung:
Ich finde die Idee mit dem Video-Ident, bei dem wir selbst keine Gesundheitsdaten verarbeiten, immer noch sehr charmant. Nachteil ist dabei, dass wir die hilfesuchenden Organisationen etwas allein lassen mit dem Thema Immunitätsnachweis. Auf der anderen Seiten stehen diese aber auch voll in der Verantwortung, wenn sie Leute anstellen oder ehrenamtlich einsetzen - von dem her müssen sie höchstwahrscheinlich eh das Thema Immunität selbst noch einmal prüfen und würden sich nicht auf unsere abgefragten Punkte verlassen (dürfen).
Abschließend eine Sache, die mir hier beim Schreiben erst so richtig bewusst geworden ist:
Wenn hilfesuchende Privatpersonen ImmunHeld:innen bei uns anfragen, sehe ich uns - anders als wenn wir jemanden an eine hilfesuchende Organisation vermitteln - in der Verantwortung, dass diese Vermittlung kein Gesundheitsrisiko für beide Seiten birgt. Hier können wir meiner Meinung nach nicht einfach sagen: "Du hast die FAQs zu Immunität nicht gelesen - nicht unser Problem, dass Du Dich doch angesteckt hast."
Wenn es also einen Bedarf an ImmunHeld:innen von Organisationen gibt, würde ich wenn dann derzeit auch nur an diese und nicht an Privatpersonen vermitteln. Und auch bei der Vermittlung an Organisationen ist mein moralischer Kompass noch nicht entschieden, da die Folgen von nicht-Immunität bei Vermittlung fatal sein könnten.

**Comment by ImmunHeldin-CE** [comment]
**Brainstorming Christine**

In meinen Augen fokussieren wir zurzeit zurecht auf die Vermittlung von Freiwilligen zu Plasmaspendezentren, könnten und sollten allerdings parallel schon hilfesuchende Organisationen anschreiben, um zu ermitteln, ob ein Bedarf für den Einsatz von Covid-19 genesenen besteht. Ansonsten kommen wir womöglich nie zu einer Vermittlung von Ehrenamt und/oder Arbeit.
Zum Thema Immunität / Immunitätsnachweis: Eine Immunität ist nach dem aktuellsten Forschungsstand höchstwahrscheinlich aber eben noch nicht bewiesen. Wahrscheinlich sind Menschen auch unterschiedlich stark immun. Jüngere haben ja meist eine bessere Immunantwort als Ältere. Gut möglich, dass eine wissenschaftlich und mit letzter Sicherheit bewiesene Immunität Jahre nach der Coronakrise feststellbar ist (können mal schauen, wie lange das bei anderen Coronaviren gedauert hat). Darauf sollten wir m. E. nicht warten, weil unser Projekt bis dahin nicht mehr relevant ist. Wir können zwar keine Immunität versprechen aber ein geringeres Ansteckungsrisiko für alle Beteiligten.
Verschiedene Organisationen suchen jetzt schon freiwillige Helfer:innen in der Coronakrise (z.B. die Tafeln), und ich denke, eine Reduzierung des Ansteckungsrisiko durch den Einsatz von Gesundeten ist für sie jetzt schon sehr erstrebenswert und wird es bei einer möglichen zweiten Corona-Welle noch mehr. Es werden sich ja ca. 60% der Bevölkerung anstecken, wenn es vorher keinen Impfstoff gibt.
Wir sollten und können einfach keine Immunität versprechen. Vielleicht geht das so weit, dass wir unseren Namen "ImmunHelden" überdenken sollten. Ich denke, dass eine größtmögliche Transparenz zum Umgang mit diesem Thema das wichtigste ist, und sehe dann auch keine Probleme bei der Vermittlung von Freiwilligen zu hilfesuchenden Privatpersonen.
Das Video-Ident-Verfahren sehe ich auch nach wie vor als super Lösung. Was die datenschutzrechtlichen Problemen einer Vorsortierung angeht, z.B. auch mit einer simplen Angabe, ob eine frühere Infektion (PCR-Test) oder eine Immunantwort,(Antikörpertest) erwiesen ist, schlage ich vor, dass wir uns datenschutzrechtliche Hilfe holen (über eine Ressourcenanfrage via ProjectTogether)

**Comment by weliveindetail** [comment]
> Was die datenschutzrechtlichen Problemen einer Vorsortierung angeht, [...], dass wir uns datenschutzrechtliche Hilfe holen (über eine Ressourcenanfrage via ProjectTogether)

Hab im ProjectTogether Profil ein neues Gesuch angelegt: Beratung Gesundheitsdaten
Bei der Gelegenheit auch gleich einige weitere aktualisiert.

**Comment by weliveindetail** [comment]
@ImmunHeldin-CE wird haben im Team Call viele Punkte geklärt. Deine Zusammenfassung aus Slack, find ich, ist ein gutes Ergebnis für dieses Ticket:

> Mini-Recap (gern ergänzen) der To-Dos:
> * Wir kontaktieren ab sofort möglichst viele potentielle Partnerorganisationen und finden heraus, was diese brauchen. Wenn wir gefragt werden, wie eine Genesung nachgewiesen werden kann, erklären wir, dass wir ein Video-Ident-Verfahren planen. Zur Identifizierung + Kontaktierung eröffnen wir ggf. Issues auf Github bzw. teilen wir uns existierenden selbstständig zu.
> * Wir legen ab sofort auch mit Outreach los. Sonja ist dabei die Hauptansprechpartnerin--> Github
> * Wir verifizieren schnellstmöglich die Infos zu den restlichen Plasmaspendezentren.
> * Wir aktualisieren schnellstmöglich die FAQs auf der Website und stellen den aktuellsten Forschungsstand verständlich dar.
> * Wenn wir mehr UserInnen haben, sollten wir uns Gedanken darüber machen, wie wir den Erfolg unserer Website messen können.

Möchte noch jemand ergänzen? Sonst sehe ich das Ticket für den Moment als gelöst.

**Comment by weliveindetail** [comment]
Hätte auch in die Hall of Fame gepasst 😄
