### ISSUE TITLE
HdM wegen Marketingstudenten als Kapa gegen Credits

### ISSUE THREAD

**Issue by Highkovic** [ImmunHelden/ImmunHelden.de#89]

**Comment by weliveindetail** [comment]
(Oder auch gegen Kompensation pro Stunde)

**Comment by Highkovic** [comment]
Anfrage an Prof. ist raus, team@ nicht in cc, da das indirekte Datenweitergabe wäre - ich kenne die Mailadresse aus anderem Kontext

**Comment by Highkovic** [comment]
Keine Rückmeldung, Nachfassen in der aktuellen KW

**Comment by Highkovic** [comment]
Nachgefasst am 12. Juni per Mail

**Comment by weliveindetail** [comment]
Das ist neuerdings Teil von #135 oder? Vielleicht können wir es zusammenführen?

**Comment by Highkovic** [comment]
Prof. fragt morgen in der Zweitsemestervorlesung seine Bacheloranden, da gibt es Social Credits. :-)

**Comment by Highkovic** [comment]
Call mit Christina von der HdM steht an :-)
