### ISSUE TITLE
ProjectTogether Profil aktualisieren (Ende April)

### ISSUE THREAD

**Issue by weliveindetail** [ImmunHelden/ImmunHelden.de#9]
Ein Anfang, aber da ist sicher noch mehr zu tun:
- Anzeigen für "Kontakte & Netzwerk" ausformulieren: https://wirvsvirus.projecttogether.org/profile
- ...

**Comment by weliveindetail** [comment]
@ImmunHeldin-CE Vielleicht kannst du auch hier nochmal schauen. Das Orga Team hatte uns gebeten unsere Projektseite immer up-to-date zu halten. Vielleicht könnten wir so einen Task 2wöchentlich/monatlich gebrauchen.

**Comment by weliveindetail** [comment]
Mit den Labels hatte ich es anfangs vielleicht etwas übertrieben 😄

**Comment by weliveindetail** [comment]
Unser Statusupdate #2 könnte als Grundlage für die Projektbeschreibung dienen: https://docs.google.com/document/d/1btvLS9NAxgc1mZ6diiYJmM2S_c8zRtUjltLfKfuToEw/edit?usp=sharing

**Comment by weliveindetail** [comment]
Aktuell ist die Editierfunktion kaputt. E-Mail an die Orga:
> Ich kann unser Profil aktuell nicht Updaten, weil ich beim Drücken auf den Stift unten rechts nur eine weiße Seite sehe.
> Vielleicht könnt ihr uns Bescheid geben, wenn es wieder geht.

Antwort sollte (cc) auch bei der team Adresse ankommen.

**Comment by weliveindetail** [comment]
Wir sollten Gesuche für "Reichweite & Sichtbarkeit" zum ProjectTogether Profil hinzuzufügen.

**Comment by ImmunHeldin-CE** [comment]
Die Projektbeschreibung ist aktualisiert! 
Wollen wir mit Anfragen zu "Reichweite und Sichtbarkeit" nicht besser warten, bis unsere Betaphase startet?

**Comment by weliveindetail** [comment]
Hab "Zusätzliche Infos" aktualisiert. Damit wären nur die Gesuche/Angebote übrig, wie besprochen.

**Comment by ImmunHeldin-CE** [comment]
Gesuche zu "Reichweite und Sichtbarkeit" sind gepostet! Fällt dir/euch dazu noch was ein?

**Comment by weliveindetail** [comment]
Sehr schön formuliert!
