### ISSUE TITLE
Einbindung Erklärfilm auf Webseite

### ISSUE THREAD

**Issue by DominikGolle** [ImmunHelden/ImmunHelden.de#91]
Für mich war es auf den ersten Blick nicht verständlich, dass man auf das Bild des Erklärvideos klicken kann, um es abzuspielen. Auch die Nummern auf den wechselnden Bildern verstehe ich nicht.
Vielleicht einfach als youtube-Video (nocookie-Variante) bzw. Heise-Shariff einbinden?

**Comment by weliveindetail** [comment]
War ne schnelle Preview. @DominikGolle Was denkst du jetzt?
https://immunhelden.de#youknow

**Comment by DominikGolle** [comment]
War nebenbei beim Call geschrieben und klingt beim zweiten Lesen etwas harsch - sorry!
Jetzt ist es auf jeden Fall deutlicher, das man draufklicken kann.
Könntest Du das Video bitte noch in der nocookie-Variante einbetten?

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/fyPF3RUv00A" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by weliveindetail** [comment]
No Problemo. Die nocookie Variante kannte ich gar nicht. Danke für den Tipp!
Sollte mit https://github.com/ImmunHelden/ImmunHelden.de/commit/30db745f0b28631719c3064b5fc05445f5538d7b eingebaut sein.
