### ISSUE TITLE
Stadt- und Bahnhofsmission für Beta-Phase kontaktieren

### ISSUE THREAD

**Issue by ImmunHeldin-CE** [ImmunHelden/ImmunHelden.de#93]
Die Stadt- und Bahnhofsmission suchen aktuell verstärkt Freiwillige.

**Comment by ImmunHeldin-CE** [comment]
Stadtmission Berlin per Mail kontaktiert (22.05.), Anruf am 25.05.

**Comment by ImmunHeldin-CE** [comment]
Bei der Stadtmission Berlin heute (25.05.) leider keinen erreicht, nächster Versuch spät. Freitag (29.05.). 
Mail an die Bahnhofsmission Hamburg ist heute (25.05.) raus, telefonischer Kontakt ebenfalls am Freitag.

**Comment by weliveindetail** [comment]
Das ist jetzt Teil von #127 oder? Dann bitte schließen
